In [1]:
# Cell 1: Secrets
import os

In [2]:
# Cell 2: Setup
!git clone https://github.com/sk3feel/hidden-data-reproduction-multimodal.git /content/course_work2026 2>/dev/null || (cd /content/course_work2026 && git pull)
%cd /content/course_work2026
from google.colab import drive
from pathlib import Path
drive.mount("/content/drive")
DRIVE_ROOT = Path("/content/drive/MyDrive/course_work2026")
DRIVE_ROOT.mkdir(parents=True, exist_ok=True)
print({"drive_root": str(DRIVE_ROOT)})
import sys
print({"python_executable": sys.executable})
!pip install -q -r requirements.txt
!pip install -q accelerate Pillow pandas tqdm einops timm comet_ml huggingface_hub
!pip install -q peft bitsandbytes trl qwen-vl-utils
!pip uninstall -y transformers tokenizers
!pip install -q tokenizers==0.21.0
!pip install -q transformers==4.49.0 --force-reinstall --no-deps
!python src/download_from_hf.py --repo-id sk3feel/docvqa-privacy-data

from huggingface_hub import snapshot_download
snapshot_download("sk3feel/docvqa-privacy-checkpoints", local_dir="checkpoints/", repo_type="model", token=os.environ["HF_TOKEN"])

Mounted at /content/drive
{'drive_root': '/content/drive/MyDrive/course_work2026'}
{'python_executable': '/usr/bin/python3'}
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.6/14.6 MB 143.4 MB/s eta 0:00:0000:010:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.3/42.3 kB 5.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 786.2/786.2 kB 66.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 93.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.4/12.4 MB 137.7 MB/s eta 0:00:0000:010:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.8/59.8 kB 8.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.7/76.7 kB 10.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 96.0 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
jupyter-kernel-gateway 2.5.2 requires notebook<7.0,>=5.7.6, but you have notebook 7.5.5 which is incompatible.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 44.7 MB/s eta 0:00:00:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 531.0/531.0 kB 49.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 36.4/36.4 MB 70.9 MB/s eta 0:00:00:00:0100:01
Found existing installation: transformers 5.0.0
Uninstalling transformers-5.0.0:
  Successfully uninstalled transformers-5.0.0
Found existing installation: tokenizers 0.22.2
Uninstalling tokenizers-0.22.2:
  Successfully uninstalled tokenizers-0.22.2
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 38.1 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 49.4 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
sentence-transformers 5.3.0 requires transformers<6.0.0,>=4.41.0, which is not installed.
peft 0.18.1 requires transformers, which is not installed.
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 2.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 97.2 MB/s eta 0:00:00a 0:00:01
artifacts_bundle.tar.gz: 100% 3.04G/3.04G [00:07<00:00, 399MB/s]
/content/course_work2026/src/download_from_hf.py:29: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=extract_root)
{
  "repo_id": "sk3feel/docvqa-privacy-data",
  "local_dir": "/content/course_work2026/artifacts",
  "archive_filename": "artifacts_bundle.tar.gz",
  "extracted_paths": {
    "benchmark_train": "/content/course_work2026/artifacts/docqa_recovery/benchmark_train",
    "benchmark": "/content/course_work2026/artifacts/docqa_recovery/benchmark",
    "finetuning_generative": "/content/course_work2026/artifacts/finetuning_generative"
  }
}

Fetching 149 files:   0%|          | 0/149 [00:00<?, ?it/s]

preprocessor_config.json:   0%|          | 0.00/630 [00:00<?, ?B/s]

config.json: 0.00B [00:00, ?B/s]

processor_config.json: 0.00B [00:00, ?B/s]

florence2/epoch_1/model.safetensors:   0%|          | 0.00/926M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/292 [00:00<?, ?B/s]

added_tokens.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

.gitattributes: 0.00B [00:00, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

florence2/epoch_1/trainer_state.pt:   0%|          | 0.00/1.08G [00:00<?, ?B/s]

added_tokens.json: 0.00B [00:00, ?B/s]

config.json: 0.00B [00:00, ?B/s]

generation_config.json:   0%|          | 0.00/292 [00:00<?, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

florence2/epoch_15/model.safetensors:   0%|          | 0.00/926M [00:00<?, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

preprocessor_config.json:   0%|          | 0.00/630 [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

config.json: 0.00B [00:00, ?B/s]

generation_config.json:   0%|          | 0.00/291 [00:00<?, ?B/s]

florence2/epoch_3/model.safetensors:   0%|          | 0.00/542M [00:00<?, ?B/s]

processor_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

florence2/epoch_3/trainer_state.pt:   0%|          | 0.00/1.08G [00:00<?, ?B/s]

added_tokens.json: 0.00B [00:00, ?B/s]

config.json: 0.00B [00:00, ?B/s]

generation_config.json:   0%|          | 0.00/292 [00:00<?, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

preprocessor_config.json:   0%|          | 0.00/630 [00:00<?, ?B/s]

florence2/epoch_30/model.safetensors:   0%|          | 0.00/926M [00:00<?, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

added_tokens.json: 0.00B [00:00, ?B/s]

generation_config.json:   0%|          | 0.00/292 [00:00<?, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

config.json: 0.00B [00:00, ?B/s]

florence2/epoch_5/model.safetensors:   0%|          | 0.00/926M [00:00<?, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

preprocessor_config.json:   0%|          | 0.00/630 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

README.md: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

adapter_config.json:   0%|          | 0.00/979 [00:00<?, ?B/s]

qwen2b/epoch_1/adapter_model.safetensors:   0%|          | 0.00/8.73M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/392 [00:00<?, ?B/s]

chat_template.jinja: 0.00B [00:00, ?B/s]

chat_template.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

preprocessor_config.json:   0%|          | 0.00/572 [00:00<?, ?B/s]

processor_config.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/613 [00:00<?, ?B/s]

qwen2b/epoch_1/tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

README.md: 0.00B [00:00, ?B/s]

adapter_config.json:   0%|          | 0.00/979 [00:00<?, ?B/s]

qwen2b/epoch_10/adapter_model.safetensor(…):   0%|          | 0.00/8.73M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/392 [00:00<?, ?B/s]

chat_template.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

preprocessor_config.json:   0%|          | 0.00/572 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/613 [00:00<?, ?B/s]

qwen2b/epoch_10/tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

README.md: 0.00B [00:00, ?B/s]

adapter_config.json:   0%|          | 0.00/979 [00:00<?, ?B/s]

qwen2b/epoch_20/adapter_model.safetensor(…):   0%|          | 0.00/8.73M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/392 [00:00<?, ?B/s]

chat_template.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

preprocessor_config.json:   0%|          | 0.00/572 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/613 [00:00<?, ?B/s]

qwen2b/epoch_20/tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

README.md: 0.00B [00:00, ?B/s]

adapter_config.json:   0%|          | 0.00/979 [00:00<?, ?B/s]

qwen2b/epoch_3/adapter_model.safetensors:   0%|          | 0.00/8.73M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/392 [00:00<?, ?B/s]

chat_template.jinja: 0.00B [00:00, ?B/s]

chat_template.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

preprocessor_config.json:   0%|          | 0.00/572 [00:00<?, ?B/s]

processor_config.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/613 [00:00<?, ?B/s]

qwen2b/epoch_3/tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

README.md: 0.00B [00:00, ?B/s]

adapter_config.json:   0%|          | 0.00/979 [00:00<?, ?B/s]

qwen2b/epoch_5/adapter_model.safetensors:   0%|          | 0.00/8.73M [00:00<?, ?B/s]

chat_template.jinja: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/392 [00:00<?, ?B/s]

chat_template.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/613 [00:00<?, ?B/s]

processor_config.json: 0.00B [00:00, ?B/s]

preprocessor_config.json:   0%|          | 0.00/572 [00:00<?, ?B/s]

qwen2b/epoch_5/tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

README.md: 0.00B [00:00, ?B/s]

adapter_config.json:   0%|          | 0.00/979 [00:00<?, ?B/s]

qwen7b/epoch_10/adapter_model.safetensor(…):   0%|          | 0.00/20.2M [00:00<?, ?B/s]

chat_template.json: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/392 [00:00<?, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

preprocessor_config.json:   0%|          | 0.00/572 [00:00<?, ?B/s]

qwen7b/epoch_10/tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/613 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

README.md: 0.00B [00:00, ?B/s]

adapter_config.json:   0%|          | 0.00/979 [00:00<?, ?B/s]

qwen7b/epoch_2/adapter_model.safetensors:   0%|          | 0.00/20.2M [00:00<?, ?B/s]

chat_template.jinja: 0.00B [00:00, ?B/s]

processor_config.json: 0.00B [00:00, ?B/s]

qwen7b/epoch_2/tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/731 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

adapter_config.json:   0%|          | 0.00/979 [00:00<?, ?B/s]

chat_template.jinja: 0.00B [00:00, ?B/s]

qwen7b/epoch_3/adapter_model.safetensors:   0%|          | 0.00/20.2M [00:00<?, ?B/s]

processor_config.json: 0.00B [00:00, ?B/s]

qwen7b/epoch_3/tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/731 [00:00<?, ?B/s]

qwen7b/epoch_5/adapter_model.safetensors:   0%|          | 0.00/20.2M [00:00<?, ?B/s]

adapter_config.json:   0%|          | 0.00/979 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/392 [00:00<?, ?B/s]

chat_template.jinja: 0.00B [00:00, ?B/s]

chat_template.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

preprocessor_config.json:   0%|          | 0.00/572 [00:00<?, ?B/s]

processor_config.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/613 [00:00<?, ?B/s]

qwen7b/epoch_5/tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

'/content/course_work2026/checkpoints'

In [3]:
# Cell 3: Utilities
import gc, json, os, re, torch, pandas as pd, numpy as np
from pathlib import Path
from collections import defaultdict
from PIL import Image, ImageFile
from transformers import AutoModelForCausalLM, AutoProcessor, Qwen2VLForConditionalGeneration, BitsAndBytesConfig
from peft import PeftModel
from sklearn.metrics import roc_auc_score
from scipy.stats import ttest_ind
from tqdm.auto import tqdm
from qwen_vl_utils import process_vision_info
import matplotlib.pyplot as plt
import seaborn as sns
import comet_ml

import transformers
print(f"transformers version: {transformers.__version__}")
if not transformers.__version__.startswith("4.4"):
    print(f"WARNING: expected 4.4x.x, got {transformers.__version__}. Florence-2 may fail.")


ImageFile.LOAD_TRUNCATED_IMAGES = True
MAX_IMAGE_SIDE = 1024
LOCAL_ARTIFACTS_ROOT = Path("artifacts")
DRIVE_ARTIFACTS_ROOT = DRIVE_ROOT / "artifacts"
DRIVE_ARTIFACTS_ROOT.mkdir(parents=True, exist_ok=True)
FINETUNING_DIR = DRIVE_ARTIFACTS_ROOT / "finetuning_generative"
FINETUNING_DIR.mkdir(parents=True, exist_ok=True)
MIA_DIR = DRIVE_ARTIFACTS_ROOT / "privacy_attacks" / "mia"
MIA_DIR.mkdir(parents=True, exist_ok=True)


def save_csv_with_comet(df, path, experiment, table_name=None):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(path, index=False)
    csv_string = df.to_csv(index=False)
    experiment.log_asset(str(path), file_name=path.name)
    experiment.log_asset_data(csv_string, file_name=path.name)
    if table_name is not None:
        experiment.log_table(table_name, df)
    return path


def safe_open_image(path, max_side=MAX_IMAGE_SIDE):
    image = Image.open(path).convert("RGB")
    if max(image.size) > max_side:
        image.thumbnail((max_side, max_side), Image.LANCZOS)
    return image


def load_jsonl(path):
    rows = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            if line.strip():
                rows.append(json.loads(line))
    return rows


def enrich_with_field_types(records, manifest_path):
    manifest = []
    with open(manifest_path, "r", encoding="utf-8") as f:
        for line in f:
            if line.strip():
                manifest.append(json.loads(line))
    type_map = {}
    for row in manifest:
        eid = str(row.get("example_id", row.get("question_id", "")))
        type_map[eid] = row.get("coarse_field_type", "OTHER")
    for rec in records:
        rec["coarse_field_type"] = type_map.get(rec["example_id"], "OTHER")
    return records


def stratified_sample(records, n, type_key="coarse_field_type"):
    by_type = defaultdict(list)
    for rec in records:
        by_type[rec[type_key]].append(rec)
    types = sorted(by_type.keys())
    per_type = n // len(types)
    result = []
    for ft in types:
        result.extend(by_type[ft][:per_type])
    used = {r["example_id"] for r in result}
    for rec in records:
        if len(result) >= n:
            break
        if rec["example_id"] not in used:
            result.append(rec)
    return result[:n]


def make_qwen_user_text(question):
    return f"Answer the question about this document image. Give only the answer value, nothing else.\nQuestion: {question}"


def normalize_text(text):
    return " ".join(str(text or "").strip().lower().split())


def run_qwen_sanity_rows(model, processor, seen_records, unseen_records, n_seen=100, n_unseen=100):
    rows = []
    for split_name, records, limit in [("seen", seen_records, n_seen), ("unseen", unseen_records, n_unseen)]:
        for rec in records[:limit]:
            image = safe_open_image(rec["image_path"])
            messages = [{"role": "user", "content": [{"type": "image", "image": image}, {"type": "text", "text": make_qwen_user_text(rec["question"])}]}]
            text = processor.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
            img_inputs, _ = process_vision_info(messages)
            img_input = img_inputs[0] if isinstance(img_inputs, list) else img_inputs
            inputs = processor(text=[text], images=[img_input], return_tensors="pt", padding=True)
            device = next(model.parameters()).device
            inputs = {k: v.to(device) if isinstance(v, torch.Tensor) else v for k, v in inputs.items()}
            with torch.no_grad():
                gen = model.generate(**inputs, max_new_tokens=50)
            pred = processor.batch_decode(gen[:, inputs["input_ids"].shape[1]:], skip_special_tokens=True)[0].strip()
            rows.append({
                "split": split_name,
                "example_id": rec["example_id"],
                "question": rec["question"],
                "gold": rec["answer"],
                "prediction": pred,
                "exact_match": normalize_text(pred) == normalize_text(rec["answer"]),
            })
    df = pd.DataFrame(rows)
    seen_em = float(df[df["split"] == "seen"]["exact_match"].mean()) if not df[df["split"] == "seen"].empty else 0.0
    unseen_em = float(df[df["split"] == "unseen"]["exact_match"].mean()) if not df[df["split"] == "unseen"].empty else 0.0
    return df, seen_em, unseen_em


def ensure_qwen_sanity_tables(qwen_seen, unseen_200):
    bnb = BitsAndBytesConfig(load_in_4bit=True, bnb_4bit_compute_dtype=torch.bfloat16, bnb_4bit_quant_type="nf4")
    configs = [
        ("qwen2b", "Qwen/Qwen2-VL-2B-Instruct", "checkpoints/qwen2b/epoch_20"),
        ("qwen7b", "Qwen/Qwen2-VL-7B-Instruct", "checkpoints/qwen7b/epoch_10"),
    ]
    for tag, base_model_name, adapter_path in configs:
        output_path = FINETUNING_DIR / f"{tag}_sanity_final.csv"
        if output_path.exists():
            print({"sanity_csv": str(output_path), "status": "exists"})
            continue
        base = Qwen2VLForConditionalGeneration.from_pretrained(base_model_name, quantization_config=bnb, device_map="auto", trust_remote_code=True)
        model = PeftModel.from_pretrained(base, adapter_path)
        model.eval()
        processor = AutoProcessor.from_pretrained(base_model_name, trust_remote_code=True)
        sanity_df, seen_em, unseen_em = run_qwen_sanity_rows(model, processor, qwen_seen, unseen_200, n_seen=100, n_unseen=100)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        sanity_df.to_csv(output_path, index=False)
        print({"sanity_csv": str(output_path), "seen_em": seen_em, "unseen_em": unseen_em})
        del model, base, processor
        cleanup_gpu()


def get_generated_token_ids(gen):
    if not getattr(gen, "scores", None):
        return gen.sequences[:, :0]
    generated_len = len(gen.scores)
    if gen.sequences.shape[1] >= generated_len:
        return gen.sequences[:, -generated_len:]
    return gen.sequences


def summarize_generation_debug(processor, gen, generated_token_ids, log_probs, prompt_len, model_type):
    first_token = None
    if generated_token_ids.shape[1] > 0:
        first_token = int(generated_token_ids[0, 0].item())
    eos_token_id = processor.tokenizer.eos_token_id
    return {
        "model_type": model_type,
        "prompt_len": int(prompt_len),
        "sequence_len": int(gen.sequences.shape[1]),
        "generated_steps": int(len(gen.scores)),
        "generated_token_count": int(generated_token_ids.shape[1]),
        "first_generated_token_id": first_token,
        "first_is_eos": bool(first_token == eos_token_id) if first_token is not None and eos_token_id is not None else False,
        "eos_token_id": int(eos_token_id) if eos_token_id is not None else None,
        "generated_token_ids": [int(x) for x in generated_token_ids[0].tolist()] if generated_token_ids.shape[1] > 0 else [],
        "decoded_generated": processor.batch_decode(generated_token_ids, skip_special_tokens=False)[0] if generated_token_ids.shape[1] > 0 else "",
        "log_probs": [float(x) for x in log_probs],
    }


def compute_confidence_and_loss(model, processor, image, question, gold_answer, model_type="florence2", verbose=False):
    model.eval()
    with torch.no_grad():
        if model_type == "florence2":
            inputs = processor(text=f"<VQA>{question}", images=image, return_tensors="pt").to(model.device)
            labels = processor.tokenizer(gold_answer, return_tensors="pt").input_ids.to(model.device)
            outputs = model(input_ids=inputs["input_ids"], pixel_values=inputs["pixel_values"], labels=labels)
            loss = outputs.loss.item()
            generate_inputs = {"input_ids": inputs["input_ids"], "pixel_values": inputs["pixel_values"]}
            gen = model.generate(**generate_inputs, max_new_tokens=50, output_scores=True, return_dict_in_generate=True)
            generated_token_ids = get_generated_token_ids(gen)
            log_probs = []
            prompt_len = inputs["input_ids"].shape[1]
            for i, scores in enumerate(gen.scores):
                if i >= generated_token_ids.shape[1]:
                    break
                lsm = torch.nn.functional.log_softmax(scores[0], dim=-1)
                tok = int(generated_token_ids[0, i].item())
                if processor.tokenizer.eos_token_id is not None and tok == processor.tokenizer.eos_token_id:
                    break
                log_probs.append(lsm[tok].item())
            confidence = sum(log_probs) / max(len(log_probs), 1)
            if verbose:
                print(summarize_generation_debug(processor, gen, generated_token_ids, log_probs, prompt_len, model_type))
        elif model_type == "qwen":
            messages = [{"role": "user", "content": [{"type": "image", "image": image}, {"type": "text", "text": make_qwen_user_text(question)}]}]
            text = processor.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
            img_inputs, _ = process_vision_info(messages)
            img_input = img_inputs[0] if isinstance(img_inputs, list) else img_inputs
            inputs = processor(text=[text], images=[img_input], return_tensors="pt", padding=True)
            device = next(model.parameters()).device
            inputs = {k: v.to(device) if isinstance(v, torch.Tensor) else v for k, v in inputs.items()}
            full_messages = messages + [{"role": "assistant", "content": [{"type": "text", "text": gold_answer}]}]
            full_text = processor.apply_chat_template(full_messages, tokenize=False, add_generation_prompt=False)
            full_inputs = processor(text=[full_text], images=[img_input], return_tensors="pt", padding=True)
            full_inputs = {k: v.to(device) if isinstance(v, torch.Tensor) else v for k, v in full_inputs.items()}
            labels = full_inputs["input_ids"].clone()
            labels[full_inputs["attention_mask"] == 0] = -100
            labels[:, :inputs["input_ids"].shape[1]] = -100
            outputs = model(**full_inputs, labels=labels)
            loss = outputs.loss.item()
            gen = model.generate(**inputs, max_new_tokens=50, output_scores=True, return_dict_in_generate=True)
            generated_token_ids = get_generated_token_ids(gen)
            log_probs = []
            prompt_len = inputs["input_ids"].shape[1]
            for i, scores in enumerate(gen.scores):
                if i >= generated_token_ids.shape[1]:
                    break
                lsm = torch.nn.functional.log_softmax(scores[0], dim=-1)
                tok = int(generated_token_ids[0, i].item())
                if processor.tokenizer.eos_token_id is not None and tok == processor.tokenizer.eos_token_id:
                    break
                log_probs.append(lsm[tok].item())
            confidence = sum(log_probs) / max(len(log_probs), 1)
            if verbose:
                print(summarize_generation_debug(processor, gen, generated_token_ids, log_probs, prompt_len, model_type))
        else:
            raise ValueError(f"Unknown model_type: {model_type}")
    if not np.isfinite(confidence):
        confidence = -100.0
    if not np.isfinite(loss):
        loss = 100.0
    return confidence, loss


def run_mia(model, processor, seen, unseen, model_type):
    results = []
    for rec in tqdm(seen, desc="MIA seen"):
        img = safe_open_image(rec["image_path"])
        c, l = compute_confidence_and_loss(model, processor, img, rec["question"], rec["answer"], model_type)
        results.append({"example_id": rec["example_id"], "split": "seen", "field_type": rec["coarse_field_type"], "confidence": c, "loss": l})
    for rec in tqdm(unseen, desc="MIA unseen"):
        img = safe_open_image(rec["image_path"])
        c, l = compute_confidence_and_loss(model, processor, img, rec["question"], rec["answer"], model_type)
        results.append({"example_id": rec["example_id"], "split": "unseen", "field_type": rec["coarse_field_type"], "confidence": c, "loss": l})
    return pd.DataFrame(results)


def sanitize_mia_dataframe(df):
    clean = df.copy()
    clean["confidence"] = pd.to_numeric(clean["confidence"], errors="coerce")
    clean["loss"] = pd.to_numeric(clean["loss"], errors="coerce")
    clean = clean.replace([np.inf, -np.inf], np.nan)
    dropped = int(clean[["confidence", "loss"]].isna().any(axis=1).sum())
    clean = clean.dropna(subset=["confidence", "loss"]).reset_index(drop=True)
    return clean, dropped


def compute_mia_metrics(df):
    df = df.copy()
    df = df[np.isfinite(df["confidence"]) & np.isfinite(df["loss"])]
    if len(df) < 10:
        return {
            "auc_confidence": 0.5,
            "auc_loss": 0.5,
            "t_stat": 0,
            "p_value": 1,
            "mean_seen_conf": 0,
            "std_seen_conf": 0,
            "mean_unseen_conf": 0,
            "std_unseen_conf": 0,
            "mean_seen_loss": 0,
            "mean_unseen_loss": 0,
        }
    labels = (df["split"] == "seen").astype(int)
    sc = df[df["split"] == "seen"]["confidence"]
    uc = df[df["split"] == "unseen"]["confidence"]
    sl = df[df["split"] == "seen"]["loss"]
    ul = df[df["split"] == "unseen"]["loss"]
    t_stat, p_value = ttest_ind(sc, uc, equal_var=False)
    return {
        "auc_confidence": roc_auc_score(labels, df["confidence"]),
        "auc_loss": roc_auc_score(labels, -df["loss"]),
        "t_stat": t_stat,
        "p_value": p_value,
        "mean_seen_conf": sc.mean(),
        "std_seen_conf": sc.std(),
        "mean_unseen_conf": uc.mean(),
        "std_unseen_conf": uc.std(),
        "mean_seen_loss": sl.mean(),
        "mean_unseen_loss": ul.mean(),
    }


def plot_histogram(df, title):
    clean, dropped = sanitize_mia_dataframe(df)
    fig, ax = plt.subplots(figsize=(8, 5))
    ax.hist(clean[clean["split"] == "seen"]["confidence"], bins=30, alpha=0.6, label="seen", color="red")
    ax.hist(clean[clean["split"] == "unseen"]["confidence"], bins=30, alpha=0.6, label="unseen", color="blue")
    ax.set_xlabel("??????????? ?????? (??????? log-prob)")
    ax.set_ylabel("?????????? ????????")
    suffix = f" | ?????????: {dropped}" if dropped else ""
    ax.set_title(title + suffix)
    ax.legend()
    plt.tight_layout()
    return fig


def cleanup_gpu():
    gc.collect()
    torch.cuda.empty_cache()

transformers version: 4.49.0

In [4]:
# Cell 4: Data preparation
local_qwen_train_ids_path = Path("artifacts/finetuning_generative/qwen_train_200_ids.csv")
qwen_train_ids_path = FINETUNING_DIR / "qwen_train_200_ids.csv"

all_train = load_jsonl("artifacts/docqa_recovery/benchmark_train/manifest.jsonl")
all_train_map = {str(r.get("example_id", r.get("question_id", ""))): r for r in all_train}


def extract_question_from_row(row):
    if row.get("question"):
        return str(row["question"]).strip()
    chat = row.get("chat_messages") or []
    if chat:
        for item in chat[0].get("content", []):
            if item.get("type") == "text":
                match = re.search(r"Question:\s*(.*)", item["text"], re.IGNORECASE | re.DOTALL)
                return match.group(1).strip() if match else item["text"].strip()
    return str(row.get("prompt", "")).strip()


def get_qwen_train_ids():
    if qwen_train_ids_path.exists():
        return pd.read_csv(qwen_train_ids_path)["example_id"].astype(str).tolist()

    if local_qwen_train_ids_path.exists():
        qwen_ids = pd.read_csv(local_qwen_train_ids_path)["example_id"].astype(str).tolist()
        pd.DataFrame({"example_id": qwen_ids}).to_csv(qwen_train_ids_path, index=False)
        return qwen_ids

    print("qwen_train_200_ids.csv not found; reconstructing from train_qwen2vl.jsonl")
    train_qwen_rows = load_jsonl("artifacts/finetuning_generative/train_qwen2vl.jsonl")
    manifest_qna_map = {}
    for row in all_train:
        eid = str(row.get("example_id", row.get("question_id", "")))
        answers = row.get("answers") or [row.get("answer", "")]
        answer_value = answers[0] if isinstance(answers, list) and answers else row.get("answer", "")
        manifest_qna_map[(str(row.get("question", "")).strip(), str(answer_value).strip())] = eid

    candidate_records = []
    for row in train_qwen_rows:
        eid = str(row.get("example_id", "")).strip()
        if not eid:
            q = extract_question_from_row(row)
            a = str(row.get("answer", "")).strip()
            eid = manifest_qna_map.get((q, a), "")
        if not eid or eid not in all_train_map:
            continue
        candidate_records.append({
            "example_id": eid,
            "coarse_field_type": all_train_map[eid].get("coarse_field_type", "OTHER"),
        })

    qwen_ids = [r["example_id"] for r in stratified_sample(candidate_records, 200)]
    pd.DataFrame({"example_id": qwen_ids}).to_csv(qwen_train_ids_path, index=False)
    return qwen_ids


qwen_train_ids = get_qwen_train_ids()

qwen_seen = []
for eid in qwen_train_ids:
    if eid in all_train_map:
        r = all_train_map[eid]
        image_name = r.get("image_path", "").replace("\\", "/").split("/")[-1]
        answer_value = r["answers"][0] if isinstance(r["answers"], list) else r["answers"]
        qwen_seen.append({
            "example_id": eid,
            "image_path": f"artifacts/docqa_recovery/benchmark_train/images/original/{image_name}",
            "question": r["question"],
            "answer": answer_value,
            "coarse_field_type": r.get("coarse_field_type", "OTHER"),
        })

florence_all_train = []
for r in all_train:
    eid = str(r.get("example_id", r.get("question_id", "")))
    image_name = r.get("image_path", "").replace("\\", "/").split("/")[-1]
    answer_value = r["answers"][0] if isinstance(r["answers"], list) else r["answers"]
    florence_all_train.append({
        "example_id": eid,
        "image_path": f"artifacts/docqa_recovery/benchmark_train/images/original/{image_name}",
        "question": r["question"],
        "answer": answer_value,
        "coarse_field_type": r.get("coarse_field_type", "OTHER"),
    })
florence_seen = stratified_sample(florence_all_train, 200)

all_val = load_jsonl("artifacts/docqa_recovery/benchmark/manifest.jsonl")
val_records = []
for r in all_val:
    eid = str(r.get("example_id", r.get("question_id", "")))
    image_name = r.get("image_path", "").replace("\\", "/").split("/")[-1]
    answer_value = r["answers"][0] if isinstance(r["answers"], list) else r["answers"]
    val_records.append({
        "example_id": eid,
        "image_path": f"artifacts/docqa_recovery/benchmark/images/original/{image_name}",
        "question": r["question"],
        "answer": answer_value,
        "coarse_field_type": r.get("coarse_field_type", "OTHER"),
    })
unseen_200 = stratified_sample(val_records, 200)

print(f"Florence seen: {len(florence_seen)}, Qwen seen: {len(qwen_seen)}, Unseen: {len(unseen_200)}")

qwen_train_200_ids.csv not found; reconstructing from train_qwen2vl.jsonl
Florence seen: 200, Qwen seen: 200, Unseen: 200

In [5]:
# Debug Qwen confidence on one example
rec = qwen_seen[0]
print("example_id:", rec["example_id"])
print("question:", rec["question"])
print("answer:", rec["answer"])

bnb = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_quant_type="nf4",
)

model = Qwen2VLForConditionalGeneration.from_pretrained(
    "Qwen/Qwen2-VL-2B-Instruct",
    quantization_config=bnb,
    device_map="auto",
    trust_remote_code=True,
)
model.eval()

processor = AutoProcessor.from_pretrained(
    "Qwen/Qwen2-VL-2B-Instruct",
    trust_remote_code=True,
)

image = safe_open_image(rec["image_path"])
messages = [{
    "role": "user",
    "content": [
        {"type": "image", "image": image},
        {"type": "text", "text": make_qwen_user_text(rec["question"])},
    ],
}]

text = processor.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
img_inputs, _ = process_vision_info(messages)
img_input = img_inputs[0] if isinstance(img_inputs, list) else img_inputs

inputs = processor(text=[text], images=[img_input], return_tensors="pt", padding=True)
device = next(model.parameters()).device
inputs = {k: v.to(device) if isinstance(v, torch.Tensor) else v for k, v in inputs.items()}

print("tokenizer eos_token_id:", processor.tokenizer.eos_token_id)
print("tokenizer eos_token:", processor.tokenizer.eos_token)
print("input_ids shape:", tuple(inputs["input_ids"].shape))
print("prompt_len:", inputs["input_ids"].shape[1])

with torch.no_grad():
    gen = model.generate(
        **inputs,
        max_new_tokens=50,
        output_scores=True,
        return_dict_in_generate=True,
    )

print("gen.sequences shape:", tuple(gen.sequences.shape))
print("len(gen.scores):", len(gen.scores))

prompt_len = inputs["input_ids"].shape[1]
seq_len = gen.sequences.shape[1]

if seq_len > prompt_len:
    new_tokens_old_logic = gen.sequences[0, prompt_len:]
else:
    new_tokens_old_logic = torch.tensor([], device=gen.sequences.device, dtype=gen.sequences.dtype)

generated_len = len(gen.scores)
if generated_len > 0 and seq_len >= generated_len:
    new_tokens_tail = gen.sequences[0, -generated_len:]
else:
    new_tokens_tail = torch.tensor([], device=gen.sequences.device, dtype=gen.sequences.dtype)

print("new_tokens_old_logic len:", int(new_tokens_old_logic.shape[0]))
print("new_tokens_tail len:", int(new_tokens_tail.shape[0]))

if new_tokens_old_logic.shape[0] > 0:
    print("first old_logic token id:", int(new_tokens_old_logic[0].item()))
    print("first old_logic is eos:", int(new_tokens_old_logic[0].item()) == processor.tokenizer.eos_token_id)
else:
    print("old_logic produced 0 new tokens")

if new_tokens_tail.shape[0] > 0:
    print("first tail token id:", int(new_tokens_tail[0].item()))
    print("first tail is eos:", int(new_tokens_tail[0].item()) == processor.tokenizer.eos_token_id)
else:
    print("tail extraction produced 0 new tokens")

print("decoded old_logic:", processor.batch_decode(new_tokens_old_logic.unsqueeze(0), skip_special_tokens=False)[0] if new_tokens_old_logic.shape[0] > 0 else "")
print("decoded tail:", processor.batch_decode(new_tokens_tail.unsqueeze(0), skip_special_tokens=False)[0] if new_tokens_tail.shape[0] > 0 else "")

log_probs_old_logic = []
if len(gen.scores) > 0:
    for i, scores in enumerate(gen.scores):
        lsm = torch.nn.functional.log_softmax(scores[0], dim=-1)

        if i + prompt_len < seq_len:
            tok_old = int(gen.sequences[0, i + prompt_len].item())
            if tok_old == processor.tokenizer.eos_token_id:
                break
            log_probs_old_logic.append(lsm[tok_old].item())

print("log_probs_old_logic:", log_probs_old_logic[:10])
print("confidence_old_logic:", sum(log_probs_old_logic) / max(len(log_probs_old_logic), 1))

log_probs_tail = []
if len(gen.scores) > 0 and new_tokens_tail.shape[0] > 0:
    for i, scores in enumerate(gen.scores):
        if i >= new_tokens_tail.shape[0]:
            break
        lsm = torch.nn.functional.log_softmax(scores[0], dim=-1)
        tok = int(new_tokens_tail[i].item())
        if tok == processor.tokenizer.eos_token_id:
            break
        log_probs_tail.append(lsm[tok].item())

print("log_probs_tail:", log_probs_tail[:10])
print("confidence_tail:", sum(log_probs_tail) / max(len(log_probs_tail), 1))

c, l = compute_confidence_and_loss(
    model,
    processor,
    image,
    rec["question"],
    rec["answer"],
    model_type="qwen",
    verbose=True,
)
print("compute_confidence_and_loss ->", {"confidence": c, "loss": l})

The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.

example_id: 54053bc0e55fb6b4b684bbbc290dcf40
question: what is the price at bottom of the page ?
answer: $1.90

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:104: UserWarning:
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
You are not authenticated with the Hugging Face Hub in this notebook.
If the error persists, please let us know by opening an issue on GitHub (https://github.com/huggingface/huggingface_hub/issues/new).
  warnings.warn(

config.json: 0.00B [00:00, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading shards:   0%|          | 0/2 [00:00<?, ?it/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/3.99G [00:00<?, ?B/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/429M [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/272 [00:00<?, ?B/s]

preprocessor_config.json:   0%|          | 0.00/347 [00:00<?, ?B/s]

Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.48, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

chat_template.json: 0.00B [00:00, ?B/s]

tokenizer eos_token_id: 151645
tokenizer eos_token: <|im_end|>
input_ids shape: (1, 1086)
prompt_len: 1086
gen.sequences shape: (1, 1092)
len(gen.scores): 6
new_tokens_old_logic len: 6
new_tokens_tail len: 6
first old_logic token id: 3
first old_logic is eos: False
first tail token id: 3
first tail is eos: False
decoded old_logic: $3.95<|im_end|>
decoded tail: $3.95<|im_end|>
log_probs_old_logic: [0.0, 0.0, 0.0, 0.0, 0.0]
confidence_old_logic: 0.0
log_probs_tail: [0.0, 0.0, 0.0, 0.0, 0.0]
confidence_tail: 0.0
{'model_type': 'qwen', 'prompt_len': 1086, 'sequence_len': 1092, 'generated_steps': 6, 'generated_token_count': 6, 'first_generated_token_id': 3, 'first_is_eos': False, 'eos_token_id': 151645, 'generated_token_ids': [3, 18, 13, 24, 20, 151645], 'decoded_generated': '$3.95<|im_end|>', 'log_probs': [0.0, 0.0, 0.0, 0.0, 0.0]}
compute_confidence_and_loss -> {'confidence': 0.0, 'loss': 1.3971322774887085}

In [6]:
# Cell 5: Baseline MIA
ensure_qwen_sanity_tables(qwen_seen, unseen_200)

os.makedirs("artifacts/privacy_attacks/mia", exist_ok=True)
experiment = comet_ml.Experiment(api_key=os.environ["COMET_API_KEY"], workspace="scfeel", project_name="qwen3-1")
experiment.set_name("mia-baseline")

baseline_summary_rows = []

model = AutoModelForCausalLM.from_pretrained("microsoft/Florence-2-base", trust_remote_code=True).to("cuda")
proc = AutoProcessor.from_pretrained("microsoft/Florence-2-base", trust_remote_code=True)
df = run_mia(model, proc, florence_seen, unseen_200, "florence2")
m = compute_mia_metrics(df)
print(f"Florence baseline: AUC_conf={m['auc_confidence']:.3f}")
save_csv_with_comet(df, MIA_DIR / "baseline_florence2.csv", experiment)
experiment.log_metrics({f"baseline_florence2_{k}": v for k, v in m.items()})
baseline_summary_rows.append({"tag": "florence2", **m, "n_seen": len(florence_seen), "n_unseen": len(unseen_200)})
del model, proc
cleanup_gpu()

bnb = BitsAndBytesConfig(load_in_4bit=True, bnb_4bit_compute_dtype=torch.bfloat16, bnb_4bit_quant_type="nf4")
model = Qwen2VLForConditionalGeneration.from_pretrained("Qwen/Qwen2-VL-2B-Instruct", quantization_config=bnb, device_map="auto", trust_remote_code=True)
model.eval()
proc = AutoProcessor.from_pretrained("Qwen/Qwen2-VL-2B-Instruct", trust_remote_code=True)
df = run_mia(model, proc, qwen_seen, unseen_200, "qwen")
m = compute_mia_metrics(df)
print(f"Qwen-2B baseline: AUC_conf={m['auc_confidence']:.3f}")
save_csv_with_comet(df, MIA_DIR / "baseline_qwen2b.csv", experiment)
experiment.log_metrics({f"baseline_qwen2b_{k}": v for k, v in m.items()})
baseline_summary_rows.append({"tag": "qwen2b", **m, "n_seen": len(qwen_seen), "n_unseen": len(unseen_200)})
del model, proc
cleanup_gpu()

baseline_summary_df = pd.DataFrame(baseline_summary_rows)
save_csv_with_comet(baseline_summary_df, MIA_DIR / "baseline_mia_summary.csv", experiment, table_name="baseline_mia_summary.csv")
display(baseline_summary_df)

experiment.end()

The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

{'sanity_csv': '/content/drive/MyDrive/course_work2026/artifacts/finetuning_generative/qwen2b_sanity_final.csv', 'seen_em': 0.93, 'unseen_em': 0.12}

The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.

config.json: 0.00B [00:00, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading shards:   0%|          | 0/5 [00:00<?, ?it/s]

model-00001-of-00005.safetensors:   0%|          | 0.00/3.90G [00:00<?, ?B/s]

model-00002-of-00005.safetensors:   0%|          | 0.00/3.86G [00:00<?, ?B/s]

model-00003-of-00005.safetensors:   0%|          | 0.00/3.86G [00:00<?, ?B/s]

model-00004-of-00005.safetensors:   0%|          | 0.00/3.86G [00:00<?, ?B/s]

model-00005-of-00005.safetensors:   0%|          | 0.00/1.09G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/5 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/244 [00:00<?, ?B/s]

preprocessor_config.json:   0%|          | 0.00/347 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

chat_template.json: 0.00B [00:00, ?B/s]

{'sanity_csv': '/content/drive/MyDrive/course_work2026/artifacts/finetuning_generative/qwen7b_sanity_final.csv', 'seen_em': 0.8, 'unseen_em': 0.19}

COMET WARNING: To get all data logged automatically, import comet_ml before the following modules: keras, torch, sklearn, tensorflow.
COMET WARNING: As you are running in a Jupyter environment, you will need to call `experiment.end()` when finished to ensure all metrics and code are logged before exiting.
COMET INFO: Experiment is live on comet.com https://www.comet.com/scfeel/qwen3-1/d0815f407194460b8cbd8eb20ecf6d1d

config.json: 0.00B [00:00, ?B/s]

configuration_florence2.py: 0.00B [00:00, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/microsoft/Florence-2-base:
- configuration_florence2.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.

modeling_florence2.py: 0.00B [00:00, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/microsoft/Florence-2-base:
- modeling_florence2.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.

model.safetensors:   0%|          | 0.00/463M [00:00<?, ?B/s]

preprocessor_config.json:   0%|          | 0.00/806 [00:00<?, ?B/s]

processing_florence2.py: 0.00B [00:00, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/microsoft/Florence-2-base:
- processing_florence2.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.

tokenizer_config.json:   0%|          | 0.00/34.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

MIA seen:   0%|          | 0/200 [00:00<?, ?it/s]

MIA unseen:   0%|          | 0/200 [00:00<?, ?it/s]

COMET WARNING: log_asset_data(..., file_name=...) is deprecated; use log_asset_data(..., name=...)

Florence baseline: AUC_conf=0.572

The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

MIA seen:   0%|          | 0/200 [00:00<?, ?it/s]

MIA unseen:   0%|          | 0/200 [00:00<?, ?it/s]

COMET WARNING: log_asset_data(..., file_name=...) is deprecated; use log_asset_data(..., name=...)

Qwen-2B baseline: AUC_conf=0.500

COMET WARNING: log_asset_data(..., file_name=...) is deprecated; use log_asset_data(..., name=...)

,tag,auc_confidence,auc_loss,t_stat,p_value,mean_seen_conf,std_seen_conf,mean_unseen_conf,std_unseen_conf,mean_seen_loss,mean_unseen_loss,n_seen,n_unseen
0,florence2,0.572125,0.513950,0.483314,0.62914,-7.975506,25.394445,-9.239896,26.905443,4.564673,4.738034,200,200
1,qwen2b,0.500000,0.549225,NaN,NaN,0.000000,0.000000,0.000000,0.000000,1.915946,2.135218,200,200

COMET WARNING: Couldn't retrieve and log Google Colab notebook content, reason: 'NoneType' object is not subscriptable
COMET INFO: ---------------------------------------------------------------------------------------
COMET INFO: Comet.ml Experiment Summary
COMET INFO: ---------------------------------------------------------------------------------------
COMET INFO:   Data:
COMET INFO:     display_summary_level : 1
COMET INFO:     name                  : mia-baseline
COMET INFO:     url                   : https://www.comet.com/scfeel/qwen3-1/d0815f407194460b8cbd8eb20ecf6d1d
COMET INFO:   Metrics:
COMET INFO:     baseline_florence2_auc_confidence   : 0.572125
COMET INFO:     baseline_florence2_auc_loss         : 0.51395
COMET INFO:     baseline_florence2_mean_seen_conf   : -7.975505816406587
COMET INFO:     baseline_florence2_mean_seen_loss   : 4.564673495292664
COMET INFO:     baseline_florence2_mean_unseen_conf : -9.239896146535555
COMET INFO:     baseline_florence2_mean_unseen_loss : 4.738033968806267
COMET INFO:     baseline_florence2_p_value          : 0.6291395764260685
COMET INFO:     baseline_florence2_std_seen_conf    : 25.394445247727162
COMET INFO:     baseline_florence2_std_unseen_conf  : 26.90544305833262
COMET INFO:     baseline_florence2_t_stat           : 0.4833138322304656
COMET INFO:     baseline_qwen2b_auc_confidence      : 0.5
COMET INFO:     baseline_qwen2b_auc_loss            : 0.5492250000000001
COMET INFO:     baseline_qwen2b_mean_seen_conf      : 0.0
COMET INFO:     baseline_qwen2b_mean_seen_loss      : 1.9159458061732584
COMET INFO:     baseline_qwen2b_mean_unseen_conf    : 0.0
COMET INFO:     baseline_qwen2b_mean_unseen_loss    : 2.135217612396227
COMET INFO:     baseline_qwen2b_p_value             : nan
COMET INFO:     baseline_qwen2b_std_seen_conf       : 0.0
COMET INFO:     baseline_qwen2b_std_unseen_conf     : 0.0
COMET INFO:     baseline_qwen2b_t_stat              : nan
COMET INFO:   Others:
COMET INFO:     Name         : mia-baseline
COMET INFO:     notebook_url : https://colab.research.google.com/notebook#22_membership_inference-jvsc-1b7715c8-213e-468d-9144-247cb9560e390644c430-eb43-49ec-9868-5e851d7583d7.ipynb
COMET INFO:   Uploads:
COMET INFO:     asset                    : 6 (57.19 KB)
COMET INFO:     dataframe                : 1 (435 bytes)
COMET INFO:     environment details      : 1
COMET INFO:     filename                 : 1
COMET INFO:     git metadata             : 1
COMET INFO:     git-patch (uncompressed) : 1 (68.35 MB)
COMET INFO:     installed packages       : 1
COMET INFO:     notebook                 : 1
COMET INFO:     os packages              : 1
COMET INFO:     source_code              : 1
COMET INFO:
COMET WARNING: To get all data logged automatically, import comet_ml before the following modules: keras, torch, sklearn, tensorflow.

In [7]:
# Cell 6: Fine-tuned MIA
experiment = comet_ml.Experiment(api_key=os.environ["COMET_API_KEY"], workspace="scfeel", project_name="qwen3-1")
experiment.set_name("mia-finetuned")

bnb = BitsAndBytesConfig(load_in_4bit=True, bnb_4bit_compute_dtype=torch.bfloat16, bnb_4bit_quant_type="nf4")
finetuned_summary_rows = []

model = AutoModelForCausalLM.from_pretrained("checkpoints/florence2/epoch_30", trust_remote_code=True).to("cuda")
proc = AutoProcessor.from_pretrained("checkpoints/florence2/epoch_30", trust_remote_code=True)
df = run_mia(model, proc, florence_seen, unseen_200, "florence2")
m = compute_mia_metrics(df)
print(f"Florence ft: AUC_conf={m['auc_confidence']:.3f}, p={m['p_value']:.4f}")
save_csv_with_comet(df, MIA_DIR / "florence2_epoch30.csv", experiment)
fig = plot_histogram(df, "Florence-2 (эпоха 30)")
experiment.log_figure("florence2_hist", fig)
plt.close(fig)
experiment.log_metrics({f"florence2_epoch30_{k}": v for k, v in m.items()})
finetuned_summary_rows.append({"tag": "florence2", "checkpoint": "epoch_30", **m, "n_seen": len(florence_seen), "n_unseen": len(unseen_200)})
del model, proc
cleanup_gpu()

base = Qwen2VLForConditionalGeneration.from_pretrained("Qwen/Qwen2-VL-2B-Instruct", quantization_config=bnb, device_map="auto", trust_remote_code=True)
model = PeftModel.from_pretrained(base, "checkpoints/qwen2b/epoch_20")
model.eval()
proc = AutoProcessor.from_pretrained("Qwen/Qwen2-VL-2B-Instruct", trust_remote_code=True)
df = run_mia(model, proc, qwen_seen, unseen_200, "qwen")
m = compute_mia_metrics(df)
print(f"Qwen-2B ft: AUC_conf={m['auc_confidence']:.3f}, p={m['p_value']:.4f}")
save_csv_with_comet(df, MIA_DIR / "qwen2b_epoch20.csv", experiment)
fig = plot_histogram(df, "Qwen2-VL-2B (эпоха 20)")
experiment.log_figure("qwen2b_hist", fig)
plt.close(fig)
experiment.log_metrics({f"qwen2b_epoch20_{k}": v for k, v in m.items()})
finetuned_summary_rows.append({"tag": "qwen2b", "checkpoint": "epoch_20", **m, "n_seen": len(qwen_seen), "n_unseen": len(unseen_200)})
del model, base, proc
cleanup_gpu()

base = Qwen2VLForConditionalGeneration.from_pretrained("Qwen/Qwen2-VL-7B-Instruct", quantization_config=bnb, device_map="auto", trust_remote_code=True)
model = PeftModel.from_pretrained(base, "checkpoints/qwen7b/epoch_10")
model.eval()
proc = AutoProcessor.from_pretrained("Qwen/Qwen2-VL-7B-Instruct", trust_remote_code=True)
df = run_mia(model, proc, qwen_seen, unseen_200, "qwen")
m = compute_mia_metrics(df)
print(f"Qwen-7B ft: AUC_conf={m['auc_confidence']:.3f}, p={m['p_value']:.4f}")
save_csv_with_comet(df, MIA_DIR / "qwen7b_epoch10.csv", experiment)
fig = plot_histogram(df, "Qwen2-VL-7B (эпоха 10)")
experiment.log_figure("qwen7b_hist", fig)
plt.close(fig)
experiment.log_metrics({f"qwen7b_epoch10_{k}": v for k, v in m.items()})
finetuned_summary_rows.append({"tag": "qwen7b", "checkpoint": "epoch_10", **m, "n_seen": len(qwen_seen), "n_unseen": len(unseen_200)})
del model, base, proc
cleanup_gpu()

finetuned_summary_df = pd.DataFrame(finetuned_summary_rows)
save_csv_with_comet(finetuned_summary_df, MIA_DIR / "finetuned_mia_summary.csv", experiment, table_name="finetuned_mia_summary.csv")
display(finetuned_summary_df)

experiment.end()

COMET WARNING: To get all data logged automatically, import comet_ml before the following modules: keras, torch, sklearn, tensorflow.
COMET WARNING: As you are running in a Jupyter environment, you will need to call `experiment.end()` when finished to ensure all metrics and code are logged before exiting.
COMET INFO: Experiment is live on comet.com https://www.comet.com/scfeel/qwen3-1/28cea9a52925463b888599c4436e21be

MIA seen:   0%|          | 0/200 [00:00<?, ?it/s]

MIA unseen:   0%|          | 0/200 [00:00<?, ?it/s]

COMET WARNING: log_asset_data(..., file_name=...) is deprecated; use log_asset_data(..., name=...)

Florence ft: AUC_conf=0.578, p=0.0006

The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

MIA seen:   0%|          | 0/200 [00:00<?, ?it/s]

MIA unseen:   0%|          | 0/200 [00:00<?, ?it/s]

COMET WARNING: log_asset_data(..., file_name=...) is deprecated; use log_asset_data(..., name=...)

Qwen-2B ft: AUC_conf=0.500, p=nan

The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.

Loading checkpoint shards:   0%|          | 0/5 [00:00<?, ?it/s]

MIA seen:   0%|          | 0/200 [00:00<?, ?it/s]

MIA unseen:   0%|          | 0/200 [00:00<?, ?it/s]

COMET WARNING: log_asset_data(..., file_name=...) is deprecated; use log_asset_data(..., name=...)

Qwen-7B ft: AUC_conf=0.500, p=nan

COMET WARNING: log_asset_data(..., file_name=...) is deprecated; use log_asset_data(..., name=...)

,tag,checkpoint,auc_confidence,auc_loss,t_stat,p_value,mean_seen_conf,std_seen_conf,mean_unseen_conf,std_unseen_conf,mean_seen_loss,mean_unseen_loss,n_seen,n_unseen
0,florence2,epoch_30,0.577788,0.992000,3.443347,0.000642,-0.070749,0.9787,-0.481699,1.375079,0.019438,3.302556,200,200
1,qwen2b,epoch_20,0.500000,0.963775,NaN,NaN,0.000000,0.0000,0.000000,0.000000,0.013494,3.896309,200,200
2,qwen7b,epoch_10,0.500000,0.939875,NaN,NaN,0.000000,0.0000,0.000000,0.000000,0.057368,3.014876,200,200

COMET WARNING: Couldn't retrieve and log Google Colab notebook content, reason: 'NoneType' object is not subscriptable
COMET INFO: ---------------------------------------------------------------------------------------
COMET INFO: Comet.ml Experiment Summary
COMET INFO: ---------------------------------------------------------------------------------------
COMET INFO:   Data:
COMET INFO:     display_summary_level : 1
COMET INFO:     name                  : mia-finetuned
COMET INFO:     url                   : https://www.comet.com/scfeel/qwen3-1/28cea9a52925463b888599c4436e21be
COMET INFO:   Metrics:
COMET INFO:     florence2_epoch30_auc_confidence   : 0.5777875
COMET INFO:     florence2_epoch30_auc_loss         : 0.9920000000000001
COMET INFO:     florence2_epoch30_mean_seen_conf   : -0.07074863900478018
COMET INFO:     florence2_epoch30_mean_seen_loss   : 0.01943841519113107
COMET INFO:     florence2_epoch30_mean_unseen_conf : -0.48169850462055563
COMET INFO:     florence2_epoch30_mean_unseen_loss : 3.302556073197402
COMET INFO:     florence2_epoch30_p_value          : 0.0006423309011040259
COMET INFO:     florence2_epoch30_std_seen_conf    : 0.9787002732701636
COMET INFO:     florence2_epoch30_std_unseen_conf  : 1.3750785326683408
COMET INFO:     florence2_epoch30_t_stat           : 3.4433474637359582
COMET INFO:     qwen2b_epoch20_auc_confidence      : 0.5
COMET INFO:     qwen2b_epoch20_auc_loss            : 0.963775
COMET INFO:     qwen2b_epoch20_mean_seen_conf      : 0.0
COMET INFO:     qwen2b_epoch20_mean_seen_loss      : 0.013493511271351045
COMET INFO:     qwen2b_epoch20_mean_unseen_conf    : 0.0
COMET INFO:     qwen2b_epoch20_mean_unseen_loss    : 3.896308515931632
COMET INFO:     qwen2b_epoch20_p_value             : nan
COMET INFO:     qwen2b_epoch20_std_seen_conf       : 0.0
COMET INFO:     qwen2b_epoch20_std_unseen_conf     : 0.0
COMET INFO:     qwen2b_epoch20_t_stat              : nan
COMET INFO:     qwen7b_epoch10_auc_confidence      : 0.5
COMET INFO:     qwen7b_epoch10_auc_loss            : 0.939875
COMET INFO:     qwen7b_epoch10_mean_seen_conf      : 0.0
COMET INFO:     qwen7b_epoch10_mean_seen_loss      : 0.05736764483357078
COMET INFO:     qwen7b_epoch10_mean_unseen_conf    : 0.0
COMET INFO:     qwen7b_epoch10_mean_unseen_loss    : 3.0148758697882694
COMET INFO:     qwen7b_epoch10_p_value             : nan
COMET INFO:     qwen7b_epoch10_std_seen_conf       : 0.0
COMET INFO:     qwen7b_epoch10_std_unseen_conf     : 0.0
COMET INFO:     qwen7b_epoch10_t_stat              : nan
COMET INFO:   Others:
COMET INFO:     Name         : mia-finetuned
COMET INFO:     notebook_url : https://colab.research.google.com/notebook#22_membership_inference-jvsc-1b7715c8-213e-468d-9144-247cb9560e390644c430-eb43-49ec-9868-5e851d7583d7.ipynb
COMET INFO:   Uploads:
COMET INFO:     asset                    : 8 (87.10 KB)
COMET INFO:     dataframe                : 1 (574 bytes)
COMET INFO:     environment details      : 1
COMET INFO:     figures                  : 3
COMET INFO:     filename                 : 1
COMET INFO:     git metadata             : 1
COMET INFO:     git-patch (uncompressed) : 1 (68.35 MB)
COMET INFO:     installed packages       : 1
COMET INFO:     notebook                 : 1
COMET INFO:     os packages              : 1
COMET INFO:     source_code              : 1
COMET INFO:
COMET WARNING: To get all data logged automatically, import comet_ml before the following modules: keras, torch, sklearn, tensorflow.

In [8]:
# Cell 7: AUC by field type
summary_experiment = comet_ml.Experiment(api_key=os.environ["COMET_API_KEY"], workspace="scfeel", project_name="qwen3-1")
summary_experiment.set_name("mia-summary")

baseline_summary_df = pd.read_csv(MIA_DIR / "baseline_mia_summary.csv")
finetuned_summary_df = pd.read_csv(MIA_DIR / "finetuned_mia_summary.csv")
summary_experiment.log_table("baseline_mia_summary.csv", baseline_summary_df)
summary_experiment.log_table("finetuned_mia_summary.csv", finetuned_summary_df)

fine_tuned_files = {
    "florence2_epoch30": MIA_DIR / "florence2_epoch30.csv",
    "qwen2b_epoch20": MIA_DIR / "qwen2b_epoch20.csv",
    "qwen7b_epoch10": MIA_DIR / "qwen7b_epoch10.csv",
}
rows = []
for model_tag, csv_path in fine_tuned_files.items():
    df = pd.read_csv(csv_path)
    for field_type, group in df.groupby("field_type"):
        labels = (group["split"] == "seen").astype(int)
        if labels.nunique() < 2:
            continue
        rows.append({
            "model": model_tag,
            "field_type": field_type,
            "auc_confidence": roc_auc_score(labels, group["confidence"]),
            "auc_loss": roc_auc_score(labels, -group["loss"]),
            "n_examples": len(group),
        })
field_auc_df = pd.DataFrame(rows).sort_values(["model", "field_type"]).reset_index(drop=True)
save_csv_with_comet(field_auc_df, MIA_DIR / "field_type_auc.csv", summary_experiment, table_name="field_type_auc.csv")

fig, ax = plt.subplots(figsize=(10, 4))
heatmap_df = field_auc_df.pivot(index="model", columns="field_type", values="auc_confidence")
sns.heatmap(heatmap_df, annot=True, fmt=".3f", cmap="YlOrRd", ax=ax)
ax.set_title("MIA AUC-ROC по типам полей")
ax.set_xlabel("Тип поля")
ax.set_ylabel("Модель")
plt.tight_layout()
summary_experiment.log_figure("field_type_auc_heatmap", fig)
plt.close(fig)

mia_bar_rows = []
for _, row in baseline_summary_df.iterrows():
    mia_bar_rows.append({"tag": row["tag"], "stage": "baseline", "auc_confidence": row["auc_confidence"], "auc_loss": row["auc_loss"]})
for _, row in finetuned_summary_df.iterrows():
    mia_bar_rows.append({"tag": row["tag"], "stage": "fine-tuned", "auc_confidence": row["auc_confidence"], "auc_loss": row["auc_loss"]})
mia_bar_df = pd.DataFrame(mia_bar_rows)
save_csv_with_comet(mia_bar_df, MIA_DIR / "mia_auc_bar_summary.csv", summary_experiment, table_name="mia_auc_bar_summary.csv")

plot_df = mia_bar_df.melt(id_vars=["tag", "stage"], value_vars=["auc_confidence", "auc_loss"], var_name="metric", value_name="auc")
fig, axes = plt.subplots(1, 2, figsize=(12, 4), sharey=True)
for ax, metric in zip(axes, ["auc_confidence", "auc_loss"]):
    metric_df = plot_df[plot_df["metric"] == metric]
    sns.barplot(data=metric_df, x="tag", y="auc", hue="stage", ax=ax, palette="Set2")
    ax.set_title("AUC-ROC по " + ("confidence" if metric == "auc_confidence" else "loss"))
    ax.set_xlabel("Модель")
    ax.set_ylabel("AUC-ROC")
    ax.axhline(0.5, linestyle="--", color="gray", linewidth=1)
plt.tight_layout()
summary_experiment.log_figure("mia_auc_bar_baseline_vs_finetuned", fig)
plt.close(fig)

display(field_auc_df)
display(mia_bar_df)
summary_experiment.end()

COMET WARNING: To get all data logged automatically, import comet_ml before the following modules: keras, torch, sklearn, tensorflow.
COMET WARNING: As you are running in a Jupyter environment, you will need to call `experiment.end()` when finished to ensure all metrics and code are logged before exiting.
COMET INFO: Experiment is live on comet.com https://www.comet.com/scfeel/qwen3-1/0f2390211910462f8c758e2897e02390

COMET WARNING: log_asset_data(..., file_name=...) is deprecated; use log_asset_data(..., name=...)
COMET WARNING: log_asset_data(..., file_name=...) is deprecated; use log_asset_data(..., name=...)

                model   field_type  auc_confidence  auc_loss  n_examples
0   florence2_epoch30       AMOUNT        0.655510  0.993469          70
1   florence2_epoch30  CONTACT_ADR        0.552342  1.000000          66
2   florence2_epoch30         DATE        0.704316  1.000000          66
3   florence2_epoch30           ID        0.678145  0.980716          66
4   florence2_epoch30          ORG        0.492195  0.977961          66
5   florence2_epoch30       PERSON        0.415978  1.000000          66
6      qwen2b_epoch20       AMOUNT        0.500000  0.946939          70
7      qwen2b_epoch20  CONTACT_ADR        0.500000  0.976125          66
8      qwen2b_epoch20         DATE        0.500000  0.963269          66
9      qwen2b_epoch20           ID        0.500000  0.957759          66
10     qwen2b_epoch20          ORG        0.500000  0.983471          66
11     qwen2b_epoch20       PERSON        0.500000  0.965106          66
12     qwen7b_epoch10       AMOUNT        0.500000  0.896327          70
13     qwen7b_epoch10  CONTACT_ADR        0.500000  0.964187          66
14     qwen7b_epoch10         DATE        0.500000  0.914601          66
15     qwen7b_epoch10           ID        0.500000  0.943067          66
16     qwen7b_epoch10          ORG        0.500000  0.991736          66
17     qwen7b_epoch10       PERSON        0.500000  0.964187          66

         tag       stage  auc_confidence  auc_loss
0  florence2    baseline        0.572125  0.513950
1     qwen2b    baseline        0.500000  0.549225
2  florence2  fine-tuned        0.577788  0.992000
3     qwen2b  fine-tuned        0.500000  0.963775
4     qwen7b  fine-tuned        0.500000  0.939875

COMET INFO: The process of logging environment details (conda environment, git patch) is underway. Please be patient as this may take some time.
COMET WARNING: Couldn't retrieve and log Google Colab notebook content, reason: 'NoneType' object is not subscriptable
COMET INFO: ---------------------------------------------------------------------------------------
COMET INFO: Comet.ml Experiment Summary
COMET INFO: ---------------------------------------------------------------------------------------
COMET INFO:   Data:
COMET INFO:     display_summary_level : 1
COMET INFO:     name                  : mia-summary
COMET INFO:     url                   : https://www.comet.com/scfeel/qwen3-1/0f2390211910462f8c758e2897e02390
COMET INFO:   Others:
COMET INFO:     Name         : mia-summary
COMET INFO:     notebook_url : https://colab.research.google.com/notebook#22_membership_inference-jvsc-1b7715c8-213e-468d-9144-247cb9560e390644c430-eb43-49ec-9868-5e851d7583d7.ipynb
COMET INFO:   Uploads:
COMET INFO:     asset                    : 4 (1.15 KB)
COMET INFO:     dataframe                : 4 (2.16 KB)
COMET INFO:     environment details      : 1
COMET INFO:     figures                  : 2
COMET INFO:     filename                 : 1
COMET INFO:     git metadata             : 1
COMET INFO:     git-patch (uncompressed) : 1 (68.35 MB)
COMET INFO:     installed packages       : 1
COMET INFO:     notebook                 : 1
COMET INFO:     os packages              : 1
COMET INFO:     source_code              : 1
COMET INFO:
COMET WARNING: To get all data logged automatically, import comet_ml before the following modules: keras, torch, sklearn, tensorflow.

In [9]:
# Cell 8: Saved outputs
saved_csvs = sorted(str(path) for path in MIA_DIR.glob("*.csv"))
display(pd.DataFrame({"csv_path": saved_csvs}))
print({"csv_count": len(saved_csvs), "output_dir": str(MIA_DIR)})

                                            csv_path
0  /content/drive/MyDrive/course_work2026/artifac...
1  /content/drive/MyDrive/course_work2026/artifac...
2  /content/drive/MyDrive/course_work2026/artifac...
3  /content/drive/MyDrive/course_work2026/artifac...
4  /content/drive/MyDrive/course_work2026/artifac...
5  /content/drive/MyDrive/course_work2026/artifac...
6  /content/drive/MyDrive/course_work2026/artifac...
7  /content/drive/MyDrive/course_work2026/artifac...
8  /content/drive/MyDrive/course_work2026/artifac...

{'csv_count': 9, 'output_dir': '/content/drive/MyDrive/course_work2026/artifacts/privacy_attacks/mia'}