In [ ]:
# Secrets
import os

In [2]:
# Setup
!git clone https://github.com/sk3feel/hidden-data-reproduction-multimodal.git /content/course_work2026 2>/dev/null || (cd /content/course_work2026 && git pull)
%cd /content/course_work2026
from google.colab import drive
from pathlib import Path
drive.mount("/content/drive")
DRIVE_ROOT = Path("/content/drive/MyDrive/course_work2026")
DRIVE_ROOT.mkdir(parents=True, exist_ok=True)
print({"drive_root": str(DRIVE_ROOT)})
import sys
print({"python_executable": sys.executable})
!pip install -q -r requirements.txt
!pip install -q accelerate Pillow pandas tqdm einops timm comet_ml huggingface_hub
!pip install -q peft bitsandbytes trl qwen-vl-utils
!pip uninstall -y transformers tokenizers
!pip install -q tokenizers==0.21.0
!pip install -q transformers==4.49.0 --force-reinstall --no-deps
!python src/download_from_hf.py --repo-id sk3feel/docvqa-privacy-data

from huggingface_hub import snapshot_download
snapshot_download("sk3feel/docvqa-privacy-checkpoints", local_dir="checkpoints/", repo_type="model", token=os.environ["HF_TOKEN"])

Mounted at /content/drive
{'drive_root': '/content/drive/MyDrive/course_work2026'}
{'python_executable': '/usr/bin/python3'}
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.6/14.6 MB 141.6 MB/s eta 0:00:0000:010:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.3/42.3 kB 4.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 786.2/786.2 kB 61.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 74.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.4/12.4 MB 151.4 MB/s eta 0:00:0000:010:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.8/59.8 kB 6.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.7/76.7 kB 8.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 80.4 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
jupyter-kernel-gateway 2.5.2 requires notebook<7.0,>=5.7.6, but you have notebook 7.5.5 which is incompatible.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 43.8 MB/s eta 0:00:00:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 531.0/531.0 kB 43.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 36.4/36.4 MB 70.9 MB/s eta 0:00:00:00:0100:01
Found existing installation: transformers 5.0.0
Uninstalling transformers-5.0.0:
  Successfully uninstalled transformers-5.0.0
Found existing installation: tokenizers 0.22.2
Uninstalling tokenizers-0.22.2:
  Successfully uninstalled tokenizers-0.22.2
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 104.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 45.6 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
sentence-transformers 5.3.0 requires transformers<6.0.0,>=4.41.0, which is not installed.
peft 0.18.1 requires transformers, which is not installed.
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 3.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 157.6 MB/s eta 0:00:0000:01
artifacts_bundle.tar.gz: 100% 3.04G/3.04G [00:16<00:00, 181MB/s]
/content/course_work2026/src/download_from_hf.py:29: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=extract_root)
{
  "repo_id": "sk3feel/docvqa-privacy-data",
  "local_dir": "/content/course_work2026/artifacts",
  "archive_filename": "artifacts_bundle.tar.gz",
  "extracted_paths": {
    "benchmark_train": "/content/course_work2026/artifacts/docqa_recovery/benchmark_train",
    "benchmark": "/content/course_work2026/artifacts/docqa_recovery/benchmark",
    "finetuning_generative": "/content/course_work2026/artifacts/finetuning_generative"
  }
}

Fetching 149 files:   0%|          | 0/149 [00:00<?, ?it/s]

.gitattributes: 0.00B [00:00, ?B/s]

processor_config.json: 0.00B [00:00, ?B/s]

generation_config.json:   0%|          | 0.00/292 [00:00<?, ?B/s]

preprocessor_config.json:   0%|          | 0.00/630 [00:00<?, ?B/s]

florence2/epoch_1/model.safetensors:   0%|          | 0.00/926M [00:00<?, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

added_tokens.json: 0.00B [00:00, ?B/s]

config.json: 0.00B [00:00, ?B/s]

florence2/epoch_1/trainer_state.pt:   0%|          | 0.00/1.08G [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

added_tokens.json: 0.00B [00:00, ?B/s]

config.json: 0.00B [00:00, ?B/s]

generation_config.json:   0%|          | 0.00/292 [00:00<?, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

florence2/epoch_15/model.safetensors:   0%|          | 0.00/926M [00:00<?, ?B/s]

preprocessor_config.json:   0%|          | 0.00/630 [00:00<?, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

generation_config.json:   0%|          | 0.00/291 [00:00<?, ?B/s]

florence2/epoch_3/model.safetensors:   0%|          | 0.00/542M [00:00<?, ?B/s]

processor_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

florence2/epoch_3/trainer_state.pt:   0%|          | 0.00/1.08G [00:00<?, ?B/s]

added_tokens.json: 0.00B [00:00, ?B/s]

config.json: 0.00B [00:00, ?B/s]

generation_config.json:   0%|          | 0.00/292 [00:00<?, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

florence2/epoch_30/model.safetensors:   0%|          | 0.00/926M [00:00<?, ?B/s]

preprocessor_config.json:   0%|          | 0.00/630 [00:00<?, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

added_tokens.json: 0.00B [00:00, ?B/s]

config.json: 0.00B [00:00, ?B/s]

generation_config.json:   0%|          | 0.00/292 [00:00<?, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

florence2/epoch_5/model.safetensors:   0%|          | 0.00/926M [00:00<?, ?B/s]

preprocessor_config.json:   0%|          | 0.00/630 [00:00<?, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

README.md: 0.00B [00:00, ?B/s]

adapter_config.json:   0%|          | 0.00/979 [00:00<?, ?B/s]

qwen2b/epoch_1/adapter_model.safetensors:   0%|          | 0.00/8.73M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/392 [00:00<?, ?B/s]

chat_template.jinja: 0.00B [00:00, ?B/s]

chat_template.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

preprocessor_config.json:   0%|          | 0.00/572 [00:00<?, ?B/s]

processor_config.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/613 [00:00<?, ?B/s]

qwen2b/epoch_1/tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

README.md: 0.00B [00:00, ?B/s]

adapter_config.json:   0%|          | 0.00/979 [00:00<?, ?B/s]

qwen2b/epoch_10/adapter_model.safetensor(…):   0%|          | 0.00/8.73M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/392 [00:00<?, ?B/s]

chat_template.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

preprocessor_config.json:   0%|          | 0.00/572 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/613 [00:00<?, ?B/s]

qwen2b/epoch_10/tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

README.md: 0.00B [00:00, ?B/s]

adapter_config.json:   0%|          | 0.00/979 [00:00<?, ?B/s]

qwen2b/epoch_20/adapter_model.safetensor(…):   0%|          | 0.00/8.73M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/392 [00:00<?, ?B/s]

chat_template.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

preprocessor_config.json:   0%|          | 0.00/572 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/613 [00:00<?, ?B/s]

qwen2b/epoch_20/tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

README.md: 0.00B [00:00, ?B/s]

adapter_config.json:   0%|          | 0.00/979 [00:00<?, ?B/s]

qwen2b/epoch_3/adapter_model.safetensors:   0%|          | 0.00/8.73M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/392 [00:00<?, ?B/s]

chat_template.jinja: 0.00B [00:00, ?B/s]

chat_template.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

preprocessor_config.json:   0%|          | 0.00/572 [00:00<?, ?B/s]

processor_config.json: 0.00B [00:00, ?B/s]

qwen2b/epoch_3/tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/613 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

README.md: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

adapter_config.json:   0%|          | 0.00/979 [00:00<?, ?B/s]

qwen2b/epoch_5/adapter_model.safetensors:   0%|          | 0.00/8.73M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/392 [00:00<?, ?B/s]

chat_template.jinja: 0.00B [00:00, ?B/s]

chat_template.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

preprocessor_config.json:   0%|          | 0.00/572 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/613 [00:00<?, ?B/s]

processor_config.json: 0.00B [00:00, ?B/s]

qwen2b/epoch_5/tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

adapter_config.json:   0%|          | 0.00/979 [00:00<?, ?B/s]

qwen7b/epoch_10/adapter_model.safetensor(…):   0%|          | 0.00/20.2M [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/392 [00:00<?, ?B/s]

chat_template.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

preprocessor_config.json:   0%|          | 0.00/572 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/613 [00:00<?, ?B/s]

qwen7b/epoch_10/tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

adapter_config.json:   0%|          | 0.00/979 [00:00<?, ?B/s]

qwen7b/epoch_2/adapter_model.safetensors:   0%|          | 0.00/20.2M [00:00<?, ?B/s]

chat_template.jinja: 0.00B [00:00, ?B/s]

processor_config.json: 0.00B [00:00, ?B/s]

qwen7b/epoch_2/tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/731 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

adapter_config.json:   0%|          | 0.00/979 [00:00<?, ?B/s]

qwen7b/epoch_3/adapter_model.safetensors:   0%|          | 0.00/20.2M [00:00<?, ?B/s]

chat_template.jinja: 0.00B [00:00, ?B/s]

processor_config.json: 0.00B [00:00, ?B/s]

qwen7b/epoch_3/tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/731 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

adapter_config.json:   0%|          | 0.00/979 [00:00<?, ?B/s]

qwen7b/epoch_5/adapter_model.safetensors:   0%|          | 0.00/20.2M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/392 [00:00<?, ?B/s]

chat_template.jinja: 0.00B [00:00, ?B/s]

chat_template.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

preprocessor_config.json:   0%|          | 0.00/572 [00:00<?, ?B/s]

processor_config.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/613 [00:00<?, ?B/s]

qwen7b/epoch_5/tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

'/content/course_work2026/checkpoints'

In [3]:
# Utilities and config
import gc, json, os, re, sys, torch, pandas as pd
from pathlib import Path
from collections import defaultdict
from PIL import Image, ImageFile
from transformers import AutoModelForCausalLM, AutoProcessor, Qwen2VLForConditionalGeneration, BitsAndBytesConfig
from peft import PeftModel
from tqdm.auto import tqdm
from qwen_vl_utils import process_vision_info
import comet_ml
import matplotlib.pyplot as plt
import seaborn as sns


sys.path.append(str(Path.cwd() / "src"))

from src.docqa_metrics import best_metric_over_answers, build_answer_pool, estimate_random_baseline
from src.inference_scenarios import generate_scenario_image, generate_scenario_ocr

import transformers
print(f"transformers version: {transformers.__version__}")
if not transformers.__version__.startswith("4.4"):
    print(f"WARNING: expected 4.4x.x, got {transformers.__version__}. Florence-2 may fail.")

ImageFile.LOAD_TRUNCATED_IMAGES = True
MAX_IMAGE_SIDE = 1024
LOCAL_ARTIFACTS_ROOT = Path("artifacts")
DRIVE_ARTIFACTS_ROOT = DRIVE_ROOT / "artifacts"
DRIVE_ARTIFACTS_ROOT.mkdir(parents=True, exist_ok=True)
FINETUNING_DIR = DRIVE_ARTIFACTS_ROOT / "finetuning_generative"
FINETUNING_DIR.mkdir(parents=True, exist_ok=True)
EXTRACTION_DIR = DRIVE_ARTIFACTS_ROOT / "privacy_attacks" / "extraction"
EXTRACTION_DIR.mkdir(parents=True, exist_ok=True)
SUCCESS_PREVIEW_DIR = EXTRACTION_DIR / "success_previews"
SUCCESS_PREVIEW_DIR.mkdir(parents=True, exist_ok=True)

FLORENCE_SCENARIOS = ["original", "img_black", "img_blur_20", "img_blur_50"]
QWEN_IMAGE_ONLY_SCENARIOS = ["original", "img_black", "img_blur_20", "img_blur_50"]
QWEN_IMAGE_OCR_SCENARIOS = ["img_black__ocr_mask__k_0", "img_none__ocr_mask__k_0"]
QWEN_OCR_SCENARIO_MAP = {
    "img_black__ocr_mask__k_0": "ocr_mask__img_black__k_0",
    "img_none__ocr_mask__k_0": "ocr_mask__img_none__k_0",
}


def save_csv_with_comet(df, path, experiment, table_name=None):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(path, index=False)
    csv_string = df.to_csv(index=False)
    experiment.log_asset(str(path), file_name=path.name)
    experiment.log_asset_data(csv_string, file_name=path.name)
    if table_name is not None:
        experiment.log_table(table_name, df)
    return path


def safe_open_image(path, max_side=MAX_IMAGE_SIDE):
    image = Image.open(path).convert("RGB")
    if max(image.size) > max_side:
        image.thumbnail((max_side, max_side), Image.LANCZOS)
    return image


def resize_generated_image(image, max_side=MAX_IMAGE_SIDE):
    image = image.convert("RGB")
    if max(image.size) > max_side:
        image.thumbnail((max_side, max_side), Image.LANCZOS)
    return image


def load_jsonl(path):
    rows = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            if line.strip():
                rows.append(json.loads(line))
    return rows


def enrich_with_field_types(records, manifest_path):
    manifest = []
    with open(manifest_path, "r", encoding="utf-8") as f:
        for line in f:
            if line.strip():
                manifest.append(json.loads(line))
    type_map = {}
    for row in manifest:
        eid = str(row.get("example_id", row.get("question_id", "")))
        type_map[eid] = row.get("coarse_field_type", "OTHER")
    for rec in records:
        rec["coarse_field_type"] = type_map.get(rec["example_id"], "OTHER")
    return records


def stratified_sample(records, n, type_key="coarse_field_type"):
    by_type = defaultdict(list)
    for rec in records:
        by_type[rec[type_key]].append(rec)
    types = sorted(by_type.keys())
    per_type = n // len(types)
    result = []
    for ft in types:
        result.extend(by_type[ft][:per_type])
    used = {r["example_id"] for r in result}
    for rec in records:
        if len(result) >= n:
            break
        if rec["example_id"] not in used:
            result.append(rec)
    return result[:n]


def normalize_text(text):
    text = str(text or "")
    text = re.sub(r"<[^>]+>", " ", text)
    text = " ".join(text.replace("\n", " ").split()).strip()
    return text


def normalize_em(text):
    text = str(text or "").lower().strip()
    text = re.sub(r"[^\w\s]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text


def qwen_user_text(question, ocr_text=None):
    if ocr_text is None:
        return f"Answer the question about this document image. Give only the answer value, nothing else.\nQuestion: {question}"
    return (
        "Answer the question about this document image using the OCR text provided. "
        "Give only the answer value, nothing else.\n"
        f"OCR: {ocr_text}\nQuestion: {question}"
    )


def load_florence(checkpoint_path=None):
    model_name = str(checkpoint_path) if checkpoint_path is not None else "microsoft/Florence-2-base"
    model = AutoModelForCausalLM.from_pretrained(model_name, trust_remote_code=True).to("cuda")
    model.eval()
    processor = AutoProcessor.from_pretrained(model_name, trust_remote_code=True)
    return model, processor


def load_qwen(base_model_name, adapter_path=None):
    bnb = BitsAndBytesConfig(load_in_4bit=True, bnb_4bit_compute_dtype=torch.bfloat16, bnb_4bit_quant_type="nf4")
    base = Qwen2VLForConditionalGeneration.from_pretrained(base_model_name, quantization_config=bnb, device_map="auto", trust_remote_code=True)
    if adapter_path is not None:
        model = PeftModel.from_pretrained(base, str(adapter_path))
    else:
        model = base
    model.eval()
    processor = AutoProcessor.from_pretrained(base_model_name, trust_remote_code=True)
    return model, processor


def generate_prediction_florence(model, processor, image, question):
    inputs = processor(text=f"<VQA>{question}", images=image, return_tensors="pt").to(model.device)
    generate_inputs = {"input_ids": inputs["input_ids"], "pixel_values": inputs["pixel_values"]}
    with torch.no_grad():
        gen = model.generate(**generate_inputs, max_new_tokens=50)
    return normalize_text(processor.batch_decode(gen, skip_special_tokens=True)[0])


def generate_prediction_qwen(model, processor, image, question, ocr_text=None):
    messages = [{"role": "user", "content": [
        {"type": "image", "image": image},
        {"type": "text", "text": qwen_user_text(question, ocr_text=ocr_text)},
    ]}]
    text = processor.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    img_inputs, _ = process_vision_info(messages)
    img_input = img_inputs[0] if isinstance(img_inputs, list) else img_inputs
    inputs = processor(text=[text], images=[img_input], return_tensors="pt", padding=True)
    device = next(model.parameters()).device
    inputs = {k: v.to(device) if isinstance(v, torch.Tensor) else v for k, v in inputs.items()}
    with torch.no_grad():
        gen = model.generate(**inputs, max_new_tokens=50)
    pred = processor.batch_decode(gen[:, inputs["input_ids"].shape[1]:], skip_special_tokens=True)[0].strip()
    return normalize_text(pred)


def run_extraction(model, processor, records, scenarios, model_kind, mode):
    rows = []
    for rec in tqdm(records, desc=f"extraction:{model_kind}:{mode}"):
        for scenario in scenarios:
            internal_scenario = QWEN_OCR_SCENARIO_MAP.get(scenario, scenario)
            image = resize_generated_image(generate_scenario_image(rec, internal_scenario))
            ocr_text = generate_scenario_ocr(rec, internal_scenario) if mode == "image_ocr" else None

            if model_kind == "florence":
                prediction = generate_prediction_florence(model, processor, image, rec["question"])
            else:
                prediction = generate_prediction_qwen(model, processor, image, rec["question"], ocr_text=ocr_text)

            rows.append({
                "example_id": rec["example_id"],
                "split": rec["split"],
                "scenario": scenario,
                "prediction": prediction,
                "question": rec["question"],
                "answer": rec["answer"],
                "answers": list(rec.get("answers") or [rec["answer"]]),
                "coarse_type": rec["coarse_field_type"],
                "ocr_text_used": ocr_text or "",
                "ocr_source": "generate_scenario_ocr" if mode == "image_ocr" else "",
            })
    return pd.DataFrame(rows)


def score_predictions(predictions_df, answer_pools):
    rows = []
    for row in predictions_df.to_dict(orient="records"):
        answers = row["answers"]
        random_record = {
            "example_id": row["example_id"],
            "coarse_field_type": row["coarse_type"],
            "answers": answers,
            "answer": row["answer"],
            "local_row_id": 0,
        }
        exact_match, token_f1 = best_metric_over_answers(row["prediction"], answers)
        random_em, random_f1 = estimate_random_baseline(random_record, answer_pools[row["split"]])
        rows.append({
            **row,
            "exact_match": exact_match,
            "token_f1": token_f1,
            "random_em": random_em,
            "random_f1": random_f1,
            "corrected_em": exact_match - random_em,
            "corrected_f1": token_f1 - random_f1,
            "normalized_prediction": normalize_em(row["prediction"]),
            "normalized_answer": normalize_em(row["answer"]),
        })
    return pd.DataFrame(rows)


def compute_metrics(scored_df):
    rows = []
    for (split, scenario, coarse_type), group in scored_df.groupby(["split", "scenario", "coarse_type"]):
        rows.append({
            "split": split,
            "scenario": scenario,
            "coarse_type": coarse_type,
            "n_examples": len(group),
            "exact_match": float(group["exact_match"].mean()),
            "token_f1": float(group["token_f1"].mean()),
            "random_em": float(group["random_em"].mean()),
            "random_f1": float(group["random_f1"].mean()),
            "corrected_em": float(group["corrected_em"].mean()),
            "corrected_f1": float(group["corrected_f1"].mean()),
        })
    overall_rows = []
    for (split, scenario), group in scored_df.groupby(["split", "scenario"]):
        overall_rows.append({
            "split": split,
            "scenario": scenario,
            "coarse_type": "ALL",
            "n_examples": len(group),
            "exact_match": float(group["exact_match"].mean()),
            "token_f1": float(group["token_f1"].mean()),
            "random_em": float(group["random_em"].mean()),
            "random_f1": float(group["random_f1"].mean()),
            "corrected_em": float(group["corrected_em"].mean()),
            "corrected_f1": float(group["corrected_f1"].mean()),
        })
    return pd.DataFrame(rows + overall_rows).sort_values(["split", "scenario", "coarse_type"]).reset_index(drop=True)


def run_model_extraction_experiment(model, processor, model_tag, model_kind, mode, scenarios, seen_records, unseen_records, answer_pools, experiment_name):
    experiment = comet_ml.Experiment(api_key=os.environ["COMET_API_KEY"], workspace="scfeel", project_name="qwen3-1")
    experiment.set_name(experiment_name)
    experiment.log_parameters({
        "model_tag": model_tag,
        "mode": mode,
        "scenarios": scenarios,
        "n_seen": len(seen_records),
        "n_unseen": len(unseen_records),
    })

    combined_records = seen_records + unseen_records
    record_lookup = {(str(rec["example_id"]), rec["split"]): rec for rec in combined_records}
    predictions_df = run_extraction(model, processor, combined_records, scenarios, model_kind=model_kind, mode=mode)
    scored_df = score_predictions(predictions_df, answer_pools)
    metrics_df = compute_metrics(scored_df)
    success_df = scored_df[(scored_df["split"] == "seen") & (scored_df["scenario"] != "original") & (scored_df["exact_match"] >= 1.0)].head(20).copy()

    prefix = f"{model_tag}_{mode}"
    predictions_path = EXTRACTION_DIR / f"{prefix}_predictions.csv"
    scored_path = EXTRACTION_DIR / f"{prefix}_scored.csv"
    metrics_path = EXTRACTION_DIR / f"{prefix}_metrics.csv"
    success_path = EXTRACTION_DIR / f"{prefix}_successful_examples.csv"
    save_csv_with_comet(predictions_df, predictions_path, experiment)
    save_csv_with_comet(scored_df, scored_path, experiment)
    save_csv_with_comet(metrics_df, metrics_path, experiment, table_name=metrics_path.name)
    save_csv_with_comet(success_df, success_path, experiment, table_name=success_path.name)

    for _, row in metrics_df[metrics_df["coarse_type"] == "ALL"].iterrows():
        metric_name = f"{row['split']}_{row['scenario']}_corrected_em".replace("+", "__").replace("-", "_")
        experiment.log_metric(metric_name, float(row["corrected_em"]))

    if not success_df.empty:
        preview_dir = SUCCESS_PREVIEW_DIR / prefix
        preview_dir.mkdir(parents=True, exist_ok=True)
        for idx, row in success_df.head(5).reset_index(drop=True).iterrows():
            record = record_lookup.get((str(row["example_id"]), row["split"]))
            if record is None:
                continue
            internal_scenario = QWEN_OCR_SCENARIO_MAP.get(row["scenario"], row["scenario"])
            preview_image = resize_generated_image(generate_scenario_image(record, internal_scenario))
            preview_path = preview_dir / f"{idx}_{row['example_id']}_{row['scenario']}.png"
            preview_image.save(preview_path)
            experiment.log_image(str(preview_path), name=preview_path.name)

    experiment.end()
    return predictions_df, scored_df, metrics_df, success_df


def cleanup_gpu():
    gc.collect()
    torch.cuda.empty_cache()

transformers version: 4.49.0

In [4]:
# Data preparation
local_qwen_train_ids_path = Path("artifacts/finetuning_generative/qwen_train_200_ids.csv")
qwen_train_ids_path = FINETUNING_DIR / "qwen_train_200_ids.csv"


def extract_question_from_row(row):
    if row.get("question"):
        return str(row["question"]).strip()
    chat = row.get("chat_messages") or []
    if chat:
        for item in chat[0].get("content", []):
            if item.get("type") == "text":
                match = re.search(r"Question:\s*(.*)", item["text"], re.IGNORECASE | re.DOTALL)
                return match.group(1).strip() if match else item["text"].strip()
    return str(row.get("prompt", "")).strip()


train_manifest = load_jsonl("artifacts/docqa_recovery/benchmark_train/manifest.jsonl")
validation_manifest = load_jsonl("artifacts/docqa_recovery/benchmark/manifest.jsonl")
train_manifest_map = {str(r.get("example_id", r.get("question_id", ""))): r for r in train_manifest}


def get_qwen_train_ids():
    if qwen_train_ids_path.exists():
        return pd.read_csv(qwen_train_ids_path)["example_id"].astype(str).tolist()

    if local_qwen_train_ids_path.exists():
        qwen_ids = pd.read_csv(local_qwen_train_ids_path)["example_id"].astype(str).tolist()
        pd.DataFrame({"example_id": qwen_ids}).to_csv(qwen_train_ids_path, index=False)
        return qwen_ids

    print("qwen_train_200_ids.csv not found; reconstructing from train_qwen2vl.jsonl")
    train_qwen_rows = load_jsonl("artifacts/finetuning_generative/train_qwen2vl.jsonl")
    manifest_qna_map = {}
    for row in train_manifest:
        eid = str(row.get("example_id", row.get("question_id", "")))
        answers = row.get("answers") or [row.get("answer", "")]
        answer_value = answers[0] if isinstance(answers, list) and answers else row.get("answer", "")
        manifest_qna_map[(str(row.get("question", "")).strip(), str(answer_value).strip())] = eid

    candidate_records = []
    for row in train_qwen_rows:
        eid = str(row.get("example_id", "")).strip()
        if not eid:
            q = extract_question_from_row(row)
            a = str(row.get("answer", "")).strip()
            eid = manifest_qna_map.get((q, a), "")
        if not eid or eid not in train_manifest_map:
            continue
        candidate_records.append({
            "example_id": eid,
            "coarse_field_type": train_manifest_map[eid].get("coarse_field_type", "OTHER"),
        })

    qwen_ids = [r["example_id"] for r in stratified_sample(candidate_records, 200)]
    pd.DataFrame({"example_id": qwen_ids}).to_csv(qwen_train_ids_path, index=False)
    return qwen_ids


qwen_train_ids = get_qwen_train_ids()


def manifest_to_record(row, split, image_root):
    image_name = str(row.get("image_path", "")).replace("\\", "/").split("/")[-1]
    answer_value = row["answers"][0] if isinstance(row.get("answers"), list) and row.get("answers") else row.get("answer", "")
    record = dict(row)
    record["example_id"] = str(row.get("example_id", row.get("question_id", "")))
    record["split"] = split
    record["image_path"] = str(Path(image_root) / image_name)
    record["answer"] = answer_value
    record["coarse_field_type"] = row.get("coarse_field_type", "OTHER")
    return record


train_records_full = [
    manifest_to_record(r, "seen", "artifacts/docqa_recovery/benchmark_train/images/original")
    for r in train_manifest
]
validation_records_full = [
    manifest_to_record(r, "unseen", "artifacts/docqa_recovery/benchmark/images/original")
    for r in validation_manifest
]

qwen_seen = [r for r in train_records_full if r["example_id"] in set(qwen_train_ids)]
florence_seen = stratified_sample(train_records_full, 200)
unseen_200 = stratified_sample(validation_records_full, 200)

florence_answer_pools = {
    "seen": build_answer_pool(florence_seen),
    "unseen": build_answer_pool(unseen_200),
}
qwen_answer_pools = {
    "seen": build_answer_pool(qwen_seen),
    "unseen": build_answer_pool(unseen_200),
}

print({
    "florence_seen": len(florence_seen),
    "qwen_seen": len(qwen_seen),
    "unseen_200": len(unseen_200),
})

{'florence_seen': 200, 'qwen_seen': 200, 'unseen_200': 200}

In [5]:
# Baseline Florence extraction
model, processor = load_florence()
baseline_outputs = run_model_extraction_experiment(
    model=model,
    processor=processor,
    model_tag="baseline_florence2",
    model_kind="florence",
    mode="image_only",
    scenarios=FLORENCE_SCENARIOS,
    seen_records=florence_seen,
    unseen_records=unseen_200,
    answer_pools=florence_answer_pools,
    experiment_name="extraction-baseline-florence2",
)
display(baseline_outputs[2])
del model, processor
cleanup_gpu()

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:104: UserWarning:
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
You are not authenticated with the Hugging Face Hub in this notebook.
If the error persists, please let us know by opening an issue on GitHub (https://github.com/huggingface/huggingface_hub/issues/new).
  warnings.warn(

config.json: 0.00B [00:00, ?B/s]

configuration_florence2.py: 0.00B [00:00, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/microsoft/Florence-2-base:
- configuration_florence2.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.

modeling_florence2.py: 0.00B [00:00, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/microsoft/Florence-2-base:
- modeling_florence2.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.

model.safetensors:   0%|          | 0.00/463M [00:00<?, ?B/s]

preprocessor_config.json:   0%|          | 0.00/806 [00:00<?, ?B/s]

processing_florence2.py: 0.00B [00:00, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/microsoft/Florence-2-base:
- processing_florence2.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.

tokenizer_config.json:   0%|          | 0.00/34.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

COMET WARNING: To get all data logged automatically, import comet_ml before the following modules: torch, tensorflow, sklearn, keras.
COMET WARNING: As you are running in a Jupyter environment, you will need to call `experiment.end()` when finished to ensure all metrics and code are logged before exiting.
COMET INFO: Experiment is live on comet.com https://www.comet.com/scfeel/qwen3-1/5ca700b6f7ff4d6fbdcbae43fabf4346

extraction:florence:image_only:   0%|          | 0/400 [00:00<?, ?it/s]

COMET WARNING: log_asset_data(..., file_name=...) is deprecated; use log_asset_data(..., name=...)
COMET WARNING: log_asset_data(..., file_name=...) is deprecated; use log_asset_data(..., name=...)
COMET WARNING: log_asset_data(..., file_name=...) is deprecated; use log_asset_data(..., name=...)
COMET WARNING: log_asset_data(..., file_name=...) is deprecated; use log_asset_data(..., name=...)
COMET WARNING: Couldn't retrieve and log Google Colab notebook content, reason: 'NoneType' object is not subscriptable
COMET INFO: ---------------------------------------------------------------------------------------
COMET INFO: Comet.ml Experiment Summary
COMET INFO: ---------------------------------------------------------------------------------------
COMET INFO:   Data:
COMET INFO:     display_summary_level : 1
COMET INFO:     name                  : extraction-baseline-florence2
COMET INFO:     url                   : https://www.comet.com/scfeel/qwen3-1/5ca700b6f7ff4d6fbdcbae43fabf4346
COMET INFO:   Metrics:
COMET INFO:     seen_img_black_corrected_em     : -0.01425
COMET INFO:     seen_img_blur_20_corrected_em   : -0.01425
COMET INFO:     seen_img_blur_50_corrected_em   : -0.01425
COMET INFO:     seen_original_corrected_em      : -0.01425
COMET INFO:     unseen_img_black_corrected_em   : -0.0017500000000000003
COMET INFO:     unseen_img_blur_20_corrected_em : -0.0017500000000000003
COMET INFO:     unseen_img_blur_50_corrected_em : -0.0017500000000000003
COMET INFO:     unseen_original_corrected_em    : -0.0017500000000000003
COMET INFO:   Others:
COMET INFO:     Name         : extraction-baseline-florence2
COMET INFO:     notebook_url : https://colab.research.google.com/notebook#23_data_extraction-jvsc-7416a373-b093-4a59-b7c3-56b6a99eed15e4640795-6a38-4ef8-a86f-442e6010de1e.ipynb
COMET INFO:   Parameters:
COMET INFO:     mode      : image_only
COMET INFO:     model_tag : baseline_florence2
COMET INFO:     n_seen    : 200
COMET INFO:     n_unseen  : 200
COMET INFO:     scenarios : ['original', 'img_black', 'img_blur_20', 'img_blur_50']
COMET INFO:   Uploads:
COMET INFO:     asset                    : 8 (977.13 KB)
COMET INFO:     dataframe                : 2 (7.36 KB)
COMET INFO:     environment details      : 1
COMET INFO:     filename                 : 1
COMET INFO:     git metadata             : 1
COMET INFO:     git-patch (uncompressed) : 1 (68.35 MB)
COMET INFO:     installed packages       : 1
COMET INFO:     notebook                 : 1
COMET INFO:     os packages              : 1
COMET INFO:     source_code              : 1
COMET INFO:
COMET WARNING: To get all data logged automatically, import comet_ml before the following modules: torch, tensorflow, sklearn, keras.
COMET INFO: Please wait for metadata to finish uploading (timeout is 3600 seconds)
COMET INFO: Uploading 1 metrics, params and output messages

,split,scenario,coarse_type,n_examples,exact_match,token_f1,random_em,random_f1,corrected_em,corrected_f1
0,seen,img_black,ALL,200,0.0,0.023129,0.014250,0.034906,-0.014250,-0.011777
1,seen,img_black,AMOUNT,35,0.0,0.003361,0.007143,0.028143,-0.007143,-0.024782
2,seen,img_black,CONTACT_ADR,33,0.0,0.021419,0.037879,0.040909,-0.037879,-0.019490
3,seen,img_black,DATE,33,0.0,0.005051,0.004545,0.035245,-0.004545,-0.030195
4,seen,img_black,ID,33,0.0,0.025364,0.015152,0.016667,-0.015152,0.008697
5,seen,img_black,ORG,33,0.0,0.080448,0.019697,0.073098,-0.019697,0.007351
6,seen,img_black,PERSON,33,0.0,0.004329,0.001515,0.015783,-0.001515,-0.011454
7,seen,img_blur_20,ALL,200,0.0,0.023262,0.014250,0.034906,-0.014250,-0.011643
8,seen,img_blur_20,AMOUNT,35,0.0,0.003361,0.007143,0.028143,-0.007143,-0.024782
9,seen,img_blur_20,CONTACT_ADR,33,0.0,0.021419,0.037879,0.040909,-0.037879,-0.019490
10,seen,img_blur_20,DATE,33,0.0,0.005051,0.004545,0.035245,-0.004545,-0.030195
11,seen,img_blur_20,ID,33,0.0,0.025364,0.015152,0.016667,-0.015152,0.008697
12,seen,img_blur_20,ORG,33,0.0,0.081257,0.019697,0.073098,-0.019697,0.008159
13,seen,img_blur_20,PERSON,33,0.0,0.004329,0.001515,0.015783,-0.001515,-0.011454
14,seen,img_blur_50,ALL,200,0.0,0.023262,0.014250,0.034906,-0.014250,-0.011643
15,seen,img_blur_50,AMOUNT,35,0.0,0.003361,0.007143,0.028143,-0.007143,-0.024782
16,seen,img_blur_50,CONTACT_ADR,33,0.0,0.021419,0.037879,0.040909,-0.037879,-0.019490
17,seen,img_blur_50,DATE,33,0.0,0.005051,0.004545,0.035245,-0.004545,-0.030195
18,seen,img_blur_50,ID,33,0.0,0.025364,0.015152,0.016667,-0.015152,0.008697
19,seen,img_blur_50,ORG,33,0.0,0.081257,0.019697,0.073098,-0.019697,0.008159
20,seen,img_blur_50,PERSON,33,0.0,0.004329,0.001515,0.015783,-0.001515,-0.011454
21,seen,original,ALL,200,0.0,0.040581,0.014250,0.034906,-0.014250,0.005675
22,seen,original,AMOUNT,35,0.0,0.003361,0.007143,0.028143,-0.007143,-0.024782
23,seen,original,CONTACT_ADR,33,0.0,0.037681,0.037879,0.040909,-0.037879,-0.003228
24,seen,original,DATE,33,0.0,0.075359,0.004545,0.035245,-0.004545,0.040114
25,seen,original,ID,33,0.0,0.027384,0.015152,0.016667,-0.015152,0.010717
26,seen,original,ORG,33,0.0,0.087721,0.019697,0.073098,-0.019697,0.014623
27,seen,original,PERSON,33,0.0,0.014236,0.001515,0.015783,-0.001515,-0.001547
28,unseen,img_black,ALL,200,0.0,0.022494,0.001750,0.014448,-0.001750,0.008046
29,unseen,img_black,AMOUNT,35,0.0,0.011538,0.000000,0.018857,0.000000,-0.007319
30,unseen,img_black,CONTACT_ADR,33,0.0,0.012393,0.006061,0.009091,-0.006061,0.003302
31,unseen,img_black,DATE,33,0.0,0.022100,0.000000,0.029516,0.000000,-0.007416
32,unseen,img_black,ID,33,0.0,0.003367,0.001515,0.002273,-0.001515,0.001094
33,unseen,img_black,ORG,33,0.0,0.071553,0.003030,0.024303,-0.003030,0.047250
34,unseen,img_black,PERSON,33,0.0,0.014676,0.000000,0.002381,0.000000,0.012295
35,unseen,img_blur_20,ALL,200,0.0,0.023639,0.001750,0.014448,-0.001750,0.009191
36,unseen,img_blur_20,AMOUNT,35,0.0,0.011538,0.000000,0.018857,0.000000,-0.007319
37,unseen,img_blur_20,CONTACT_ADR,33,0.0,0.012216,0.006061,0.009091,-0.006061,0.003125
38,unseen,img_blur_20,DATE,33,0.0,0.022100,0.000000,0.029516,0.000000,-0.007416
39,unseen,img_blur_20,ID,33,0.0,0.003276,0.001515,0.002273,-0.001515,0.001003
40,unseen,img_blur_20,ORG,33,0.0,0.078655,0.003030,0.024303,-0.003030,0.054352
41,unseen,img_blur_20,PERSON,33,0.0,0.014784,0.000000,0.002381,0.000000,0.012403
42,unseen,img_blur_50,ALL,200,0.0,0.023589,0.001750,0.014448,-0.001750,0.009141
43,unseen,img_blur_50,AMOUNT,35,0.0,0.011538,0.000000,0.018857,0.000000,-0.007319
44,unseen,img_blur_50,CONTACT_ADR,33,0.0,0.012216,0.006061,0.009091,-0.006061,0.003125
45,unseen,img_blur_50,DATE,33,0.0,0.023548,0.000000,0.029516,0.000000,-0.005967
46,unseen,img_blur_50,ID,33,0.0,0.003367,0.001515,0.002273,-0.001515,0.001094
47,unseen,img_blur_50,ORG,33,0.0,0.076813,0.003030,0.024303,-0.003030,0.052510
48,unseen,img_blur_50,PERSON,33,0.0,0.014784,0.000000,0.002381,0.000000,0.012403
49,unseen,original,ALL,200,0.0,0.050198,0.001750,0.014448,-0.001750,0.035750
50,unseen,original,AMOUNT,35,0.0,0.011642,0.000000,0.018857,0.000000,-0.007215
51,unseen,original,CONTACT_ADR,33,0.0,0.024479,0.006061,0.009091,-0.006061,0.015388
52,unseen,original,DATE,33,0.0,0.068753,0.000000,0.029516,0.000000,0.039238
53,unseen,original,ID,33,0.0,0.054259,0.001515,0.002273,-0.001515,0.051986
54,unseen,original,ORG,33,0.0,0.127219,0.003030,0.024303,-0.003030,0.102916
55,unseen,original,PERSON,33,0.0,0.017172,0.000000,0.002381,0.000000,0.014791

In [6]:
# Florence-2 epoch_30 extraction
model, processor = load_florence("checkpoints/florence2/epoch_30")
florence_outputs = run_model_extraction_experiment(
    model=model,
    processor=processor,
    model_tag="florence2_epoch30",
    model_kind="florence",
    mode="image_only",
    scenarios=FLORENCE_SCENARIOS,
    seen_records=florence_seen,
    unseen_records=unseen_200,
    answer_pools=florence_answer_pools,
    experiment_name="extraction-florence2-epoch30",
)
display(florence_outputs[2])
del model, processor
cleanup_gpu()

COMET WARNING: To get all data logged automatically, import comet_ml before the following modules: torch, tensorflow, sklearn, keras.
COMET WARNING: As you are running in a Jupyter environment, you will need to call `experiment.end()` when finished to ensure all metrics and code are logged before exiting.
COMET INFO: Experiment is live on comet.com https://www.comet.com/scfeel/qwen3-1/7171d124238b44269e21555559e6aa47

extraction:florence:image_only:   0%|          | 0/400 [00:00<?, ?it/s]

COMET WARNING: log_asset_data(..., file_name=...) is deprecated; use log_asset_data(..., name=...)
COMET WARNING: log_asset_data(..., file_name=...) is deprecated; use log_asset_data(..., name=...)
COMET WARNING: log_asset_data(..., file_name=...) is deprecated; use log_asset_data(..., name=...)
COMET WARNING: log_asset_data(..., file_name=...) is deprecated; use log_asset_data(..., name=...)
COMET WARNING: Couldn't retrieve and log Google Colab notebook content, reason: 'NoneType' object is not subscriptable
COMET INFO: ---------------------------------------------------------------------------------------
COMET INFO: Comet.ml Experiment Summary
COMET INFO: ---------------------------------------------------------------------------------------
COMET INFO:   Data:
COMET INFO:     display_summary_level : 1
COMET INFO:     name                  : extraction-florence2-epoch30
COMET INFO:     url                   : https://www.comet.com/scfeel/qwen3-1/7171d124238b44269e21555559e6aa47
COMET INFO:   Metrics:
COMET INFO:     seen_img_black_corrected_em     : 0.14575
COMET INFO:     seen_img_blur_20_corrected_em   : 0.15075000000000002
COMET INFO:     seen_img_blur_50_corrected_em   : 0.15575
COMET INFO:     seen_original_corrected_em      : 0.9657499999999999
COMET INFO:     unseen_img_black_corrected_em   : 0.00825
COMET INFO:     unseen_img_blur_20_corrected_em : 0.00825
COMET INFO:     unseen_img_blur_50_corrected_em : 0.00825
COMET INFO:     unseen_original_corrected_em    : 0.11825
COMET INFO:   Others:
COMET INFO:     Name         : extraction-florence2-epoch30
COMET INFO:     notebook_url : https://colab.research.google.com/notebook#23_data_extraction-jvsc-7416a373-b093-4a59-b7c3-56b6a99eed15e4640795-6a38-4ef8-a86f-442e6010de1e.ipynb
COMET INFO:   Parameters:
COMET INFO:     mode      : image_only
COMET INFO:     model_tag : florence2_epoch30
COMET INFO:     n_seen    : 200
COMET INFO:     n_unseen  : 200
COMET INFO:     scenarios : ['original', 'img_black', 'img_blur_20', 'img_blur_50']
COMET INFO:   Uploads:
COMET INFO:     asset                    : 8 (591.78 KB)
COMET INFO:     dataframe                : 2 (11.26 KB)
COMET INFO:     environment details      : 1
COMET INFO:     filename                 : 1
COMET INFO:     git metadata             : 1
COMET INFO:     git-patch (uncompressed) : 1 (68.35 MB)
COMET INFO:     images                   : 5
COMET INFO:     installed packages       : 1
COMET INFO:     notebook                 : 1
COMET INFO:     os packages              : 1
COMET INFO:     source_code              : 1
COMET INFO:
COMET WARNING: To get all data logged automatically, import comet_ml before the following modules: torch, tensorflow, sklearn, keras.

,split,scenario,coarse_type,n_examples,exact_match,token_f1,random_em,random_f1,corrected_em,corrected_f1
0,seen,img_black,ALL,200,0.160000,0.284155,0.014250,0.034906,0.145750,0.249249
1,seen,img_black,AMOUNT,35,0.200000,0.347619,0.007143,0.028143,0.192857,0.319476
2,seen,img_black,CONTACT_ADR,33,0.272727,0.373737,0.037879,0.040909,0.234848,0.332828
3,seen,img_black,DATE,33,0.151515,0.269841,0.004545,0.035245,0.146970,0.234596
4,seen,img_black,ID,33,0.060606,0.113131,0.015152,0.016667,0.045455,0.096465
5,seen,img_black,ORG,33,0.151515,0.363709,0.019697,0.073098,0.131818,0.290611
6,seen,img_black,PERSON,33,0.121212,0.233045,0.001515,0.015783,0.119697,0.217262
7,seen,img_blur_20,ALL,200,0.165000,0.290040,0.014250,0.034906,0.150750,0.255134
8,seen,img_blur_20,AMOUNT,35,0.257143,0.404762,0.007143,0.028143,0.250000,0.376619
9,seen,img_blur_20,CONTACT_ADR,33,0.272727,0.385859,0.037879,0.040909,0.234848,0.344949
10,seen,img_blur_20,DATE,33,0.151515,0.327561,0.004545,0.035245,0.146970,0.292316
11,seen,img_blur_20,ID,33,0.030303,0.082828,0.015152,0.016667,0.015152,0.066162
12,seen,img_blur_20,ORG,33,0.151515,0.323473,0.019697,0.073098,0.131818,0.250375
13,seen,img_blur_20,PERSON,33,0.121212,0.208802,0.001515,0.015783,0.119697,0.193019
14,seen,img_blur_50,ALL,200,0.170000,0.295595,0.014250,0.034906,0.155750,0.260689
15,seen,img_blur_50,AMOUNT,35,0.257143,0.404762,0.007143,0.028143,0.250000,0.376619
16,seen,img_blur_50,CONTACT_ADR,33,0.272727,0.376768,0.037879,0.040909,0.234848,0.335859
17,seen,img_blur_50,DATE,33,0.151515,0.337662,0.004545,0.035245,0.146970,0.302417
18,seen,img_blur_50,ID,33,0.030303,0.082828,0.015152,0.016667,0.015152,0.066162
19,seen,img_blur_50,ORG,33,0.181818,0.356133,0.019697,0.073098,0.162121,0.283035
20,seen,img_blur_50,PERSON,33,0.121212,0.208802,0.001515,0.015783,0.119697,0.193019
21,seen,original,ALL,200,0.980000,0.982500,0.014250,0.034906,0.965750,0.947594
22,seen,original,AMOUNT,35,0.914286,0.928571,0.007143,0.028143,0.907143,0.900429
23,seen,original,CONTACT_ADR,33,1.000000,1.000000,0.037879,0.040909,0.962121,0.959091
24,seen,original,DATE,33,1.000000,1.000000,0.004545,0.035245,0.995455,0.964755
25,seen,original,ID,33,1.000000,1.000000,0.015152,0.016667,0.984848,0.983333
26,seen,original,ORG,33,0.969697,0.969697,0.019697,0.073098,0.950000,0.896599
27,seen,original,PERSON,33,1.000000,1.000000,0.001515,0.015783,0.998485,0.984217
28,unseen,img_black,ALL,200,0.010000,0.059742,0.001750,0.014448,0.008250,0.045294
29,unseen,img_black,AMOUNT,35,0.000000,0.014286,0.000000,0.018857,0.000000,-0.004571
30,unseen,img_black,CONTACT_ADR,33,0.000000,0.071789,0.006061,0.009091,-0.006061,0.062698
31,unseen,img_black,DATE,33,0.000000,0.096032,0.000000,0.029516,0.000000,0.066516
32,unseen,img_black,ID,33,0.000000,0.020202,0.001515,0.002273,-0.001515,0.017929
33,unseen,img_black,ORG,33,0.060606,0.145262,0.003030,0.024303,0.057576,0.120959
34,unseen,img_black,PERSON,33,0.000000,0.013636,0.000000,0.002381,0.000000,0.011255
35,unseen,img_blur_20,ALL,200,0.010000,0.055813,0.001750,0.014448,0.008250,0.041366
36,unseen,img_blur_20,AMOUNT,35,0.000000,0.014286,0.000000,0.018857,0.000000,-0.004571
37,unseen,img_blur_20,CONTACT_ADR,33,0.000000,0.046537,0.006061,0.009091,-0.006061,0.037446
38,unseen,img_blur_20,DATE,33,0.000000,0.096032,0.000000,0.029516,0.000000,0.066516
39,unseen,img_blur_20,ID,33,0.000000,0.020202,0.001515,0.002273,-0.001515,0.017929
40,unseen,img_blur_20,ORG,33,0.060606,0.146705,0.003030,0.024303,0.057576,0.122402
41,unseen,img_blur_20,PERSON,33,0.000000,0.013636,0.000000,0.002381,0.000000,0.011255
42,unseen,img_blur_50,ALL,200,0.010000,0.054147,0.001750,0.014448,0.008250,0.039699
43,unseen,img_blur_50,AMOUNT,35,0.000000,0.014286,0.000000,0.018857,0.000000,-0.004571
44,unseen,img_blur_50,CONTACT_ADR,33,0.000000,0.046537,0.006061,0.009091,-0.006061,0.037446
45,unseen,img_blur_50,DATE,33,0.000000,0.085931,0.000000,0.029516,0.000000,0.056415
46,unseen,img_blur_50,ID,33,0.000000,0.020202,0.001515,0.002273,-0.001515,0.017929
47,unseen,img_blur_50,ORG,33,0.060606,0.146705,0.003030,0.024303,0.057576,0.122402
48,unseen,img_blur_50,PERSON,33,0.000000,0.013636,0.000000,0.002381,0.000000,0.011255
49,unseen,original,ALL,200,0.120000,0.250448,0.001750,0.014448,0.118250,0.236001
50,unseen,original,AMOUNT,35,0.171429,0.211429,0.000000,0.018857,0.171429,0.192571
51,unseen,original,CONTACT_ADR,33,0.090909,0.221212,0.006061,0.009091,0.084848,0.212121
52,unseen,original,DATE,33,0.151515,0.386580,0.000000,0.029516,0.151515,0.357065
53,unseen,original,ID,33,0.212121,0.242424,0.001515,0.002273,0.210606,0.240152
54,unseen,original,ORG,33,0.060606,0.272463,0.003030,0.024303,0.057576,0.248160
55,unseen,original,PERSON,33,0.030303,0.170948,0.000000,0.002381,0.030303,0.168567

In [7]:
# Qwen2-VL-2B extraction
model, processor = load_qwen("Qwen/Qwen2-VL-2B-Instruct", "checkpoints/qwen2b/epoch_20")
qwen2b_image_only_outputs = run_model_extraction_experiment(
    model=model,
    processor=processor,
    model_tag="qwen2b_epoch20",
    model_kind="qwen",
    mode="image_only",
    scenarios=QWEN_IMAGE_ONLY_SCENARIOS,
    seen_records=qwen_seen,
    unseen_records=unseen_200,
    answer_pools=qwen_answer_pools,
    experiment_name="extraction-qwen2b-epoch20-imageonly",
)
display(qwen2b_image_only_outputs[2])
del model, processor
cleanup_gpu()

model, processor = load_qwen("Qwen/Qwen2-VL-2B-Instruct", "checkpoints/qwen2b/epoch_20")
qwen2b_image_ocr_outputs = run_model_extraction_experiment(
    model=model,
    processor=processor,
    model_tag="qwen2b_epoch20",
    model_kind="qwen",
    mode="image_ocr",
    scenarios=QWEN_IMAGE_OCR_SCENARIOS,
    seen_records=qwen_seen,
    unseen_records=unseen_200,
    answer_pools=qwen_answer_pools,
    experiment_name="extraction-qwen2b-epoch20-imageocr",
)
display(qwen2b_image_ocr_outputs[2])
del model, processor
cleanup_gpu()

The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.

config.json: 0.00B [00:00, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading shards:   0%|          | 0/2 [00:00<?, ?it/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/3.99G [00:00<?, ?B/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/429M [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/272 [00:00<?, ?B/s]

preprocessor_config.json:   0%|          | 0.00/347 [00:00<?, ?B/s]

Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.48, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

chat_template.json: 0.00B [00:00, ?B/s]

COMET WARNING: To get all data logged automatically, import comet_ml before the following modules: torch, tensorflow, sklearn, keras.
COMET WARNING: As you are running in a Jupyter environment, you will need to call `experiment.end()` when finished to ensure all metrics and code are logged before exiting.
COMET INFO: Experiment is live on comet.com https://www.comet.com/scfeel/qwen3-1/51398cc1efad473bb3dae0f284638504

extraction:qwen:image_only:   0%|          | 0/400 [00:00<?, ?it/s]

COMET WARNING: log_asset_data(..., file_name=...) is deprecated; use log_asset_data(..., name=...)
COMET WARNING: log_asset_data(..., file_name=...) is deprecated; use log_asset_data(..., name=...)
COMET WARNING: log_asset_data(..., file_name=...) is deprecated; use log_asset_data(..., name=...)
COMET WARNING: log_asset_data(..., file_name=...) is deprecated; use log_asset_data(..., name=...)
COMET WARNING: Couldn't retrieve and log Google Colab notebook content, reason: 'NoneType' object is not subscriptable
COMET INFO: ---------------------------------------------------------------------------------------
COMET INFO: Comet.ml Experiment Summary
COMET INFO: ---------------------------------------------------------------------------------------
COMET INFO:   Data:
COMET INFO:     display_summary_level : 1
COMET INFO:     name                  : extraction-qwen2b-epoch20-imageonly
COMET INFO:     url                   : https://www.comet.com/scfeel/qwen3-1/51398cc1efad473bb3dae0f284638504
COMET INFO:   Metrics:
COMET INFO:     seen_img_black_corrected_em     : 0.59575
COMET INFO:     seen_img_blur_20_corrected_em   : 0.60075
COMET INFO:     seen_img_blur_50_corrected_em   : 0.60075
COMET INFO:     seen_original_corrected_em      : 0.94575
COMET INFO:     unseen_img_black_corrected_em   : 0.00825
COMET INFO:     unseen_img_blur_20_corrected_em : 0.00825
COMET INFO:     unseen_img_blur_50_corrected_em : 0.00825
COMET INFO:     unseen_original_corrected_em    : 0.14325
COMET INFO:   Others:
COMET INFO:     Name         : extraction-qwen2b-epoch20-imageonly
COMET INFO:     notebook_url : https://colab.research.google.com/notebook#23_data_extraction-jvsc-7416a373-b093-4a59-b7c3-56b6a99eed15e4640795-6a38-4ef8-a86f-442e6010de1e.ipynb
COMET INFO:   Parameters:
COMET INFO:     mode      : image_only
COMET INFO:     model_tag : qwen2b_epoch20
COMET INFO:     n_seen    : 200
COMET INFO:     n_unseen  : 200
COMET INFO:     scenarios : ['original', 'img_black', 'img_blur_20', 'img_blur_50']
COMET INFO:   Uploads:
COMET INFO:     asset                    : 8 (595.05 KB)
COMET INFO:     dataframe                : 2 (12.05 KB)
COMET INFO:     environment details      : 1
COMET INFO:     filename                 : 1
COMET INFO:     git metadata             : 1
COMET INFO:     git-patch (uncompressed) : 1 (68.35 MB)
COMET INFO:     images                   : 5
COMET INFO:     installed packages       : 1
COMET INFO:     notebook                 : 1
COMET INFO:     os packages              : 1
COMET INFO:     source_code              : 1
COMET INFO:
COMET WARNING: To get all data logged automatically, import comet_ml before the following modules: torch, tensorflow, sklearn, keras.

,split,scenario,coarse_type,n_examples,exact_match,token_f1,random_em,random_f1,corrected_em,corrected_f1
0,seen,img_black,ALL,200,0.610000,0.659755,0.014250,0.034906,0.595750,0.624850
1,seen,img_black,AMOUNT,35,0.600000,0.633333,0.007143,0.028143,0.592857,0.605190
2,seen,img_black,CONTACT_ADR,33,0.575758,0.644930,0.037879,0.040909,0.537879,0.604021
3,seen,img_black,DATE,33,0.484848,0.563709,0.004545,0.035245,0.480303,0.528463
4,seen,img_black,ID,33,0.606061,0.618182,0.015152,0.016667,0.590909,0.601515
5,seen,img_black,ORG,33,0.575758,0.673140,0.019697,0.073098,0.556061,0.600043
6,seen,img_black,PERSON,33,0.818182,0.826840,0.001515,0.015783,0.816667,0.811057
7,seen,img_blur_20,ALL,200,0.615000,0.657999,0.014250,0.034906,0.600750,0.623093
8,seen,img_blur_20,AMOUNT,35,0.600000,0.633333,0.007143,0.028143,0.592857,0.605190
9,seen,img_blur_20,CONTACT_ADR,33,0.545455,0.608999,0.037879,0.040909,0.507576,0.568090
10,seen,img_blur_20,DATE,33,0.484848,0.543506,0.004545,0.035245,0.480303,0.508261
11,seen,img_blur_20,ID,33,0.606061,0.620047,0.015152,0.016667,0.590909,0.603380
12,seen,img_blur_20,ORG,33,0.636364,0.705219,0.019697,0.073098,0.616667,0.632121
13,seen,img_blur_20,PERSON,33,0.818182,0.838384,0.001515,0.015783,0.816667,0.822601
14,seen,img_blur_50,ALL,200,0.615000,0.659316,0.014250,0.034906,0.600750,0.624411
15,seen,img_blur_50,AMOUNT,35,0.600000,0.633333,0.007143,0.028143,0.592857,0.605190
16,seen,img_blur_50,CONTACT_ADR,33,0.545455,0.596878,0.037879,0.040909,0.507576,0.555969
17,seen,img_blur_50,DATE,33,0.484848,0.561688,0.004545,0.035245,0.480303,0.526443
18,seen,img_blur_50,ID,33,0.606061,0.620047,0.015152,0.016667,0.590909,0.603380
19,seen,img_blur_50,ORG,33,0.636364,0.707143,0.019697,0.073098,0.616667,0.634045
20,seen,img_blur_50,PERSON,33,0.818182,0.838384,0.001515,0.015783,0.816667,0.822601
21,seen,original,ALL,200,0.960000,0.970641,0.014250,0.034906,0.945750,0.935735
22,seen,original,AMOUNT,35,0.857143,0.890476,0.007143,0.028143,0.850000,0.862333
23,seen,original,CONTACT_ADR,33,0.969697,0.984848,0.037879,0.040909,0.931818,0.943939
24,seen,original,DATE,33,0.969697,0.969697,0.004545,0.035245,0.965152,0.934452
25,seen,original,ID,33,0.969697,0.983683,0.015152,0.016667,0.954545,0.967016
26,seen,original,ORG,33,1.000000,1.000000,0.019697,0.073098,0.980303,0.926902
27,seen,original,PERSON,33,1.000000,1.000000,0.001515,0.015783,0.998485,0.984217
28,unseen,img_black,ALL,200,0.010000,0.066091,0.001750,0.014448,0.008250,0.051643
29,unseen,img_black,AMOUNT,35,0.028571,0.087619,0.000000,0.018857,0.028571,0.068762
30,unseen,img_black,CONTACT_ADR,33,0.000000,0.025874,0.006061,0.009091,-0.006061,0.016783
31,unseen,img_black,DATE,33,0.000000,0.110967,0.000000,0.029516,0.000000,0.081451
32,unseen,img_black,ID,33,0.000000,0.022727,0.001515,0.002273,-0.001515,0.020455
33,unseen,img_black,ORG,33,0.030303,0.117172,0.003030,0.024303,0.027273,0.092869
34,unseen,img_black,PERSON,33,0.000000,0.030880,0.000000,0.002381,0.000000,0.028499
35,unseen,img_blur_20,ALL,200,0.010000,0.053509,0.001750,0.014448,0.008250,0.039061
36,unseen,img_blur_20,AMOUNT,35,0.000000,0.038095,0.000000,0.018857,0.000000,0.019238
37,unseen,img_blur_20,CONTACT_ADR,33,0.000000,0.026548,0.006061,0.009091,-0.006061,0.017457
38,unseen,img_blur_20,DATE,33,0.000000,0.100866,0.000000,0.029516,0.000000,0.071350
39,unseen,img_blur_20,ID,33,0.000000,0.021886,0.001515,0.002273,-0.001515,0.019613
40,unseen,img_blur_20,ORG,33,0.030303,0.073411,0.003030,0.024303,0.027273,0.049108
41,unseen,img_blur_20,PERSON,33,0.030303,0.061183,0.000000,0.002381,0.030303,0.058802
42,unseen,img_blur_50,ALL,200,0.010000,0.057068,0.001750,0.014448,0.008250,0.042620
43,unseen,img_blur_50,AMOUNT,35,0.000000,0.047619,0.000000,0.018857,0.000000,0.028762
44,unseen,img_blur_50,CONTACT_ADR,33,0.000000,0.028904,0.006061,0.009091,-0.006061,0.019814
45,unseen,img_blur_50,DATE,33,0.000000,0.100866,0.000000,0.029516,0.000000,0.071350
46,unseen,img_blur_50,ID,33,0.000000,0.023810,0.001515,0.002273,-0.001515,0.021537
47,unseen,img_blur_50,ORG,33,0.030303,0.080600,0.003030,0.024303,0.027273,0.056297
48,unseen,img_blur_50,PERSON,33,0.030303,0.061183,0.000000,0.002381,0.030303,0.058802
49,unseen,original,ALL,200,0.145000,0.206895,0.001750,0.014448,0.143250,0.192447
50,unseen,original,AMOUNT,35,0.142857,0.171429,0.000000,0.018857,0.142857,0.152571
51,unseen,original,CONTACT_ADR,33,0.060606,0.119529,0.006061,0.009091,0.054545,0.110438
52,unseen,original,DATE,33,0.242424,0.366919,0.000000,0.029516,0.242424,0.337404
53,unseen,original,ID,33,0.090909,0.111111,0.001515,0.002273,0.089394,0.108838
54,unseen,original,ORG,33,0.181818,0.237662,0.003030,0.024303,0.178788,0.213359
55,unseen,original,PERSON,33,0.151515,0.236869,0.000000,0.002381,0.151515,0.234488

The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

COMET WARNING: To get all data logged automatically, import comet_ml before the following modules: torch, tensorflow, sklearn, keras.
COMET WARNING: As you are running in a Jupyter environment, you will need to call `experiment.end()` when finished to ensure all metrics and code are logged before exiting.
COMET INFO: Experiment is live on comet.com https://www.comet.com/scfeel/qwen3-1/477fc3e0f32d4bb6a65c547119282819

extraction:qwen:image_ocr:   0%|          | 0/400 [00:00<?, ?it/s]

COMET WARNING: log_asset_data(..., file_name=...) is deprecated; use log_asset_data(..., name=...)
COMET WARNING: log_asset_data(..., file_name=...) is deprecated; use log_asset_data(..., name=...)
COMET WARNING: log_asset_data(..., file_name=...) is deprecated; use log_asset_data(..., name=...)
COMET WARNING: log_asset_data(..., file_name=...) is deprecated; use log_asset_data(..., name=...)
COMET WARNING: Couldn't retrieve and log Google Colab notebook content, reason: 'NoneType' object is not subscriptable
COMET INFO: ---------------------------------------------------------------------------------------
COMET INFO: Comet.ml Experiment Summary
COMET INFO: ---------------------------------------------------------------------------------------
COMET INFO:   Data:
COMET INFO:     display_summary_level : 1
COMET INFO:     name                  : extraction-qwen2b-epoch20-imageocr
COMET INFO:     url                   : https://www.comet.com/scfeel/qwen3-1/477fc3e0f32d4bb6a65c547119282819
COMET INFO:   Metrics:
COMET INFO:     seen_img_black__ocr_mask__k_0_corrected_em   : 0.02575
COMET INFO:     seen_img_none__ocr_mask__k_0_corrected_em    : 0.32075000000000004
COMET INFO:     unseen_img_black__ocr_mask__k_0_corrected_em : 0.0032499999999999994
COMET INFO:     unseen_img_none__ocr_mask__k_0_corrected_em  : 0.15325
COMET INFO:   Others:
COMET INFO:     Name         : extraction-qwen2b-epoch20-imageocr
COMET INFO:     notebook_url : https://colab.research.google.com/notebook#23_data_extraction-jvsc-7416a373-b093-4a59-b7c3-56b6a99eed15e4640795-6a38-4ef8-a86f-442e6010de1e.ipynb
COMET INFO:   Parameters:
COMET INFO:     mode      : image_ocr
COMET INFO:     model_tag : qwen2b_epoch20
COMET INFO:     n_seen    : 200
COMET INFO:     n_unseen  : 200
COMET INFO:     scenarios : ['img_black__ocr_mask__k_0', 'img_none__ocr_mask__k_0']
COMET INFO:   Uploads:
COMET INFO:     asset                    : 8 (2.19 MB)
COMET INFO:     dataframe                : 2 (33.98 KB)
COMET INFO:     environment details      : 1
COMET INFO:     filename                 : 1
COMET INFO:     git metadata             : 1
COMET INFO:     git-patch (uncompressed) : 1 (68.35 MB)
COMET INFO:     images                   : 5
COMET INFO:     installed packages       : 1
COMET INFO:     notebook                 : 1
COMET INFO:     os packages              : 1
COMET INFO:     source_code              : 1
COMET INFO:
COMET WARNING: To get all data logged automatically, import comet_ml before the following modules: torch, tensorflow, sklearn, keras.

,split,scenario,coarse_type,n_examples,exact_match,token_f1,random_em,random_f1,corrected_em,corrected_f1
0,seen,img_black__ocr_mask__k_0,ALL,200,0.040000,0.128294,0.014250,0.034906,0.025750,0.093389
1,seen,img_black__ocr_mask__k_0,AMOUNT,35,0.028571,0.080952,0.007143,0.028143,0.021429,0.052810
2,seen,img_black__ocr_mask__k_0,CONTACT_ADR,33,0.000000,0.088797,0.037879,0.040909,-0.037879,0.047888
3,seen,img_black__ocr_mask__k_0,DATE,33,0.000000,0.130447,0.004545,0.035245,-0.004545,0.095202
4,seen,img_black__ocr_mask__k_0,ID,33,0.090909,0.111111,0.015152,0.016667,0.075758,0.094444
5,seen,img_black__ocr_mask__k_0,ORG,33,0.090909,0.260606,0.019697,0.073098,0.071212,0.187508
6,seen,img_black__ocr_mask__k_0,PERSON,33,0.030303,0.100722,0.001515,0.015783,0.028788,0.084939
7,seen,img_none__ocr_mask__k_0,ALL,200,0.335000,0.402714,0.014250,0.034906,0.320750,0.367809
8,seen,img_none__ocr_mask__k_0,AMOUNT,35,0.257143,0.309524,0.007143,0.028143,0.250000,0.281381
9,seen,img_none__ocr_mask__k_0,CONTACT_ADR,33,0.363636,0.419192,0.037879,0.040909,0.325758,0.378283
10,seen,img_none__ocr_mask__k_0,DATE,33,0.424242,0.503608,0.004545,0.035245,0.419697,0.468362
11,seen,img_none__ocr_mask__k_0,ID,33,0.393939,0.409091,0.015152,0.016667,0.378788,0.392424
12,seen,img_none__ocr_mask__k_0,ORG,33,0.424242,0.539538,0.019697,0.073098,0.404545,0.466441
13,seen,img_none__ocr_mask__k_0,PERSON,33,0.151515,0.240981,0.001515,0.015783,0.150000,0.225198
14,unseen,img_black__ocr_mask__k_0,ALL,200,0.005000,0.090246,0.001750,0.014448,0.003250,0.075798
15,unseen,img_black__ocr_mask__k_0,AMOUNT,35,0.000000,0.061905,0.000000,0.018857,0.000000,0.043048
16,unseen,img_black__ocr_mask__k_0,CONTACT_ADR,33,0.000000,0.125421,0.006061,0.009091,-0.006061,0.116330
17,unseen,img_black__ocr_mask__k_0,DATE,33,0.000000,0.073593,0.000000,0.029516,0.000000,0.044078
18,unseen,img_black__ocr_mask__k_0,ID,33,0.000000,0.045455,0.001515,0.002273,-0.001515,0.043182
19,unseen,img_black__ocr_mask__k_0,ORG,33,0.030303,0.173617,0.003030,0.024303,0.027273,0.149314
20,unseen,img_black__ocr_mask__k_0,PERSON,33,0.000000,0.063203,0.000000,0.002381,0.000000,0.060823
21,unseen,img_none__ocr_mask__k_0,ALL,200,0.155000,0.254990,0.001750,0.014448,0.153250,0.240542
22,unseen,img_none__ocr_mask__k_0,AMOUNT,35,0.171429,0.247619,0.000000,0.018857,0.171429,0.228762
23,unseen,img_none__ocr_mask__k_0,CONTACT_ADR,33,0.030303,0.204185,0.006061,0.009091,0.024242,0.195094
24,unseen,img_none__ocr_mask__k_0,DATE,33,0.333333,0.425505,0.000000,0.029516,0.333333,0.395990
25,unseen,img_none__ocr_mask__k_0,ID,33,0.090909,0.140404,0.001515,0.002273,0.089394,0.138131
26,unseen,img_none__ocr_mask__k_0,ORG,33,0.181818,0.292905,0.003030,0.024303,0.178788,0.268602
27,unseen,img_none__ocr_mask__k_0,PERSON,33,0.121212,0.219769,0.000000,0.002381,0.121212,0.217388

In [8]:
# Qwen2-VL-7B extraction
model, processor = load_qwen("Qwen/Qwen2-VL-7B-Instruct", "checkpoints/qwen7b/epoch_10")
qwen7b_image_only_outputs = run_model_extraction_experiment(
    model=model,
    processor=processor,
    model_tag="qwen7b_epoch10",
    model_kind="qwen",
    mode="image_only",
    scenarios=QWEN_IMAGE_ONLY_SCENARIOS,
    seen_records=qwen_seen,
    unseen_records=unseen_200,
    answer_pools=qwen_answer_pools,
    experiment_name="extraction-qwen7b-epoch10-imageonly",
)
display(qwen7b_image_only_outputs[2])
del model, processor
cleanup_gpu()

The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.

config.json: 0.00B [00:00, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading shards:   0%|          | 0/5 [00:00<?, ?it/s]

model-00001-of-00005.safetensors:   0%|          | 0.00/3.90G [00:00<?, ?B/s]

model-00002-of-00005.safetensors:   0%|          | 0.00/3.86G [00:00<?, ?B/s]

model-00003-of-00005.safetensors:   0%|          | 0.00/3.86G [00:00<?, ?B/s]

model-00004-of-00005.safetensors:   0%|          | 0.00/3.86G [00:00<?, ?B/s]

model-00005-of-00005.safetensors:   0%|          | 0.00/1.09G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/5 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/244 [00:00<?, ?B/s]

preprocessor_config.json:   0%|          | 0.00/347 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

chat_template.json: 0.00B [00:00, ?B/s]

COMET WARNING: To get all data logged automatically, import comet_ml before the following modules: torch, tensorflow, sklearn, keras.
COMET WARNING: As you are running in a Jupyter environment, you will need to call `experiment.end()` when finished to ensure all metrics and code are logged before exiting.
COMET INFO: Experiment is live on comet.com https://www.comet.com/scfeel/qwen3-1/d2248a1f8d02495ebd93f08787e81344

extraction:qwen:image_only:   0%|          | 0/400 [00:00<?, ?it/s]

COMET WARNING: log_asset_data(..., file_name=...) is deprecated; use log_asset_data(..., name=...)
COMET WARNING: log_asset_data(..., file_name=...) is deprecated; use log_asset_data(..., name=...)
COMET WARNING: log_asset_data(..., file_name=...) is deprecated; use log_asset_data(..., name=...)
COMET WARNING: log_asset_data(..., file_name=...) is deprecated; use log_asset_data(..., name=...)
COMET WARNING: Couldn't retrieve and log Google Colab notebook content, reason: 'NoneType' object is not subscriptable
COMET INFO: ---------------------------------------------------------------------------------------
COMET INFO: Comet.ml Experiment Summary
COMET INFO: ---------------------------------------------------------------------------------------
COMET INFO:   Data:
COMET INFO:     display_summary_level : 1
COMET INFO:     name                  : extraction-qwen7b-epoch10-imageonly
COMET INFO:     url                   : https://www.comet.com/scfeel/qwen3-1/d2248a1f8d02495ebd93f08787e81344
COMET INFO:   Metrics:
COMET INFO:     seen_img_black_corrected_em     : 0.5457500000000001
COMET INFO:     seen_img_blur_20_corrected_em   : 0.5457500000000001
COMET INFO:     seen_img_blur_50_corrected_em   : 0.5507500000000001
COMET INFO:     seen_original_corrected_em      : 0.88075
COMET INFO:     unseen_img_black_corrected_em   : 0.023249999999999996
COMET INFO:     unseen_img_blur_20_corrected_em : 0.023249999999999996
COMET INFO:     unseen_img_blur_50_corrected_em : 0.023249999999999996
COMET INFO:     unseen_original_corrected_em    : 0.22325000000000003
COMET INFO:   Others:
COMET INFO:     Name         : extraction-qwen7b-epoch10-imageonly
COMET INFO:     notebook_url : https://colab.research.google.com/notebook#23_data_extraction-jvsc-7416a373-b093-4a59-b7c3-56b6a99eed15e4640795-6a38-4ef8-a86f-442e6010de1e.ipynb
COMET INFO:   Parameters:
COMET INFO:     mode      : image_only
COMET INFO:     model_tag : qwen7b_epoch10
COMET INFO:     n_seen    : 200
COMET INFO:     n_unseen  : 200
COMET INFO:     scenarios : ['original', 'img_black', 'img_blur_20', 'img_blur_50']
COMET INFO:   Uploads:
COMET INFO:     asset                    : 8 (595.90 KB)
COMET INFO:     dataframe                : 2 (12.25 KB)
COMET INFO:     environment details      : 1
COMET INFO:     filename                 : 1
COMET INFO:     git metadata             : 1
COMET INFO:     git-patch (uncompressed) : 1 (68.35 MB)
COMET INFO:     images                   : 5
COMET INFO:     installed packages       : 1
COMET INFO:     notebook                 : 1
COMET INFO:     os packages              : 1
COMET INFO:     source_code              : 1
COMET INFO:
COMET WARNING: To get all data logged automatically, import comet_ml before the following modules: torch, tensorflow, sklearn, keras.

,split,scenario,coarse_type,n_examples,exact_match,token_f1,random_em,random_f1,corrected_em,corrected_f1
0,seen,img_black,ALL,200,0.560000,0.629224,0.014250,0.034906,0.545750,0.594318
1,seen,img_black,AMOUNT,35,0.485714,0.566667,0.007143,0.028143,0.478571,0.538524
2,seen,img_black,CONTACT_ADR,33,0.393939,0.510468,0.037879,0.040909,0.356061,0.469559
3,seen,img_black,DATE,33,0.545455,0.614719,0.004545,0.035245,0.540909,0.579473
4,seen,img_black,ID,33,0.575758,0.606979,0.015152,0.016667,0.560606,0.590312
5,seen,img_black,ORG,33,0.606061,0.679798,0.019697,0.073098,0.586364,0.606700
6,seen,img_black,PERSON,33,0.757576,0.800505,0.001515,0.015783,0.756061,0.784722
7,seen,img_blur_20,ALL,200,0.560000,0.622589,0.014250,0.034906,0.545750,0.587683
8,seen,img_blur_20,AMOUNT,35,0.457143,0.538095,0.007143,0.028143,0.450000,0.509952
9,seen,img_blur_20,CONTACT_ADR,33,0.393939,0.517080,0.037879,0.040909,0.356061,0.476171
10,seen,img_blur_20,DATE,33,0.545455,0.594517,0.004545,0.035245,0.540909,0.559271
11,seen,img_blur_20,ID,33,0.575758,0.606979,0.015152,0.016667,0.560606,0.590312
12,seen,img_blur_20,ORG,33,0.636364,0.703030,0.019697,0.073098,0.616667,0.629933
13,seen,img_blur_20,PERSON,33,0.757576,0.780952,0.001515,0.015783,0.756061,0.765170
14,seen,img_blur_50,ALL,200,0.565000,0.624994,0.014250,0.034906,0.550750,0.590088
15,seen,img_blur_50,AMOUNT,35,0.457143,0.538095,0.007143,0.028143,0.450000,0.509952
16,seen,img_blur_50,CONTACT_ADR,33,0.393939,0.482736,0.037879,0.040909,0.356061,0.441827
17,seen,img_blur_50,DATE,33,0.545455,0.594517,0.004545,0.035245,0.540909,0.559271
18,seen,img_blur_50,ID,33,0.606061,0.637282,0.015152,0.016667,0.590909,0.620615
19,seen,img_blur_50,ORG,33,0.636364,0.720202,0.019697,0.073098,0.616667,0.647104
20,seen,img_blur_50,PERSON,33,0.757576,0.782395,0.001515,0.015783,0.756061,0.766613
21,seen,original,ALL,200,0.895000,0.919318,0.014250,0.034906,0.880750,0.884412
22,seen,original,AMOUNT,35,0.714286,0.780952,0.007143,0.028143,0.707143,0.752810
23,seen,original,CONTACT_ADR,33,0.757576,0.823232,0.037879,0.040909,0.719697,0.782323
24,seen,original,DATE,33,1.000000,1.000000,0.004545,0.035245,0.995455,0.964755
25,seen,original,ID,33,0.969697,0.980716,0.015152,0.016667,0.954545,0.964050
26,seen,original,ORG,33,1.000000,1.000000,0.019697,0.073098,0.980303,0.926902
27,seen,original,PERSON,33,0.939394,0.939394,0.001515,0.015783,0.937879,0.923611
28,unseen,img_black,ALL,200,0.025000,0.088039,0.001750,0.014448,0.023250,0.073591
29,unseen,img_black,AMOUNT,35,0.000000,0.052381,0.000000,0.018857,0.000000,0.033524
30,unseen,img_black,CONTACT_ADR,33,0.000000,0.077001,0.006061,0.009091,-0.006061,0.067910
31,unseen,img_black,DATE,33,0.030303,0.136729,0.000000,0.029516,0.030303,0.107213
32,unseen,img_black,ID,33,0.000000,0.045455,0.001515,0.002273,-0.001515,0.043182
33,unseen,img_black,ORG,33,0.090909,0.148990,0.003030,0.024303,0.087879,0.124687
34,unseen,img_black,PERSON,33,0.030303,0.069841,0.000000,0.002381,0.030303,0.067460
35,unseen,img_blur_20,ALL,200,0.025000,0.089997,0.001750,0.014448,0.023250,0.075549
36,unseen,img_blur_20,AMOUNT,35,0.000000,0.066667,0.000000,0.018857,0.000000,0.047810
37,unseen,img_blur_20,CONTACT_ADR,33,0.000000,0.060218,0.006061,0.009091,-0.006061,0.051127
38,unseen,img_blur_20,DATE,33,0.030303,0.129726,0.000000,0.029516,0.030303,0.100210
39,unseen,img_blur_20,ID,33,0.000000,0.020202,0.001515,0.002273,-0.001515,0.017929
40,unseen,img_blur_20,ORG,33,0.090909,0.205924,0.003030,0.024303,0.087879,0.181621
41,unseen,img_blur_20,PERSON,33,0.030303,0.058658,0.000000,0.002381,0.030303,0.056277
42,unseen,img_blur_50,ALL,200,0.025000,0.088330,0.001750,0.014448,0.023250,0.073882
43,unseen,img_blur_50,AMOUNT,35,0.000000,0.042857,0.000000,0.018857,0.000000,0.024000
44,unseen,img_blur_50,CONTACT_ADR,33,0.000000,0.060218,0.006061,0.009091,-0.006061,0.051127
45,unseen,img_blur_50,DATE,33,0.030303,0.132612,0.000000,0.029516,0.030303,0.103096
46,unseen,img_blur_50,ID,33,0.000000,0.020202,0.001515,0.002273,-0.001515,0.017929
47,unseen,img_blur_50,ORG,33,0.090909,0.205924,0.003030,0.024303,0.087879,0.181621
48,unseen,img_blur_50,PERSON,33,0.030303,0.070924,0.000000,0.002381,0.030303,0.068543
49,unseen,original,ALL,200,0.225000,0.288220,0.001750,0.014448,0.223250,0.273772
50,unseen,original,AMOUNT,35,0.200000,0.266667,0.000000,0.018857,0.200000,0.247810
51,unseen,original,CONTACT_ADR,33,0.121212,0.168687,0.006061,0.009091,0.115152,0.159596
52,unseen,original,DATE,33,0.363636,0.403175,0.000000,0.029516,0.363636,0.373659
53,unseen,original,ID,33,0.181818,0.222222,0.001515,0.002273,0.180303,0.219949
54,unseen,original,ORG,33,0.272727,0.385747,0.003030,0.024303,0.269697,0.361444
55,unseen,original,PERSON,33,0.212121,0.284127,0.000000,0.002381,0.212121,0.281746

In [9]:
# Model summaries
summary_rows = []
for name, outputs in {
    "baseline_florence2": baseline_outputs,
    "florence2_epoch30": florence_outputs,
    "qwen2b_epoch20_image_only": qwen2b_image_only_outputs,
    "qwen2b_epoch20_image_ocr": qwen2b_image_ocr_outputs,
    "qwen7b_epoch10_image_only": qwen7b_image_only_outputs,
}.items():
    metrics_df = outputs[2]
    overall = metrics_df[metrics_df["coarse_type"] == "ALL"].copy()
    overall["model"] = name
    summary_rows.append(overall)

summary_df = pd.concat(summary_rows, ignore_index=True)
summary_path = EXTRACTION_DIR / "extraction_summary.csv"

summary_experiment = comet_ml.Experiment(api_key=os.environ["COMET_API_KEY"], workspace="scfeel", project_name="qwen3-1")
summary_experiment.set_name("extraction-summary")
save_csv_with_comet(summary_df, summary_path, summary_experiment, table_name="extraction_summary.csv")

image_only_df = summary_df[(summary_df["model"].isin(["baseline_florence2", "florence2_epoch30", "qwen2b_epoch20_image_only", "qwen7b_epoch10_image_only"])) & (summary_df["split"] == "seen")].copy()
image_only_df["model_label"] = image_only_df["model"].map({
    "baseline_florence2": "Florence-2 base",
    "florence2_epoch30": "Florence-2 (эпоха 30)",
    "qwen2b_epoch20_image_only": "Qwen2-VL-2B (эпоха 20)",
    "qwen7b_epoch10_image_only": "Qwen2-VL-7B (эпоха 10)",
})
heatmap_df = image_only_df.pivot(index="model_label", columns="scenario", values="corrected_em")
fig, ax = plt.subplots(figsize=(10, 5))
sns.heatmap(heatmap_df, annot=True, fmt=".3f", cmap="YlGnBu", ax=ax)
ax.set_title("Extraction по image-only сценариям (seen)")
ax.set_xlabel("Сценарий")
ax.set_ylabel("Модель")
plt.tight_layout()
summary_experiment.log_figure("extraction_heatmap_image_only_seen", fig)
plt.close(fig)

image_ocr_df = summary_df[(summary_df["model"] == "qwen2b_epoch20_image_ocr") & (summary_df["split"] == "seen")].copy()
if not image_ocr_df.empty:
    heatmap_df = image_ocr_df.assign(model_label="Qwen2-VL-2B (epoch 20, image+OCR)").pivot(index="model_label", columns="scenario", values="corrected_em")
    fig, ax = plt.subplots(figsize=(8, 3))
    sns.heatmap(heatmap_df, annot=True, fmt=".3f", cmap="YlOrBr", ax=ax)
    ax.set_title("Extraction по image+OCR сценариям (seen)")
    ax.set_xlabel("Сценарий")
    ax.set_ylabel("")
    plt.tight_layout()
    summary_experiment.log_figure("extraction_heatmap_image_ocr_seen", fig)
    plt.close(fig)

display(summary_df)
summary_experiment.end()

COMET WARNING: To get all data logged automatically, import comet_ml before the following modules: torch, tensorflow, sklearn, keras.
COMET WARNING: As you are running in a Jupyter environment, you will need to call `experiment.end()` when finished to ensure all metrics and code are logged before exiting.
COMET INFO: Experiment is live on comet.com https://www.comet.com/scfeel/qwen3-1/2a61e0607f8740e99172b52d97fb067f

COMET WARNING: log_asset_data(..., file_name=...) is deprecated; use log_asset_data(..., name=...)

,split,scenario,coarse_type,n_examples,exact_match,token_f1,random_em,random_f1,corrected_em,corrected_f1,model
0,seen,img_black,ALL,200,0.000,0.023129,0.01425,0.034906,-0.01425,-0.011777,baseline_florence2
1,seen,img_blur_20,ALL,200,0.000,0.023262,0.01425,0.034906,-0.01425,-0.011643,baseline_florence2
2,seen,img_blur_50,ALL,200,0.000,0.023262,0.01425,0.034906,-0.01425,-0.011643,baseline_florence2
3,seen,original,ALL,200,0.000,0.040581,0.01425,0.034906,-0.01425,0.005675,baseline_florence2
4,unseen,img_black,ALL,200,0.000,0.022494,0.00175,0.014448,-0.00175,0.008046,baseline_florence2
5,unseen,img_blur_20,ALL,200,0.000,0.023639,0.00175,0.014448,-0.00175,0.009191,baseline_florence2
6,unseen,img_blur_50,ALL,200,0.000,0.023589,0.00175,0.014448,-0.00175,0.009141,baseline_florence2
7,unseen,original,ALL,200,0.000,0.050198,0.00175,0.014448,-0.00175,0.035750,baseline_florence2
8,seen,img_black,ALL,200,0.160,0.284155,0.01425,0.034906,0.14575,0.249249,florence2_epoch30
9,seen,img_blur_20,ALL,200,0.165,0.290040,0.01425,0.034906,0.15075,0.255134,florence2_epoch30
10,seen,img_blur_50,ALL,200,0.170,0.295595,0.01425,0.034906,0.15575,0.260689,florence2_epoch30
11,seen,original,ALL,200,0.980,0.982500,0.01425,0.034906,0.96575,0.947594,florence2_epoch30
12,unseen,img_black,ALL,200,0.010,0.059742,0.00175,0.014448,0.00825,0.045294,florence2_epoch30
13,unseen,img_blur_20,ALL,200,0.010,0.055813,0.00175,0.014448,0.00825,0.041366,florence2_epoch30
14,unseen,img_blur_50,ALL,200,0.010,0.054147,0.00175,0.014448,0.00825,0.039699,florence2_epoch30
15,unseen,original,ALL,200,0.120,0.250448,0.00175,0.014448,0.11825,0.236001,florence2_epoch30
16,seen,img_black,ALL,200,0.610,0.659755,0.01425,0.034906,0.59575,0.624850,qwen2b_epoch20_image_only
17,seen,img_blur_20,ALL,200,0.615,0.657999,0.01425,0.034906,0.60075,0.623093,qwen2b_epoch20_image_only
18,seen,img_blur_50,ALL,200,0.615,0.659316,0.01425,0.034906,0.60075,0.624411,qwen2b_epoch20_image_only
19,seen,original,ALL,200,0.960,0.970641,0.01425,0.034906,0.94575,0.935735,qwen2b_epoch20_image_only
20,unseen,img_black,ALL,200,0.010,0.066091,0.00175,0.014448,0.00825,0.051643,qwen2b_epoch20_image_only
21,unseen,img_blur_20,ALL,200,0.010,0.053509,0.00175,0.014448,0.00825,0.039061,qwen2b_epoch20_image_only
22,unseen,img_blur_50,ALL,200,0.010,0.057068,0.00175,0.014448,0.00825,0.042620,qwen2b_epoch20_image_only
23,unseen,original,ALL,200,0.145,0.206895,0.00175,0.014448,0.14325,0.192447,qwen2b_epoch20_image_only
24,seen,img_black__ocr_mask__k_0,ALL,200,0.040,0.128294,0.01425,0.034906,0.02575,0.093389,qwen2b_epoch20_image_ocr
25,seen,img_none__ocr_mask__k_0,ALL,200,0.335,0.402714,0.01425,0.034906,0.32075,0.367809,qwen2b_epoch20_image_ocr
26,unseen,img_black__ocr_mask__k_0,ALL,200,0.005,0.090246,0.00175,0.014448,0.00325,0.075798,qwen2b_epoch20_image_ocr
27,unseen,img_none__ocr_mask__k_0,ALL,200,0.155,0.254990,0.00175,0.014448,0.15325,0.240542,qwen2b_epoch20_image_ocr
28,seen,img_black,ALL,200,0.560,0.629224,0.01425,0.034906,0.54575,0.594318,qwen7b_epoch10_image_only
29,seen,img_blur_20,ALL,200,0.560,0.622589,0.01425,0.034906,0.54575,0.587683,qwen7b_epoch10_image_only
30,seen,img_blur_50,ALL,200,0.565,0.624994,0.01425,0.034906,0.55075,0.590088,qwen7b_epoch10_image_only
31,seen,original,ALL,200,0.895,0.919318,0.01425,0.034906,0.88075,0.884412,qwen7b_epoch10_image_only
32,unseen,img_black,ALL,200,0.025,0.088039,0.00175,0.014448,0.02325,0.073591,qwen7b_epoch10_image_only
33,unseen,img_blur_20,ALL,200,0.025,0.089997,0.00175,0.014448,0.02325,0.075549,qwen7b_epoch10_image_only
34,unseen,img_blur_50,ALL,200,0.025,0.088330,0.00175,0.014448,0.02325,0.073882,qwen7b_epoch10_image_only
35,unseen,original,ALL,200,0.225,0.288220,0.00175,0.014448,0.22325,0.273772,qwen7b_epoch10_image_only

COMET INFO: The process of logging environment details (conda environment, git patch) is underway. Please be patient as this may take some time.
COMET WARNING: Couldn't retrieve and log Google Colab notebook content, reason: 'NoneType' object is not subscriptable
COMET INFO: ---------------------------------------------------------------------------------------
COMET INFO: Comet.ml Experiment Summary
COMET INFO: ---------------------------------------------------------------------------------------
COMET INFO:   Data:
COMET INFO:     display_summary_level : 1
COMET INFO:     name                  : extraction-summary
COMET INFO:     url                   : https://www.comet.com/scfeel/qwen3-1/2a61e0607f8740e99172b52d97fb067f
COMET INFO:   Others:
COMET INFO:     Name         : extraction-summary
COMET INFO:     notebook_url : https://colab.research.google.com/notebook#23_data_extraction-jvsc-7416a373-b093-4a59-b7c3-56b6a99eed15e4640795-6a38-4ef8-a86f-442e6010de1e.ipynb
COMET INFO:   Uploads:
COMET INFO:     asset                    : 2 (5.09 KB)
COMET INFO:     dataframe                : 1 (5.18 KB)
COMET INFO:     environment details      : 1
COMET INFO:     figures                  : 2
COMET INFO:     filename                 : 1
COMET INFO:     git metadata             : 1
COMET INFO:     git-patch (uncompressed) : 1 (68.35 MB)
COMET INFO:     installed packages       : 1
COMET INFO:     notebook                 : 1
COMET INFO:     os packages              : 1
COMET INFO:     source_code              : 1
COMET INFO:
COMET WARNING: To get all data logged automatically, import comet_ml before the following modules: torch, tensorflow, sklearn, keras.

In [10]:
# Saved outputs
saved_csvs = sorted(str(path) for path in EXTRACTION_DIR.glob("*.csv"))
display(pd.DataFrame({"csv_path": saved_csvs}))
print({"csv_count": len(saved_csvs), "output_dir": str(EXTRACTION_DIR)})

                                             csv_path
0   /content/drive/MyDrive/course_work2026/artifac...
1   /content/drive/MyDrive/course_work2026/artifac...
2   /content/drive/MyDrive/course_work2026/artifac...
3   /content/drive/MyDrive/course_work2026/artifac...
4   /content/drive/MyDrive/course_work2026/artifac...
5   /content/drive/MyDrive/course_work2026/artifac...
6   /content/drive/MyDrive/course_work2026/artifac...
7   /content/drive/MyDrive/course_work2026/artifac...
8   /content/drive/MyDrive/course_work2026/artifac...
9   /content/drive/MyDrive/course_work2026/artifac...
10  /content/drive/MyDrive/course_work2026/artifac...
11  /content/drive/MyDrive/course_work2026/artifac...
12  /content/drive/MyDrive/course_work2026/artifac...
13  /content/drive/MyDrive/course_work2026/artifac...
14  /content/drive/MyDrive/course_work2026/artifac...
15  /content/drive/MyDrive/course_work2026/artifac...
16  /content/drive/MyDrive/course_work2026/artifac...
17  /content/drive/MyDrive/course_work2026/artifac...
18  /content/drive/MyDrive/course_work2026/artifac...
19  /content/drive/MyDrive/course_work2026/artifac...
20  /content/drive/MyDrive/course_work2026/artifac...

{'csv_count': 21, 'output_dir': '/content/drive/MyDrive/course_work2026/artifacts/privacy_attacks/extraction'}