In [1]:
# Secrets
import os

In [2]:
# Setup
!git clone https://github.com/sk3feel/hidden-data-reproduction-multimodal.git /content/course_work2026 2>/dev/null || (cd /content/course_work2026 && git pull)
%cd /content/course_work2026
from google.colab import drive
from pathlib import Path
drive.mount("/content/drive")
DRIVE_ROOT = Path("/content/drive/MyDrive/course_work2026")
DRIVE_ROOT.mkdir(parents=True, exist_ok=True)
print({"drive_root": str(DRIVE_ROOT)})
import sys
print({"python_executable": sys.executable})
!pip install -q -r requirements.txt
!pip install -q accelerate Pillow pandas tqdm einops timm comet_ml huggingface_hub
!pip install -q peft bitsandbytes trl qwen-vl-utils
!pip uninstall -y transformers tokenizers
!pip install -q tokenizers==0.21.0
!pip install -q transformers==4.49.0 --force-reinstall --no-deps
!python src/download_from_hf.py --repo-id sk3feel/docvqa-privacy-data

from huggingface_hub import snapshot_download
snapshot_download("sk3feel/docvqa-privacy-checkpoints", local_dir="checkpoints/", repo_type="model", token=os.environ["HF_TOKEN"])

Mounted at /content/drive
{'drive_root': '/content/drive/MyDrive/course_work2026'}
{'python_executable': '/usr/bin/python3'}
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.6/14.6 MB 154.7 MB/s eta 0:00:0000:010:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.3/42.3 kB 4.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 786.2/786.2 kB 63.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 82.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.4/12.4 MB 158.3 MB/s eta 0:00:0000:010:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.8/59.8 kB 7.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.7/76.7 kB 10.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 93.1 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
jupyter-kernel-gateway 2.5.2 requires notebook<7.0,>=5.7.6, but you have notebook 7.5.5 which is incompatible.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 34.7 MB/s eta 0:00:0000:01:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 531.0/531.0 kB 51.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 36.4/36.4 MB 77.1 MB/s eta 0:00:00:00:0100:01
Found existing installation: transformers 5.0.0
Uninstalling transformers-5.0.0:
  Successfully uninstalled transformers-5.0.0
Found existing installation: tokenizers 0.22.2
Uninstalling tokenizers-0.22.2:
  Successfully uninstalled tokenizers-0.22.2
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 109.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 53.5 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
sentence-transformers 5.3.0 requires transformers<6.0.0,>=4.41.0, which is not installed.
peft 0.18.1 requires transformers, which is not installed.
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 4.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 130.7 MB/s eta 0:00:0000:010:01
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 3e062d55-0892-44ff-a3dd-9e11243a9605)')' thrown while requesting HEAD https://huggingface.co/datasets/sk3feel/docvqa-privacy-data/resolve/main/artifacts_bundle.tar.gz
Retrying in 1s [Retry 1/5].
artifacts_bundle.tar.gz: 100% 3.04G/3.04G [00:08<00:00, 353MB/s]
/content/course_work2026/src/download_from_hf.py:29: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=extract_root)
{
  "repo_id": "sk3feel/docvqa-privacy-data",
  "local_dir": "/content/course_work2026/artifacts",
  "archive_filename": "artifacts_bundle.tar.gz",
  "extracted_paths": {
    "benchmark_train": "/content/course_work2026/artifacts/docqa_recovery/benchmark_train",
    "benchmark": "/content/course_work2026/artifacts/docqa_recovery/benchmark",
    "finetuning_generative": "/content/course_work2026/artifacts/finetuning_generative"
  }
}

Fetching 245 files:   0%|          | 0/245 [00:00<?, ?it/s]

preprocessor_config.json:   0%|          | 0.00/630 [00:00<?, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

config.json: 0.00B [00:00, ?B/s]

processor_config.json: 0.00B [00:00, ?B/s]

added_tokens.json: 0.00B [00:00, ?B/s]

.gitattributes: 0.00B [00:00, ?B/s]

florence2/epoch_1/model.safetensors:   0%|          | 0.00/926M [00:00<?, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

generation_config.json:   0%|          | 0.00/292 [00:00<?, ?B/s]

config.json: 0.00B [00:00, ?B/s]

florence2/epoch_1/trainer_state.pt:   0%|          | 0.00/1.08G [00:00<?, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

generation_config.json:   0%|          | 0.00/291 [00:00<?, ?B/s]

florence2/epoch_3/model.safetensors:   0%|          | 0.00/542M [00:00<?, ?B/s]

'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 8386a736-0b95-49cd-83a4-2b160027949c)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/florence2/epoch_1/generation_config.json
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 8386a736-0b95-49cd-83a4-2b160027949c)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/florence2/epoch_1/generation_config.json
Retrying in 1s [Retry 1/5].
WARNING:huggingface_hub.utils._http:Retrying in 1s [Retry 1/5].
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: abb3c4e1-f3a1-4596-a882-77ba8d996337)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/florence2/epoch_15/added_tokens.json
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: abb3c4e1-f3a1-4596-a882-77ba8d996337)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/florence2/epoch_15/added_tokens.json
Retrying in 1s [Retry 1/5].
WARNING:huggingface_hub.utils._http:Retrying in 1s [Retry 1/5].

processor_config.json: 0.00B [00:00, ?B/s]

'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: ec3cea46-89c7-4053-bbaf-aa52a7335ed4)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/florence2/epoch_15/merges.txt
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: ec3cea46-89c7-4053-bbaf-aa52a7335ed4)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/florence2/epoch_15/merges.txt
Retrying in 1s [Retry 1/5].
WARNING:huggingface_hub.utils._http:Retrying in 1s [Retry 1/5].
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: da1c1851-6b5f-4f67-89eb-3e1a2aa3e856)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/florence2/epoch_15/model.safetensors
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: da1c1851-6b5f-4f67-89eb-3e1a2aa3e856)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/florence2/epoch_15/model.safetensors
Retrying in 1s [Retry 1/5].
WARNING:huggingface_hub.utils._http:Retrying in 1s [Retry 1/5].

tokenizer.json: 0.00B [00:00, ?B/s]

'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 628ae18f-f4d1-4dde-bb5a-db70ca1a502a)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/florence2/epoch_15/preprocessor_config.json
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 628ae18f-f4d1-4dde-bb5a-db70ca1a502a)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/florence2/epoch_15/preprocessor_config.json
Retrying in 1s [Retry 1/5].
WARNING:huggingface_hub.utils._http:Retrying in 1s [Retry 1/5].

tokenizer_config.json: 0.00B [00:00, ?B/s]

added_tokens.json: 0.00B [00:00, ?B/s]

florence2/epoch_3/trainer_state.pt:   0%|          | 0.00/1.08G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/292 [00:00<?, ?B/s]

config.json: 0.00B [00:00, ?B/s]

generation_config.json:   0%|          | 0.00/292 [00:00<?, ?B/s]

added_tokens.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

preprocessor_config.json:   0%|          | 0.00/630 [00:00<?, ?B/s]

'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: d900be5b-a332-4c95-b65d-638a246c03de)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/florence2/epoch_3/config.json
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: d900be5b-a332-4c95-b65d-638a246c03de)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/florence2/epoch_3/config.json
Retrying in 1s [Retry 1/5].
WARNING:huggingface_hub.utils._http:Retrying in 1s [Retry 1/5].

special_tokens_map.json: 0.00B [00:00, ?B/s]

preprocessor_config.json:   0%|          | 0.00/630 [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

florence2/epoch_30/model.safetensors:   0%|          | 0.00/926M [00:00<?, ?B/s]

florence2/epoch_15/model.safetensors:   0%|          | 0.00/926M [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

added_tokens.json: 0.00B [00:00, ?B/s]

generation_config.json:   0%|          | 0.00/292 [00:00<?, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

preprocessor_config.json:   0%|          | 0.00/630 [00:00<?, ?B/s]

florence2/epoch_5/model.safetensors:   0%|          | 0.00/926M [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

added_tokens.json: 0.00B [00:00, ?B/s]

config.json: 0.00B [00:00, ?B/s]

generation_config.json:   0%|          | 0.00/292 [00:00<?, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

preprocessor_config.json:   0%|          | 0.00/630 [00:00<?, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

florence2_v2/epoch_10/model.safetensors:   0%|          | 0.00/926M [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

added_tokens.json: 0.00B [00:00, ?B/s]

config.json: 0.00B [00:00, ?B/s]

generation_config.json:   0%|          | 0.00/292 [00:00<?, ?B/s]

preprocessor_config.json:   0%|          | 0.00/630 [00:00<?, ?B/s]

florence2_v2/epoch_3/model.safetensors:   0%|          | 0.00/926M [00:00<?, ?B/s]

'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: f09522ba-4f4e-4746-bfa2-7180deaf43da)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/florence2/epoch_5/config.json
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: f09522ba-4f4e-4746-bfa2-7180deaf43da)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/florence2/epoch_5/config.json
Retrying in 1s [Retry 1/5].
WARNING:huggingface_hub.utils._http:Retrying in 1s [Retry 1/5].
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 6100f0a3-09eb-490d-837a-7ae1085192df)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/florence2/epoch_5/special_tokens_map.json
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 6100f0a3-09eb-490d-837a-7ae1085192df)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/florence2/epoch_5/special_tokens_map.json
Retrying in 1s [Retry 1/5].
WARNING:huggingface_hub.utils._http:Retrying in 1s [Retry 1/5].
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 36ec8c47-171f-492a-b1c4-94f2a12b2b5b)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/florence2/epoch_5/tokenizer.json
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 36ec8c47-171f-492a-b1c4-94f2a12b2b5b)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/florence2/epoch_5/tokenizer.json
Retrying in 1s [Retry 1/5].
WARNING:huggingface_hub.utils._http:Retrying in 1s [Retry 1/5].
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 215900ee-38e8-4e2e-bce6-be0dc45da78d)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/florence2/epoch_3/config.json
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 215900ee-38e8-4e2e-bce6-be0dc45da78d)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/florence2/epoch_3/config.json
Retrying in 2s [Retry 2/5].
WARNING:huggingface_hub.utils._http:Retrying in 2s [Retry 2/5].

config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

config.json: 0.00B [00:00, ?B/s]

'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 45521064-4d9a-4738-a2fd-2edfa73b692e)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/florence2_v2/epoch_3/merges.txt
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 45521064-4d9a-4738-a2fd-2edfa73b692e)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/florence2_v2/epoch_3/merges.txt
Retrying in 1s [Retry 1/5].
WARNING:huggingface_hub.utils._http:Retrying in 1s [Retry 1/5].
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: f1b1c313-78a7-4468-bd20-bbbebb301985)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/florence2_v2/epoch_3/special_tokens_map.json
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: f1b1c313-78a7-4468-bd20-bbbebb301985)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/florence2_v2/epoch_3/special_tokens_map.json
Retrying in 1s [Retry 1/5].
WARNING:huggingface_hub.utils._http:Retrying in 1s [Retry 1/5].

merges.txt: 0.00B [00:00, ?B/s]

preprocessor_config.json:   0%|          | 0.00/630 [00:00<?, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

README.md: 0.00B [00:00, ?B/s]

adapter_config.json:   0%|          | 0.00/979 [00:00<?, ?B/s]

'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 0bc2db98-bbd6-4e62-8466-17695c3d40a6)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/florence2/epoch_5/special_tokens_map.json
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 0bc2db98-bbd6-4e62-8466-17695c3d40a6)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/florence2/epoch_5/special_tokens_map.json
Retrying in 2s [Retry 2/5].
WARNING:huggingface_hub.utils._http:Retrying in 2s [Retry 2/5].

added_tokens.json:   0%|          | 0.00/392 [00:00<?, ?B/s]

qwen2b/epoch_1/adapter_model.safetensors:   0%|          | 0.00/8.73M [00:00<?, ?B/s]

chat_template.jinja: 0.00B [00:00, ?B/s]

'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: cb58cdd9-e325-4063-9a2a-250a147b127f)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/florence2_v2/epoch_5/added_tokens.json

chat_template.json: 0.00B [00:00, ?B/s]

WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: cb58cdd9-e325-4063-9a2a-250a147b127f)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/florence2_v2/epoch_5/added_tokens.json
Retrying in 1s [Retry 1/5].
WARNING:huggingface_hub.utils._http:Retrying in 1s [Retry 1/5].
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 19349ec2-9d1a-4817-99bb-01171bab8b03)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/florence2_v2/epoch_5/config.json
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 19349ec2-9d1a-4817-99bb-01171bab8b03)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/florence2_v2/epoch_5/config.json
Retrying in 1s [Retry 1/5].
WARNING:huggingface_hub.utils._http:Retrying in 1s [Retry 1/5].

merges.txt: 0.00B [00:00, ?B/s]

'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 432a87d5-1304-401a-850a-30a0e2558df6)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/florence2_v2/epoch_5/generation_config.json
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 432a87d5-1304-401a-850a-30a0e2558df6)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/florence2_v2/epoch_5/generation_config.json
Retrying in 1s [Retry 1/5].
WARNING:huggingface_hub.utils._http:Retrying in 1s [Retry 1/5].
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 4aff3117-18e9-4a2f-b8e2-513003fdbdb3)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/florence2_v2/epoch_5/merges.txt
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 4aff3117-18e9-4a2f-b8e2-513003fdbdb3)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/florence2_v2/epoch_5/merges.txt
Retrying in 1s [Retry 1/5].
WARNING:huggingface_hub.utils._http:Retrying in 1s [Retry 1/5].

config.json: 0.00B [00:00, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

added_tokens.json: 0.00B [00:00, ?B/s]

'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 9979e813-d015-4209-8da3-46540adc7e76)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/florence2_v2/epoch_5/model.safetensors
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 9979e813-d015-4209-8da3-46540adc7e76)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/florence2_v2/epoch_5/model.safetensors
Retrying in 1s [Retry 1/5].
WARNING:huggingface_hub.utils._http:Retrying in 1s [Retry 1/5].

tokenizer_config.json: 0.00B [00:00, ?B/s]

qwen2b/epoch_1/tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

README.md: 0.00B [00:00, ?B/s]

adapter_config.json:   0%|          | 0.00/979 [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/392 [00:00<?, ?B/s]

qwen2b/epoch_10/adapter_model.safetensor(…):   0%|          | 0.00/8.73M [00:00<?, ?B/s]

florence2_v2/epoch_5/model.safetensors:   0%|          | 0.00/926M [00:00<?, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

preprocessor_config.json:   0%|          | 0.00/572 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/613 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

README.md: 0.00B [00:00, ?B/s]

adapter_config.json:   0%|          | 0.00/979 [00:00<?, ?B/s]

qwen2b/epoch_20/adapter_model.safetensor(…):   0%|          | 0.00/8.73M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/392 [00:00<?, ?B/s]

chat_template.json: 0.00B [00:00, ?B/s]

'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: e2d62722-df68-43b0-ad00-6c7bda4ad4dd)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen2b/epoch_1/preprocessor_config.json
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: e2d62722-df68-43b0-ad00-6c7bda4ad4dd)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen2b/epoch_1/preprocessor_config.json
Retrying in 1s [Retry 1/5].
WARNING:huggingface_hub.utils._http:Retrying in 1s [Retry 1/5].
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 5e78d2ac-32e4-4bf7-95ea-7a43491fa181)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen2b/epoch_1/processor_config.json
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 5e78d2ac-32e4-4bf7-95ea-7a43491fa181)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen2b/epoch_1/processor_config.json
Retrying in 1s [Retry 1/5].
WARNING:huggingface_hub.utils._http:Retrying in 1s [Retry 1/5].

preprocessor_config.json:   0%|          | 0.00/572 [00:00<?, ?B/s]

'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: b92e650b-0ae6-426a-929e-2acb560a2cb0)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen2b/epoch_1/special_tokens_map.json
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: b92e650b-0ae6-426a-929e-2acb560a2cb0)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen2b/epoch_1/special_tokens_map.json
Retrying in 1s [Retry 1/5].
WARNING:huggingface_hub.utils._http:Retrying in 1s [Retry 1/5].

preprocessor_config.json:   0%|          | 0.00/572 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/613 [00:00<?, ?B/s]

'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: f35ce049-532e-46ef-af8c-407134c6132a)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen2b/epoch_1/vocab.json
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: f35ce049-532e-46ef-af8c-407134c6132a)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen2b/epoch_1/vocab.json
Retrying in 1s [Retry 1/5].
WARNING:huggingface_hub.utils._http:Retrying in 1s [Retry 1/5].
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: b4f3a4a6-2072-4dba-a762-bc63f83b23e0)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/florence2_v2/epoch_5/generation_config.json
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: b4f3a4a6-2072-4dba-a762-bc63f83b23e0)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/florence2_v2/epoch_5/generation_config.json
Retrying in 2s [Retry 2/5].
WARNING:huggingface_hub.utils._http:Retrying in 2s [Retry 2/5].

qwen2b/epoch_20/tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 6ae16e42-ad52-4c91-ae2e-26a25f00ffd1)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen2b/epoch_10/chat_template.json
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 6ae16e42-ad52-4c91-ae2e-26a25f00ffd1)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen2b/epoch_10/chat_template.json
Retrying in 1s [Retry 1/5].
WARNING:huggingface_hub.utils._http:Retrying in 1s [Retry 1/5].

vocab.json: 0.00B [00:00, ?B/s]

generation_config.json:   0%|          | 0.00/292 [00:00<?, ?B/s]

'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 4e60a11e-c23f-429c-b228-bdc4bc457fa5)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen2b/epoch_10/tokenizer.json
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 4e60a11e-c23f-429c-b228-bdc4bc457fa5)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen2b/epoch_10/tokenizer.json
Retrying in 1s [Retry 1/5].
WARNING:huggingface_hub.utils._http:Retrying in 1s [Retry 1/5].

chat_template.json: 0.00B [00:00, ?B/s]

adapter_config.json:   0%|          | 0.00/979 [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/392 [00:00<?, ?B/s]

qwen2b/epoch_3/adapter_model.safetensors:   0%|          | 0.00/8.73M [00:00<?, ?B/s]

qwen2b/epoch_10/tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 5f5ef948-59ab-4618-9b57-7c3680e9a668)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen2b/epoch_20/merges.txt
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 5f5ef948-59ab-4618-9b57-7c3680e9a668)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen2b/epoch_20/merges.txt
Retrying in 1s [Retry 1/5].
WARNING:huggingface_hub.utils._http:Retrying in 1s [Retry 1/5].

merges.txt: 0.00B [00:00, ?B/s]

preprocessor_config.json:   0%|          | 0.00/572 [00:00<?, ?B/s]

processor_config.json: 0.00B [00:00, ?B/s]

'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 1ee878ed-d020-4a1b-9334-8fc89eb39faa)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen2b/epoch_1/processor_config.json
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 1ee878ed-d020-4a1b-9334-8fc89eb39faa)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen2b/epoch_1/processor_config.json
Retrying in 2s [Retry 2/5].
WARNING:huggingface_hub.utils._http:Retrying in 2s [Retry 2/5].
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: db6a781c-b825-444a-9cb7-2d75345215ea)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen2b/epoch_1/special_tokens_map.json
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: db6a781c-b825-444a-9cb7-2d75345215ea)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen2b/epoch_1/special_tokens_map.json
Retrying in 2s [Retry 2/5].
WARNING:huggingface_hub.utils._http:Retrying in 2s [Retry 2/5].
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 470414b6-ecb9-4090-bb47-d41734bde446)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen2b/epoch_1/vocab.json
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 470414b6-ecb9-4090-bb47-d41734bde446)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen2b/epoch_1/vocab.json
Retrying in 2s [Retry 2/5].
WARNING:huggingface_hub.utils._http:Retrying in 2s [Retry 2/5].
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 7ce90526-0b80-4077-b797-506aa710d08b)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen2b/epoch_3/README.md
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 7ce90526-0b80-4077-b797-506aa710d08b)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen2b/epoch_3/README.md
Retrying in 1s [Retry 1/5].
WARNING:huggingface_hub.utils._http:Retrying in 1s [Retry 1/5].

processor_config.json: 0.00B [00:00, ?B/s]

qwen2b/epoch_3/tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 8d3d553a-7061-46bc-be74-aa4e856069b9)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen2b/epoch_3/chat_template.jinja
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 8d3d553a-7061-46bc-be74-aa4e856069b9)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen2b/epoch_3/chat_template.jinja
Retrying in 1s [Retry 1/5].
WARNING:huggingface_hub.utils._http:Retrying in 1s [Retry 1/5].

special_tokens_map.json:   0%|          | 0.00/613 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

README.md: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

adapter_config.json:   0%|          | 0.00/979 [00:00<?, ?B/s]

'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 411630dd-cdfa-4598-b360-90dc0e7e2209)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen2b/epoch_3/chat_template.json
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 411630dd-cdfa-4598-b360-90dc0e7e2209)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen2b/epoch_3/chat_template.json
Retrying in 1s [Retry 1/5].
WARNING:huggingface_hub.utils._http:Retrying in 1s [Retry 1/5].

added_tokens.json:   0%|          | 0.00/392 [00:00<?, ?B/s]

chat_template.jinja: 0.00B [00:00, ?B/s]

qwen2b/epoch_5/adapter_model.safetensors:   0%|          | 0.00/8.73M [00:00<?, ?B/s]

chat_template.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

chat_template.jinja: 0.00B [00:00, ?B/s]

processor_config.json: 0.00B [00:00, ?B/s]

'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 0ff3498e-dc06-4766-b01b-eccdbe7c01fe)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen2b/epoch_3/merges.txt
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 0ff3498e-dc06-4766-b01b-eccdbe7c01fe)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen2b/epoch_3/merges.txt
Retrying in 1s [Retry 1/5].
WARNING:huggingface_hub.utils._http:Retrying in 1s [Retry 1/5].

special_tokens_map.json:   0%|          | 0.00/613 [00:00<?, ?B/s]

preprocessor_config.json:   0%|          | 0.00/572 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

qwen2b/epoch_5/tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

chat_template.json: 0.00B [00:00, ?B/s]

README.md: 0.00B [00:00, ?B/s]

adapter_config.json:   0%|          | 0.00/979 [00:00<?, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

qwen2b_v2/epoch_10/adapter_model.safeten(…):   0%|          | 0.00/8.73M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/613 [00:00<?, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

qwen2b_v2/epoch_10/tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

README.md: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/392 [00:00<?, ?B/s]

chat_template.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

preprocessor_config.json:   0%|          | 0.00/572 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/613 [00:00<?, ?B/s]

qwen2b_v2/epoch_3/tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: c7c31ffc-4ddb-4c01-8d34-7d648b484d43)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen2b/epoch_3/special_tokens_map.json
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: c7c31ffc-4ddb-4c01-8d34-7d648b484d43)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen2b/epoch_3/special_tokens_map.json
Retrying in 1s [Retry 1/5].
WARNING:huggingface_hub.utils._http:Retrying in 1s [Retry 1/5].

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/613 [00:00<?, ?B/s]

adapter_config.json:   0%|          | 0.00/979 [00:00<?, ?B/s]

qwen2b_v2/epoch_5/adapter_model.safetens(…):   0%|          | 0.00/8.73M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/392 [00:00<?, ?B/s]

chat_template.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

preprocessor_config.json:   0%|          | 0.00/572 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/613 [00:00<?, ?B/s]

'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: c6095b42-8bdc-47c7-8812-138c7a6263f2)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen2b/epoch_3/tokenizer_config.json
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: c6095b42-8bdc-47c7-8812-138c7a6263f2)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen2b/epoch_3/tokenizer_config.json
Retrying in 1s [Retry 1/5].
WARNING:huggingface_hub.utils._http:Retrying in 1s [Retry 1/5].

qwen2b_v2/epoch_5/tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

README.md: 0.00B [00:00, ?B/s]

qwen7b/epoch_10/adapter_model.safetensor(…):   0%|          | 0.00/20.2M [00:00<?, ?B/s]

'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: d0fc168f-c882-48d3-903c-adb665497fc9)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen2b_v2/epoch_10/added_tokens.json
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: d0fc168f-c882-48d3-903c-adb665497fc9)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen2b_v2/epoch_10/added_tokens.json
Retrying in 1s [Retry 1/5].
WARNING:huggingface_hub.utils._http:Retrying in 1s [Retry 1/5].
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 1f33a318-fd60-474c-b89c-95749c3cbb30)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen2b_v2/epoch_10/chat_template.json
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 1f33a318-fd60-474c-b89c-95749c3cbb30)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen2b_v2/epoch_10/chat_template.json
Retrying in 1s [Retry 1/5].
WARNING:huggingface_hub.utils._http:Retrying in 1s [Retry 1/5].
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 736c8854-1afb-4604-9f20-2f92474ed5c8)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen2b_v2/epoch_10/preprocessor_config.json
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 736c8854-1afb-4604-9f20-2f92474ed5c8)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen2b_v2/epoch_10/preprocessor_config.json
Retrying in 1s [Retry 1/5].
WARNING:huggingface_hub.utils._http:Retrying in 1s [Retry 1/5].

added_tokens.json:   0%|          | 0.00/392 [00:00<?, ?B/s]

chat_template.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/392 [00:00<?, ?B/s]

'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 233adcd0-89be-4601-a673-3f4541601cf9)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen2b_v2/epoch_3/adapter_config.json
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 233adcd0-89be-4601-a673-3f4541601cf9)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen2b_v2/epoch_3/adapter_config.json
Retrying in 1s [Retry 1/5].
WARNING:huggingface_hub.utils._http:Retrying in 1s [Retry 1/5].
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 03b80d93-4e9d-4295-affc-22695e571b4b)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen2b_v2/epoch_3/adapter_model.safetensors
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 03b80d93-4e9d-4295-affc-22695e571b4b)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen2b_v2/epoch_3/adapter_model.safetensors
Retrying in 1s [Retry 1/5].
WARNING:huggingface_hub.utils._http:Retrying in 1s [Retry 1/5].

preprocessor_config.json:   0%|          | 0.00/572 [00:00<?, ?B/s]

preprocessor_config.json:   0%|          | 0.00/572 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

qwen7b/epoch_10/tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

adapter_config.json:   0%|          | 0.00/979 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

adapter_config.json:   0%|          | 0.00/979 [00:00<?, ?B/s]

processor_config.json: 0.00B [00:00, ?B/s]

qwen7b/epoch_2/adapter_model.safetensors:   0%|          | 0.00/20.2M [00:00<?, ?B/s]

chat_template.jinja: 0.00B [00:00, ?B/s]

qwen2b_v2/epoch_3/adapter_model.safetens(…):   0%|          | 0.00/8.73M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/731 [00:00<?, ?B/s]

qwen7b/epoch_2/tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

adapter_config.json:   0%|          | 0.00/979 [00:00<?, ?B/s]

chat_template.jinja: 0.00B [00:00, ?B/s]

processor_config.json: 0.00B [00:00, ?B/s]

qwen7b/epoch_3/adapter_model.safetensors:   0%|          | 0.00/20.2M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/731 [00:00<?, ?B/s]

'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 0f74a830-bb90-4b7e-8d6d-6dac8285a396)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen2b_v2/epoch_5/README.md
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 0f74a830-bb90-4b7e-8d6d-6dac8285a396)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen2b_v2/epoch_5/README.md
Retrying in 1s [Retry 1/5].
WARNING:huggingface_hub.utils._http:Retrying in 1s [Retry 1/5].

qwen7b/epoch_3/tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

adapter_config.json:   0%|          | 0.00/979 [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/392 [00:00<?, ?B/s]

qwen7b/epoch_5/adapter_model.safetensors:   0%|          | 0.00/20.2M [00:00<?, ?B/s]

chat_template.jinja: 0.00B [00:00, ?B/s]

chat_template.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

preprocessor_config.json:   0%|          | 0.00/572 [00:00<?, ?B/s]

processor_config.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/613 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

qwen7b/epoch_5/tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

README.md: 0.00B [00:00, ?B/s]

adapter_config.json:   0%|          | 0.00/979 [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/392 [00:00<?, ?B/s]

chat_template.json: 0.00B [00:00, ?B/s]

qwen7b_v2/epoch_10/adapter_model.safeten(…):   0%|          | 0.00/20.2M [00:00<?, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/613 [00:00<?, ?B/s]

preprocessor_config.json:   0%|          | 0.00/572 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

README.md: 0.00B [00:00, ?B/s]

adapter_config.json:   0%|          | 0.00/979 [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/392 [00:00<?, ?B/s]

chat_template.json: 0.00B [00:00, ?B/s]

'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 65c4798c-6fd0-4227-b88d-03809d27ea04)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen7b/epoch_10/adapter_config.json
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 65c4798c-6fd0-4227-b88d-03809d27ea04)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen7b/epoch_10/adapter_config.json
Retrying in 1s [Retry 1/5].
WARNING:huggingface_hub.utils._http:Retrying in 1s [Retry 1/5].

adapter_config.json:   0%|          | 0.00/979 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/613 [00:00<?, ?B/s]

'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: adca8af0-7276-4067-91d8-58060024e246)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen2b_v2/epoch_10/chat_template.json
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: adca8af0-7276-4067-91d8-58060024e246)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen2b_v2/epoch_10/chat_template.json
Retrying in 2s [Retry 2/5].
WARNING:huggingface_hub.utils._http:Retrying in 2s [Retry 2/5].
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 3b322b60-2cc4-4900-89bb-5650f4d7de8b)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen7b/epoch_10/special_tokens_map.json
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 3b322b60-2cc4-4900-89bb-5650f4d7de8b)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen7b/epoch_10/special_tokens_map.json
Retrying in 1s [Retry 1/5].
WARNING:huggingface_hub.utils._http:Retrying in 1s [Retry 1/5].

qwen7b_v2/epoch_3/tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

README.md: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/613 [00:00<?, ?B/s]

adapter_config.json:   0%|          | 0.00/979 [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/392 [00:00<?, ?B/s]

qwen7b_v2/epoch_5/adapter_model.safetens(…):   0%|          | 0.00/20.2M [00:00<?, ?B/s]

chat_template.json: 0.00B [00:00, ?B/s]

chat_template.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

preprocessor_config.json:   0%|          | 0.00/572 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/613 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

qwen7b_v2/epoch_5/tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 128f15e3-add3-450d-8657-1d938fa78555)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen7b/epoch_5/tokenizer_config.json
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 128f15e3-add3-450d-8657-1d938fa78555)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen7b/epoch_5/tokenizer_config.json
Retrying in 1s [Retry 1/5].
WARNING:huggingface_hub.utils._http:Retrying in 1s [Retry 1/5].
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 05f724ae-6004-4637-ad78-e2b5f7d0853c)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen7b_v2/epoch_10/tokenizer.json
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 05f724ae-6004-4637-ad78-e2b5f7d0853c)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen7b_v2/epoch_10/tokenizer.json
Retrying in 1s [Retry 1/5].
WARNING:huggingface_hub.utils._http:Retrying in 1s [Retry 1/5].

tokenizer_config.json: 0.00B [00:00, ?B/s]

'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: fec0aecf-c42a-4720-8ae4-acfd24496ecb)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen7b_v2/epoch_3/adapter_model.safetensors
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: fec0aecf-c42a-4720-8ae4-acfd24496ecb)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen7b_v2/epoch_3/adapter_model.safetensors
Retrying in 1s [Retry 1/5].
WARNING:huggingface_hub.utils._http:Retrying in 1s [Retry 1/5].
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 0e5e8cab-46da-43f3-9fcc-48cb24ea18a6)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen7b_v2/epoch_3/merges.txt
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 0e5e8cab-46da-43f3-9fcc-48cb24ea18a6)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen7b_v2/epoch_3/merges.txt
Retrying in 1s [Retry 1/5].
WARNING:huggingface_hub.utils._http:Retrying in 1s [Retry 1/5].
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 5cec9f92-f237-4b29-96bb-55203da18454)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen7b_v2/epoch_3/preprocessor_config.json
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 5cec9f92-f237-4b29-96bb-55203da18454)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen7b_v2/epoch_3/preprocessor_config.json
Retrying in 1s [Retry 1/5].
WARNING:huggingface_hub.utils._http:Retrying in 1s [Retry 1/5].

qwen7b_v2/epoch_10/tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

preprocessor_config.json:   0%|          | 0.00/572 [00:00<?, ?B/s]

'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: ca400c8d-9032-43a6-b2cf-e90713f69a71)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen7b_v2/epoch_3/adapter_model.safetensors
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: ca400c8d-9032-43a6-b2cf-e90713f69a71)')' thrown while requesting HEAD https://huggingface.co/sk3feel/docvqa-privacy-checkpoints/resolve/8ec365fb58d960752357e91647a1aa333368124e/qwen7b_v2/epoch_3/adapter_model.safetensors
Retrying in 2s [Retry 2/5].
WARNING:huggingface_hub.utils._http:Retrying in 2s [Retry 2/5].

qwen7b_v2/epoch_3/adapter_model.safetens(…):   0%|          | 0.00/20.2M [00:00<?, ?B/s]

'/content/course_work2026/checkpoints'

In [3]:
# Utilities and config
import gc, json, os, re, sys, torch, pandas as pd
from pathlib import Path
from collections import defaultdict
from PIL import Image, ImageFile
from transformers import AutoModelForCausalLM, AutoProcessor, Qwen2VLForConditionalGeneration, BitsAndBytesConfig
from peft import PeftModel
from tqdm.auto import tqdm
from qwen_vl_utils import process_vision_info
import comet_ml
import matplotlib.pyplot as plt
import seaborn as sns


sys.path.append(str(Path.cwd() / "src"))

from src.docqa_metrics import best_metric_over_answers, build_answer_pool, estimate_random_baseline
from src.inference_scenarios import generate_scenario_image, generate_scenario_ocr

import transformers
print(f"transformers version: {transformers.__version__}")
if not transformers.__version__.startswith("4.4"):
    print(f"WARNING: expected 4.4x.x, got {transformers.__version__}. Florence-2 may fail.")

ImageFile.LOAD_TRUNCATED_IMAGES = True
MAX_IMAGE_SIDE = 1024
LOCAL_ARTIFACTS_ROOT = Path("artifacts")
DRIVE_ARTIFACTS_ROOT = DRIVE_ROOT / 'artifacts_v2_controlled'
DRIVE_ARTIFACTS_ROOT.mkdir(parents=True, exist_ok=True)
FINETUNING_DIR = DRIVE_ARTIFACTS_ROOT / "finetuning_generative"
FINETUNING_DIR.mkdir(parents=True, exist_ok=True)
EXTRACTION_DIR = DRIVE_ARTIFACTS_ROOT / "privacy_attacks" / "extraction"
EXTRACTION_DIR.mkdir(parents=True, exist_ok=True)
SUCCESS_PREVIEW_DIR = EXTRACTION_DIR / "success_previews"
SUCCESS_PREVIEW_DIR.mkdir(parents=True, exist_ok=True)

FLORENCE_SCENARIOS = ["original", "img_black", "img_blur_20", "img_blur_50"]
QWEN_IMAGE_ONLY_SCENARIOS = ["original", "img_black", "img_blur_20", "img_blur_50"]
QWEN_IMAGE_OCR_SCENARIOS = ["img_black__ocr_mask__k_0", "img_none__ocr_mask__k_0"]
QWEN_OCR_SCENARIO_MAP = {
    "img_black__ocr_mask__k_0": "ocr_mask__img_black__k_0",
    "img_none__ocr_mask__k_0": "ocr_mask__img_none__k_0",
}


def save_csv_with_comet(df, path, experiment, table_name=None):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(path, index=False)
    csv_string = df.to_csv(index=False)
    experiment.log_asset(str(path), file_name=path.name)
    experiment.log_asset_data(csv_string, file_name=path.name)
    if table_name is not None:
        experiment.log_table(table_name, df)
    return path


def safe_open_image(path, max_side=MAX_IMAGE_SIDE):
    image = Image.open(path).convert("RGB")
    if max(image.size) > max_side:
        image.thumbnail((max_side, max_side), Image.LANCZOS)
    return image


def resize_generated_image(image, max_side=MAX_IMAGE_SIDE):
    image = image.convert("RGB")
    if max(image.size) > max_side:
        image.thumbnail((max_side, max_side), Image.LANCZOS)
    return image


def load_jsonl(path):
    rows = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            if line.strip():
                rows.append(json.loads(line))
    return rows


def enrich_with_field_types(records, manifest_path):
    manifest = []
    with open(manifest_path, "r", encoding="utf-8") as f:
        for line in f:
            if line.strip():
                manifest.append(json.loads(line))
    type_map = {}
    for row in manifest:
        eid = str(row.get("example_id", row.get("question_id", "")))
        type_map[eid] = row.get("coarse_field_type", "OTHER")
    for rec in records:
        rec["coarse_field_type"] = type_map.get(rec["example_id"], "OTHER")
    return records


def stratified_sample(records, n, type_key="coarse_field_type"):
    by_type = defaultdict(list)
    for rec in records:
        by_type[rec[type_key]].append(rec)
    types = sorted(by_type.keys())
    if not types:
        return []
    base = n // len(types)
    remainder = n % len(types)
    target_counts = {ft: base + (1 if idx < remainder else 0) for idx, ft in enumerate(types)}
    result = []
    used = set()
    for ft in types:
        selected = by_type[ft][:target_counts[ft]]
        result.extend(selected)
        used.update(rec["example_id"] for rec in selected)
    if len(result) < n:
        for rec in records:
            if len(result) >= n:
                break
            if rec["example_id"] not in used:
                result.append(rec)
                used.add(rec["example_id"])
    return result[:n]


def normalize_text(text):
    text = str(text or "")
    text = re.sub(r"<[^>]+>", " ", text)
    text = " ".join(text.replace("\n", " ").split()).strip()
    return text


def normalize_em(text):
    text = str(text or "").lower().strip()
    text = re.sub(r"[^\w\s]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text


def qwen_user_text(question, ocr_text=None):
    if ocr_text is None:
        return f"Answer the question about this document image. Give only the answer value, nothing else.\nQuestion: {question}"
    return (
        "Answer the question about this document image using the OCR text provided. "
        "Give only the answer value, nothing else.\n"
        f"OCR: {ocr_text}\nQuestion: {question}"
    )


def load_florence(checkpoint_path=None):
    model_name = str(checkpoint_path) if checkpoint_path is not None else "microsoft/Florence-2-base"
    model = AutoModelForCausalLM.from_pretrained(model_name, trust_remote_code=True).to("cuda")
    model.eval()
    processor = AutoProcessor.from_pretrained(model_name, trust_remote_code=True)
    return model, processor


def load_qwen(base_model_name, adapter_path=None):
    bnb = BitsAndBytesConfig(load_in_4bit=True, bnb_4bit_compute_dtype=torch.bfloat16, bnb_4bit_quant_type="nf4")
    base = Qwen2VLForConditionalGeneration.from_pretrained(base_model_name, quantization_config=bnb, device_map="auto", trust_remote_code=True)
    if adapter_path is not None:
        model = PeftModel.from_pretrained(base, str(adapter_path))
    else:
        model = base
    model.eval()
    processor = AutoProcessor.from_pretrained(base_model_name, trust_remote_code=True)
    return model, processor


def generate_prediction_florence(model, processor, image, question):
    inputs = processor(text=f"<VQA>{question}", images=image, return_tensors="pt").to(model.device)
    generate_inputs = {"input_ids": inputs["input_ids"], "pixel_values": inputs["pixel_values"]}
    with torch.no_grad():
        gen = model.generate(**generate_inputs, max_new_tokens=50)
    return normalize_text(processor.batch_decode(gen, skip_special_tokens=True)[0])


def generate_prediction_qwen(model, processor, image, question, ocr_text=None):
    messages = [{"role": "user", "content": [
        {"type": "image", "image": image},
        {"type": "text", "text": qwen_user_text(question, ocr_text=ocr_text)},
    ]}]
    text = processor.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    img_inputs, _ = process_vision_info(messages)
    img_input = img_inputs[0] if isinstance(img_inputs, list) else img_inputs
    inputs = processor(text=[text], images=[img_input], return_tensors="pt", padding=True)
    device = next(model.parameters()).device
    inputs = {k: v.to(device) if isinstance(v, torch.Tensor) else v for k, v in inputs.items()}
    with torch.no_grad():
        gen = model.generate(**inputs, max_new_tokens=50)
    pred = processor.batch_decode(gen[:, inputs["input_ids"].shape[1]:], skip_special_tokens=True)[0].strip()
    return normalize_text(pred)


def run_extraction(model, processor, records, scenarios, model_kind, mode):
    rows = []
    for rec in tqdm(records, desc=f"extraction:{model_kind}:{mode}"):
        for scenario in scenarios:
            internal_scenario = QWEN_OCR_SCENARIO_MAP.get(scenario, scenario)
            image = resize_generated_image(generate_scenario_image(rec, internal_scenario))
            ocr_text = generate_scenario_ocr(rec, internal_scenario) if mode == "image_ocr" else None

            if model_kind == "florence":
                prediction = generate_prediction_florence(model, processor, image, rec["question"])
            else:
                prediction = generate_prediction_qwen(model, processor, image, rec["question"], ocr_text=ocr_text)

            rows.append({
                "example_id": rec["example_id"],
                "split": rec["split"],
                "scenario": scenario,
                "prediction": prediction,
                "question": rec["question"],
                "answer": rec["answer"],
                "answers": list(rec.get("answers") or [rec["answer"]]),
                "coarse_type": rec["coarse_field_type"],
                "ocr_text_used": ocr_text or "",
                "ocr_source": "generate_scenario_ocr" if mode == "image_ocr" else "",
            })
    return pd.DataFrame(rows)


def score_predictions(predictions_df, answer_pools):
    rows = []
    for row in predictions_df.to_dict(orient="records"):
        answers = row["answers"]
        random_record = {
            "example_id": row["example_id"],
            "coarse_field_type": row["coarse_type"],
            "answers": answers,
            "answer": row["answer"],
            "local_row_id": 0,
        }
        exact_match, token_f1 = best_metric_over_answers(row["prediction"], answers)
        random_em, random_f1 = estimate_random_baseline(random_record, answer_pools[row["split"]])
        rows.append({
            **row,
            "exact_match": exact_match,
            "token_f1": token_f1,
            "random_em": random_em,
            "random_f1": random_f1,
            "corrected_em": exact_match - random_em,
            "corrected_f1": token_f1 - random_f1,
            "normalized_prediction": normalize_em(row["prediction"]),
            "normalized_answer": normalize_em(row["answer"]),
        })
    return pd.DataFrame(rows)


def compute_metrics(scored_df):
    rows = []
    for (split, scenario, coarse_type), group in scored_df.groupby(["split", "scenario", "coarse_type"]):
        rows.append({
            "split": split,
            "scenario": scenario,
            "coarse_type": coarse_type,
            "n_examples": len(group),
            "exact_match": float(group["exact_match"].mean()),
            "token_f1": float(group["token_f1"].mean()),
            "random_em": float(group["random_em"].mean()),
            "random_f1": float(group["random_f1"].mean()),
            "corrected_em": float(group["corrected_em"].mean()),
            "corrected_f1": float(group["corrected_f1"].mean()),
        })
    overall_rows = []
    for (split, scenario), group in scored_df.groupby(["split", "scenario"]):
        overall_rows.append({
            "split": split,
            "scenario": scenario,
            "coarse_type": "ALL",
            "n_examples": len(group),
            "exact_match": float(group["exact_match"].mean()),
            "token_f1": float(group["token_f1"].mean()),
            "random_em": float(group["random_em"].mean()),
            "random_f1": float(group["random_f1"].mean()),
            "corrected_em": float(group["corrected_em"].mean()),
            "corrected_f1": float(group["corrected_f1"].mean()),
        })
    return pd.DataFrame(rows + overall_rows).sort_values(["split", "scenario", "coarse_type"]).reset_index(drop=True)


def run_model_extraction_experiment(model, processor, model_tag, model_kind, mode, scenarios, seen_records, unseen_records, answer_pools, experiment_name):
    experiment = comet_ml.Experiment(api_key=os.environ["COMET_API_KEY"], workspace="scfeel", project_name="qwen3-1")
    experiment.set_name(experiment_name)
    experiment.log_parameters({
        "model_tag": model_tag,
        "mode": mode,
        "scenarios": scenarios,
        "n_seen": len(seen_records),
        "n_unseen": len(unseen_records),
    })

    combined_records = seen_records + unseen_records
    record_lookup = {(str(rec["example_id"]), rec["split"]): rec for rec in combined_records}
    predictions_df = run_extraction(model, processor, combined_records, scenarios, model_kind=model_kind, mode=mode)
    scored_df = score_predictions(predictions_df, answer_pools)
    metrics_df = compute_metrics(scored_df)
    success_df = scored_df[(scored_df["split"] == "seen") & (scored_df["scenario"] != "original") & (scored_df["exact_match"] >= 1.0)].head(20).copy()

    prefix = f"{model_tag}_{mode}"
    predictions_path = EXTRACTION_DIR / f"{prefix}_predictions.csv"
    scored_path = EXTRACTION_DIR / f"{prefix}_scored.csv"
    metrics_path = EXTRACTION_DIR / f"{prefix}_metrics.csv"
    success_path = EXTRACTION_DIR / f"{prefix}_successful_examples.csv"
    save_csv_with_comet(predictions_df, predictions_path, experiment)
    save_csv_with_comet(scored_df, scored_path, experiment)
    save_csv_with_comet(metrics_df, metrics_path, experiment, table_name=metrics_path.name)
    save_csv_with_comet(success_df, success_path, experiment, table_name=success_path.name)

    for _, row in metrics_df[metrics_df["coarse_type"] == "ALL"].iterrows():
        metric_name = f"{row['split']}_{row['scenario']}_corrected_em".replace("+", "__").replace("-", "_")
        experiment.log_metric(metric_name, float(row["corrected_em"]))

    if not success_df.empty:
        preview_dir = SUCCESS_PREVIEW_DIR / prefix
        preview_dir.mkdir(parents=True, exist_ok=True)
        for idx, row in success_df.head(5).reset_index(drop=True).iterrows():
            record = record_lookup.get((str(row["example_id"]), row["split"]))
            if record is None:
                continue
            internal_scenario = QWEN_OCR_SCENARIO_MAP.get(row["scenario"], row["scenario"])
            preview_image = resize_generated_image(generate_scenario_image(record, internal_scenario))
            preview_path = preview_dir / f"{idx}_{row['example_id']}_{row['scenario']}.png"
            preview_image.save(preview_path)
            experiment.log_image(str(preview_path), name=preview_path.name)

    experiment.end()
    return predictions_df, scored_df, metrics_df, success_df


def cleanup_gpu():
    gc.collect()
    torch.cuda.empty_cache()

transformers version: 4.49.0

In [4]:
# Data preparation
local_common_train_ids_path = Path('artifacts/finetuning_generative/common_train_200_ids.csv')
common_train_ids_path = FINETUNING_DIR / 'common_train_200_ids.csv'
common_unseen_ids_path = FINETUNING_DIR / 'common_unseen_200_ids.csv'

train_manifest = load_jsonl('artifacts/docqa_recovery/benchmark_train/manifest.jsonl')
validation_manifest = load_jsonl('artifacts/docqa_recovery/benchmark/manifest.jsonl')

def manifest_to_record(row, split, image_root):
    eid = str(row.get('example_id', row.get('question_id', '')))
    image_name = str(row.get('image_path', '')).replace('\\', '/').split('/')[-1]
    answer_value = row['answers'][0] if isinstance(row.get('answers'), list) and row.get('answers') else row.get('answer', '')
    record = dict(row)
    record['example_id'] = eid
    record['split'] = split
    record['image_path'] = str(Path(image_root) / image_name)
    record['answer'] = answer_value
    record['coarse_field_type'] = row.get('coarse_field_type', 'OTHER')
    return record

train_records_full = [manifest_to_record(r, 'seen', 'artifacts/docqa_recovery/benchmark_train/images/original') for r in train_manifest]
validation_records_full = [manifest_to_record(r, 'unseen', 'artifacts/docqa_recovery/benchmark/images/original') for r in validation_manifest]

if common_train_ids_path.exists():
    common_train_ids = pd.read_csv(common_train_ids_path)['example_id'].astype(str).tolist()
elif local_common_train_ids_path.exists():
    common_train_ids = pd.read_csv(local_common_train_ids_path)['example_id'].astype(str).tolist()
    pd.DataFrame({'example_id': common_train_ids}).to_csv(common_train_ids_path, index=False)
else:
    common_train_ids = [r['example_id'] for r in stratified_sample(train_records_full, 200)]
    pd.DataFrame({'example_id': common_train_ids}).to_csv(common_train_ids_path, index=False)

if common_unseen_ids_path.exists():
    common_unseen_ids = pd.read_csv(common_unseen_ids_path)['example_id'].astype(str).tolist()
else:
    common_unseen_ids = [r['example_id'] for r in stratified_sample(validation_records_full, 200)]
    pd.DataFrame({'example_id': common_unseen_ids}).to_csv(common_unseen_ids_path, index=False)

train_map = {r['example_id']: r for r in train_records_full}
val_map = {r['example_id']: r for r in validation_records_full}
common_seen = [train_map[eid] for eid in common_train_ids if eid in train_map]
unseen_200 = [val_map[eid] for eid in common_unseen_ids if eid in val_map]
qwen_seen = common_seen
florence_seen = common_seen
florence_answer_pools = {'seen': build_answer_pool(florence_seen), 'unseen': build_answer_pool(unseen_200)}
qwen_answer_pools = {'seen': build_answer_pool(qwen_seen), 'unseen': build_answer_pool(unseen_200)}
print({'common_seen': len(common_seen), 'unseen_200': len(unseen_200)})

{'common_seen': 200, 'unseen_200': 200}

In [5]:
# Baseline Florence extraction
model, processor = load_florence()
baseline_outputs = run_model_extraction_experiment(
    model=model,
    processor=processor,
    model_tag="baseline_florence2",
    model_kind="florence",
    mode="image_only",
    scenarios=FLORENCE_SCENARIOS,
    seen_records=florence_seen,
    unseen_records=unseen_200,
    answer_pools=florence_answer_pools,
    experiment_name="extraction-baseline-florence2-v2",
)
display(baseline_outputs[2])
del model, processor
cleanup_gpu()

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:104: UserWarning:
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
You are not authenticated with the Hugging Face Hub in this notebook.
If the error persists, please let us know by opening an issue on GitHub (https://github.com/huggingface/huggingface_hub/issues/new).
  warnings.warn(
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 75e5771e-0055-4031-a5d2-2d245017c933)')' thrown while requesting HEAD https://huggingface.co/microsoft/Florence-2-base/resolve/main/config.json
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 75e5771e-0055-4031-a5d2-2d245017c933)')' thrown while requesting HEAD https://huggingface.co/microsoft/Florence-2-base/resolve/main/config.json
Retrying in 1s [Retry 1/5].
WARNING:huggingface_hub.utils._http:Retrying in 1s [Retry 1/5].
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 79ce2cc0-6df0-4a86-9ce5-cb57e55f9c79)')' thrown while requesting HEAD https://huggingface.co/microsoft/Florence-2-base/resolve/main/config.json
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 79ce2cc0-6df0-4a86-9ce5-cb57e55f9c79)')' thrown while requesting HEAD https://huggingface.co/microsoft/Florence-2-base/resolve/main/config.json
Retrying in 2s [Retry 2/5].
WARNING:huggingface_hub.utils._http:Retrying in 2s [Retry 2/5].
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 61831768-ac4f-438d-8b03-1c790c386e17)')' thrown while requesting HEAD https://huggingface.co/microsoft/Florence-2-base/resolve/main/config.json
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 61831768-ac4f-438d-8b03-1c790c386e17)')' thrown while requesting HEAD https://huggingface.co/microsoft/Florence-2-base/resolve/main/config.json
Retrying in 4s [Retry 3/5].
WARNING:huggingface_hub.utils._http:Retrying in 4s [Retry 3/5].

config.json: 0.00B [00:00, ?B/s]

configuration_florence2.py: 0.00B [00:00, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/microsoft/Florence-2-base:
- configuration_florence2.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.

modeling_florence2.py: 0.00B [00:00, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/microsoft/Florence-2-base:
- modeling_florence2.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.

model.safetensors:   0%|          | 0.00/463M [00:00<?, ?B/s]

preprocessor_config.json:   0%|          | 0.00/806 [00:00<?, ?B/s]

processing_florence2.py: 0.00B [00:00, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/microsoft/Florence-2-base:
- processing_florence2.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.

tokenizer_config.json:   0%|          | 0.00/34.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 435cad67-cf54-4b07-8f5f-915282b85bdb)')' thrown while requesting HEAD https://huggingface.co/microsoft/Florence-2-base/resolve/main/configuration_florence2.py
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 435cad67-cf54-4b07-8f5f-915282b85bdb)')' thrown while requesting HEAD https://huggingface.co/microsoft/Florence-2-base/resolve/main/configuration_florence2.py
Retrying in 1s [Retry 1/5].
WARNING:huggingface_hub.utils._http:Retrying in 1s [Retry 1/5].
COMET WARNING: To get all data logged automatically, import comet_ml before the following modules: sklearn, tensorflow, torch, keras.
COMET WARNING: As you are running in a Jupyter environment, you will need to call `experiment.end()` when finished to ensure all metrics and code are logged before exiting.
COMET INFO: Experiment is live on comet.com https://www.comet.com/scfeel/qwen3-1/9439fa211b4c42fcbf38a937231dfcb3

extraction:florence:image_only:   0%|          | 0/400 [00:00<?, ?it/s]

COMET WARNING: log_asset_data(..., file_name=...) is deprecated; use log_asset_data(..., name=...)
COMET WARNING: log_asset_data(..., file_name=...) is deprecated; use log_asset_data(..., name=...)
COMET WARNING: log_asset_data(..., file_name=...) is deprecated; use log_asset_data(..., name=...)
COMET WARNING: log_asset_data(..., file_name=...) is deprecated; use log_asset_data(..., name=...)
COMET WARNING: Couldn't retrieve and log Google Colab notebook content, reason: 'NoneType' object is not subscriptable
COMET INFO: ---------------------------------------------------------------------------------------
COMET INFO: Comet.ml Experiment Summary
COMET INFO: ---------------------------------------------------------------------------------------
COMET INFO:   Data:
COMET INFO:     display_summary_level : 1
COMET INFO:     name                  : extraction-baseline-florence2-v2
COMET INFO:     url                   : https://www.comet.com/scfeel/qwen3-1/9439fa211b4c42fcbf38a937231dfcb3
COMET INFO:   Metrics:
COMET INFO:     seen_img_black_corrected_em     : -0.014249999999999999
COMET INFO:     seen_img_blur_20_corrected_em   : -0.014249999999999999
COMET INFO:     seen_img_blur_50_corrected_em   : -0.014249999999999999
COMET INFO:     seen_original_corrected_em      : -0.014249999999999999
COMET INFO:     unseen_img_black_corrected_em   : -0.0017500000000000003
COMET INFO:     unseen_img_blur_20_corrected_em : -0.0017500000000000003
COMET INFO:     unseen_img_blur_50_corrected_em : -0.0017500000000000003
COMET INFO:     unseen_original_corrected_em    : -0.0017500000000000003
COMET INFO:   Others:
COMET INFO:     Name         : extraction-baseline-florence2-v2
COMET INFO:     notebook_url : https://colab.research.google.com/notebook#23_data_extraction_v2-jvsc-17603f68-61d9-4ee8-ac45-070691eb2f613c1eee6f-0ab7-43f3-a66a-9de7128a3766.ipynb
COMET INFO:   Parameters:
COMET INFO:     mode      : image_only
COMET INFO:     model_tag : baseline_florence2
COMET INFO:     n_seen    : 200
COMET INFO:     n_unseen  : 200
COMET INFO:     scenarios : ['original', 'img_black', 'img_blur_20', 'img_blur_50']
COMET INFO:   Uploads:
COMET INFO:     asset                    : 8 (978.06 KB)
COMET INFO:     dataframe                : 2 (7.48 KB)
COMET INFO:     environment details      : 1
COMET INFO:     filename                 : 1
COMET INFO:     git metadata             : 1
COMET INFO:     git-patch (uncompressed) : 1 (68.35 MB)
COMET INFO:     installed packages       : 1
COMET INFO:     notebook                 : 1
COMET INFO:     os packages              : 1
COMET INFO:     source_code              : 1
COMET INFO:
COMET WARNING: To get all data logged automatically, import comet_ml before the following modules: sklearn, tensorflow, torch, keras.

,split,scenario,coarse_type,n_examples,exact_match,token_f1,random_em,random_f1,corrected_em,corrected_f1
0,seen,img_black,ALL,200,0.0,0.023929,0.014250,0.034906,-0.014250,-0.010977
1,seen,img_black,AMOUNT,34,0.0,0.003460,0.007353,0.028971,-0.007353,-0.025510
2,seen,img_black,CONTACT_ADR,34,0.0,0.025495,0.036765,0.039706,-0.036765,-0.014211
3,seen,img_black,DATE,33,0.0,0.005051,0.004545,0.035245,-0.004545,-0.030195
4,seen,img_black,ID,33,0.0,0.025364,0.015152,0.016667,-0.015152,0.008697
5,seen,img_black,ORG,33,0.0,0.080448,0.019697,0.073098,-0.019697,0.007351
6,seen,img_black,PERSON,33,0.0,0.004329,0.001515,0.015783,-0.001515,-0.011454
7,seen,img_blur_20,ALL,200,0.0,0.024062,0.014250,0.034906,-0.014250,-0.010843
8,seen,img_blur_20,AMOUNT,34,0.0,0.003460,0.007353,0.028971,-0.007353,-0.025510
9,seen,img_blur_20,CONTACT_ADR,34,0.0,0.025495,0.036765,0.039706,-0.036765,-0.014211
10,seen,img_blur_20,DATE,33,0.0,0.005051,0.004545,0.035245,-0.004545,-0.030195
11,seen,img_blur_20,ID,33,0.0,0.025364,0.015152,0.016667,-0.015152,0.008697
12,seen,img_blur_20,ORG,33,0.0,0.081257,0.019697,0.073098,-0.019697,0.008159
13,seen,img_blur_20,PERSON,33,0.0,0.004329,0.001515,0.015783,-0.001515,-0.011454
14,seen,img_blur_50,ALL,200,0.0,0.024062,0.014250,0.034906,-0.014250,-0.010843
15,seen,img_blur_50,AMOUNT,34,0.0,0.003460,0.007353,0.028971,-0.007353,-0.025510
16,seen,img_blur_50,CONTACT_ADR,34,0.0,0.025495,0.036765,0.039706,-0.036765,-0.014211
17,seen,img_blur_50,DATE,33,0.0,0.005051,0.004545,0.035245,-0.004545,-0.030195
18,seen,img_blur_50,ID,33,0.0,0.025364,0.015152,0.016667,-0.015152,0.008697
19,seen,img_blur_50,ORG,33,0.0,0.081257,0.019697,0.073098,-0.019697,0.008159
20,seen,img_blur_50,PERSON,33,0.0,0.004329,0.001515,0.015783,-0.001515,-0.011454
21,seen,original,ALL,200,0.0,0.041350,0.014250,0.034906,-0.014250,0.006444
22,seen,original,AMOUNT,34,0.0,0.003460,0.007353,0.028971,-0.007353,-0.025510
23,seen,original,CONTACT_ADR,34,0.0,0.041097,0.036765,0.039706,-0.036765,0.001392
24,seen,original,DATE,33,0.0,0.075359,0.004545,0.035245,-0.004545,0.040114
25,seen,original,ID,33,0.0,0.027384,0.015152,0.016667,-0.015152,0.010717
26,seen,original,ORG,33,0.0,0.087721,0.019697,0.073098,-0.019697,0.014623
27,seen,original,PERSON,33,0.0,0.014236,0.001515,0.015783,-0.001515,-0.001547
28,unseen,img_black,ALL,200,0.0,0.022494,0.001750,0.014448,-0.001750,0.008046
29,unseen,img_black,AMOUNT,34,0.0,0.011878,0.000000,0.019412,0.000000,-0.007534
30,unseen,img_black,CONTACT_ADR,34,0.0,0.012028,0.005882,0.008824,-0.005882,0.003205
31,unseen,img_black,DATE,33,0.0,0.022100,0.000000,0.029516,0.000000,-0.007416
32,unseen,img_black,ID,33,0.0,0.003367,0.001515,0.002273,-0.001515,0.001094
33,unseen,img_black,ORG,33,0.0,0.071553,0.003030,0.024303,-0.003030,0.047250
34,unseen,img_black,PERSON,33,0.0,0.014676,0.000000,0.002381,0.000000,0.012295
35,unseen,img_blur_20,ALL,200,0.0,0.023639,0.001750,0.014448,-0.001750,0.009191
36,unseen,img_blur_20,AMOUNT,34,0.0,0.011878,0.000000,0.019412,0.000000,-0.007534
37,unseen,img_blur_20,CONTACT_ADR,34,0.0,0.011856,0.005882,0.008824,-0.005882,0.003033
38,unseen,img_blur_20,DATE,33,0.0,0.022100,0.000000,0.029516,0.000000,-0.007416
39,unseen,img_blur_20,ID,33,0.0,0.003276,0.001515,0.002273,-0.001515,0.001003
40,unseen,img_blur_20,ORG,33,0.0,0.078655,0.003030,0.024303,-0.003030,0.054352
41,unseen,img_blur_20,PERSON,33,0.0,0.014784,0.000000,0.002381,0.000000,0.012403
42,unseen,img_blur_50,ALL,200,0.0,0.023589,0.001750,0.014448,-0.001750,0.009141
43,unseen,img_blur_50,AMOUNT,34,0.0,0.011878,0.000000,0.019412,0.000000,-0.007534
44,unseen,img_blur_50,CONTACT_ADR,34,0.0,0.011856,0.005882,0.008824,-0.005882,0.003033
45,unseen,img_blur_50,DATE,33,0.0,0.023548,0.000000,0.029516,0.000000,-0.005967
46,unseen,img_blur_50,ID,33,0.0,0.003367,0.001515,0.002273,-0.001515,0.001094
47,unseen,img_blur_50,ORG,33,0.0,0.076813,0.003030,0.024303,-0.003030,0.052510
48,unseen,img_blur_50,PERSON,33,0.0,0.014784,0.000000,0.002381,0.000000,0.012403
49,unseen,original,ALL,200,0.0,0.050198,0.001750,0.014448,-0.001750,0.035750
50,unseen,original,AMOUNT,34,0.0,0.011984,0.000000,0.019412,0.000000,-0.007427
51,unseen,original,CONTACT_ADR,34,0.0,0.023759,0.005882,0.008824,-0.005882,0.014936
52,unseen,original,DATE,33,0.0,0.068753,0.000000,0.029516,0.000000,0.039238
53,unseen,original,ID,33,0.0,0.054259,0.001515,0.002273,-0.001515,0.051986
54,unseen,original,ORG,33,0.0,0.127219,0.003030,0.024303,-0.003030,0.102916
55,unseen,original,PERSON,33,0.0,0.017172,0.000000,0.002381,0.000000,0.014791

In [6]:
# Florence-2 epoch_30 extraction
model, processor = load_florence("checkpoints/florence2_v2/epoch_10")
florence_outputs = run_model_extraction_experiment(
    model=model,
    processor=processor,
    model_tag="florence2_epoch10",
    model_kind="florence",
    mode="image_only",
    scenarios=FLORENCE_SCENARIOS,
    seen_records=florence_seen,
    unseen_records=unseen_200,
    answer_pools=florence_answer_pools,
    experiment_name="extraction-florence2-epoch10-v2",
)
display(florence_outputs[2])
del model, processor
cleanup_gpu()

COMET WARNING: To get all data logged automatically, import comet_ml before the following modules: sklearn, tensorflow, torch, keras.
COMET WARNING: As you are running in a Jupyter environment, you will need to call `experiment.end()` when finished to ensure all metrics and code are logged before exiting.
COMET INFO: Experiment is live on comet.com https://www.comet.com/scfeel/qwen3-1/0a0a75cc895549e7a257bb39cf456e52

extraction:florence:image_only:   0%|          | 0/400 [00:00<?, ?it/s]

COMET WARNING: log_asset_data(..., file_name=...) is deprecated; use log_asset_data(..., name=...)
COMET WARNING: log_asset_data(..., file_name=...) is deprecated; use log_asset_data(..., name=...)
COMET WARNING: log_asset_data(..., file_name=...) is deprecated; use log_asset_data(..., name=...)
COMET WARNING: log_asset_data(..., file_name=...) is deprecated; use log_asset_data(..., name=...)
COMET WARNING: Couldn't retrieve and log Google Colab notebook content, reason: 'NoneType' object is not subscriptable
COMET INFO: ---------------------------------------------------------------------------------------
COMET INFO: Comet.ml Experiment Summary
COMET INFO: ---------------------------------------------------------------------------------------
COMET INFO:   Data:
COMET INFO:     display_summary_level : 1
COMET INFO:     name                  : extraction-florence2-epoch10-v2
COMET INFO:     url                   : https://www.comet.com/scfeel/qwen3-1/0a0a75cc895549e7a257bb39cf456e52
COMET INFO:   Metrics:
COMET INFO:     seen_img_black_corrected_em     : 0.08074999999999999
COMET INFO:     seen_img_blur_20_corrected_em   : 0.08074999999999999
COMET INFO:     seen_img_blur_50_corrected_em   : 0.08074999999999999
COMET INFO:     seen_original_corrected_em      : 0.9307499999999999
COMET INFO:     unseen_img_black_corrected_em   : 0.00825
COMET INFO:     unseen_img_blur_20_corrected_em : 0.00825
COMET INFO:     unseen_img_blur_50_corrected_em : 0.00825
COMET INFO:     unseen_original_corrected_em    : 0.12325
COMET INFO:   Others:
COMET INFO:     Name         : extraction-florence2-epoch10-v2
COMET INFO:     notebook_url : https://colab.research.google.com/notebook#23_data_extraction_v2-jvsc-17603f68-61d9-4ee8-ac45-070691eb2f613c1eee6f-0ab7-43f3-a66a-9de7128a3766.ipynb
COMET INFO:   Parameters:
COMET INFO:     mode      : image_only
COMET INFO:     model_tag : florence2_epoch10
COMET INFO:     n_seen    : 200
COMET INFO:     n_unseen  : 200
COMET INFO:     scenarios : ['original', 'img_black', 'img_blur_20', 'img_blur_50']
COMET INFO:   Uploads:
COMET INFO:     asset                    : 8 (593.89 KB)
COMET INFO:     dataframe                : 2 (11.07 KB)
COMET INFO:     environment details      : 1
COMET INFO:     filename                 : 1
COMET INFO:     git metadata             : 1
COMET INFO:     git-patch (uncompressed) : 1 (68.35 MB)
COMET INFO:     images                   : 5
COMET INFO:     installed packages       : 1
COMET INFO:     notebook                 : 1
COMET INFO:     os packages              : 1
COMET INFO:     source_code              : 1
COMET INFO:
COMET WARNING: To get all data logged automatically, import comet_ml before the following modules: sklearn, tensorflow, torch, keras.

,split,scenario,coarse_type,n_examples,exact_match,token_f1,random_em,random_f1,corrected_em,corrected_f1
0,seen,img_black,ALL,200,0.095000,0.228727,0.014250,0.034906,0.080750,0.193821
1,seen,img_black,AMOUNT,34,0.176471,0.379412,0.007353,0.028971,0.169118,0.350441
2,seen,img_black,CONTACT_ADR,34,0.088235,0.159715,0.036765,0.039706,0.051471,0.120009
3,seen,img_black,DATE,33,0.090909,0.301659,0.004545,0.035245,0.086364,0.266414
4,seen,img_black,ID,33,0.060606,0.106734,0.015152,0.016667,0.045455,0.090067
5,seen,img_black,ORG,33,0.090909,0.205628,0.019697,0.073098,0.071212,0.132530
6,seen,img_black,PERSON,33,0.060606,0.216739,0.001515,0.015783,0.059091,0.200956
7,seen,img_blur_20,ALL,200,0.095000,0.227552,0.014250,0.034906,0.080750,0.192647
8,seen,img_blur_20,AMOUNT,34,0.176471,0.379412,0.007353,0.028971,0.169118,0.350441
9,seen,img_blur_20,CONTACT_ADR,34,0.088235,0.171480,0.036765,0.039706,0.051471,0.131774
10,seen,img_blur_20,DATE,33,0.090909,0.301659,0.004545,0.035245,0.086364,0.266414
11,seen,img_blur_20,ID,33,0.060606,0.106734,0.015152,0.016667,0.045455,0.090067
12,seen,img_blur_20,ORG,33,0.060606,0.175325,0.019697,0.073098,0.040909,0.102227
13,seen,img_blur_20,PERSON,33,0.090909,0.227802,0.001515,0.015783,0.089394,0.212019
14,seen,img_blur_50,ALL,200,0.095000,0.225275,0.014250,0.034906,0.080750,0.190369
15,seen,img_blur_50,AMOUNT,34,0.176471,0.350000,0.007353,0.028971,0.169118,0.321029
16,seen,img_blur_50,CONTACT_ADR,34,0.088235,0.159715,0.036765,0.039706,0.051471,0.120009
17,seen,img_blur_50,DATE,33,0.090909,0.301659,0.004545,0.035245,0.086364,0.266414
18,seen,img_blur_50,ID,33,0.060606,0.126936,0.015152,0.016667,0.045455,0.110269
19,seen,img_blur_50,ORG,33,0.060606,0.175325,0.019697,0.073098,0.040909,0.102227
20,seen,img_blur_50,PERSON,33,0.090909,0.236219,0.001515,0.015783,0.089394,0.220437
21,seen,original,ALL,200,0.945000,0.963167,0.014250,0.034906,0.930750,0.928261
22,seen,original,AMOUNT,34,0.823529,0.867647,0.007353,0.028971,0.816176,0.838676
23,seen,original,CONTACT_ADR,34,0.970588,0.990196,0.036765,0.039706,0.933824,0.950490
24,seen,original,DATE,33,0.909091,0.929293,0.004545,0.035245,0.904545,0.894048
25,seen,original,ID,33,0.969697,0.993939,0.015152,0.016667,0.954545,0.977273
26,seen,original,ORG,33,1.000000,1.000000,0.019697,0.073098,0.980303,0.926902
27,seen,original,PERSON,33,1.000000,1.000000,0.001515,0.015783,0.998485,0.984217
28,unseen,img_black,ALL,200,0.010000,0.060067,0.001750,0.014448,0.008250,0.045620
29,unseen,img_black,AMOUNT,34,0.000000,0.038235,0.000000,0.019412,0.000000,0.018824
30,unseen,img_black,CONTACT_ADR,34,0.000000,0.035014,0.005882,0.008824,-0.005882,0.026190
31,unseen,img_black,DATE,33,0.000000,0.086436,0.000000,0.029516,0.000000,0.056920
32,unseen,img_black,ID,33,0.030303,0.030303,0.001515,0.002273,0.028788,0.028030
33,unseen,img_black,ORG,33,0.030303,0.149110,0.003030,0.024303,0.027273,0.124807
34,unseen,img_black,PERSON,33,0.000000,0.022727,0.000000,0.002381,0.000000,0.020346
35,unseen,img_blur_20,ALL,200,0.010000,0.061734,0.001750,0.014448,0.008250,0.047286
36,unseen,img_blur_20,AMOUNT,34,0.000000,0.038235,0.000000,0.019412,0.000000,0.018824
37,unseen,img_blur_20,CONTACT_ADR,34,0.000000,0.035014,0.005882,0.008824,-0.005882,0.026190
38,unseen,img_blur_20,DATE,33,0.000000,0.096537,0.000000,0.029516,0.000000,0.067021
39,unseen,img_blur_20,ID,33,0.030303,0.030303,0.001515,0.002273,0.028788,0.028030
40,unseen,img_blur_20,ORG,33,0.030303,0.149110,0.003030,0.024303,0.027273,0.124807
41,unseen,img_blur_20,PERSON,33,0.000000,0.022727,0.000000,0.002381,0.000000,0.020346
42,unseen,img_blur_50,ALL,200,0.010000,0.065067,0.001750,0.014448,0.008250,0.050620
43,unseen,img_blur_50,AMOUNT,34,0.000000,0.038235,0.000000,0.019412,0.000000,0.018824
44,unseen,img_blur_50,CONTACT_ADR,34,0.000000,0.035014,0.005882,0.008824,-0.005882,0.026190
45,unseen,img_blur_50,DATE,33,0.000000,0.096537,0.000000,0.029516,0.000000,0.067021
46,unseen,img_blur_50,ID,33,0.030303,0.050505,0.001515,0.002273,0.028788,0.048232
47,unseen,img_blur_50,ORG,33,0.030303,0.149110,0.003030,0.024303,0.027273,0.124807
48,unseen,img_blur_50,PERSON,33,0.000000,0.022727,0.000000,0.002381,0.000000,0.020346
49,unseen,original,ALL,200,0.125000,0.228508,0.001750,0.014448,0.123250,0.214060
50,unseen,original,AMOUNT,34,0.029412,0.128011,0.000000,0.019412,0.029412,0.108599
51,unseen,original,CONTACT_ADR,34,0.000000,0.063725,0.005882,0.008824,-0.005882,0.054902
52,unseen,original,DATE,33,0.242424,0.397162,0.000000,0.029516,0.242424,0.367647
53,unseen,original,ID,33,0.121212,0.151515,0.001515,0.002273,0.119697,0.149242
54,unseen,original,ORG,33,0.303030,0.434055,0.003030,0.024303,0.300000,0.409752
55,unseen,original,PERSON,33,0.060606,0.204618,0.000000,0.002381,0.060606,0.202237

In [7]:
# Qwen2-VL-2B extraction
model, processor = load_qwen("Qwen/Qwen2-VL-2B-Instruct", "checkpoints/qwen2b_v2/epoch_10")
qwen2b_image_only_outputs = run_model_extraction_experiment(
    model=model,
    processor=processor,
    model_tag="qwen2b_epoch10",
    model_kind="qwen",
    mode="image_only",
    scenarios=QWEN_IMAGE_ONLY_SCENARIOS,
    seen_records=qwen_seen,
    unseen_records=unseen_200,
    answer_pools=qwen_answer_pools,
    experiment_name="extraction-qwen2b-epoch10-imageonly-v2",
)
display(qwen2b_image_only_outputs[2])
del model, processor
cleanup_gpu()

model, processor = load_qwen("Qwen/Qwen2-VL-2B-Instruct", "checkpoints/qwen2b_v2/epoch_10")
qwen2b_image_ocr_outputs = run_model_extraction_experiment(
    model=model,
    processor=processor,
    model_tag="qwen2b_epoch10",
    model_kind="qwen",
    mode="image_ocr",
    scenarios=QWEN_IMAGE_OCR_SCENARIOS,
    seen_records=qwen_seen,
    unseen_records=unseen_200,
    answer_pools=qwen_answer_pools,
    experiment_name="extraction-qwen2b-epoch10-imageocr-v2",
)
display(qwen2b_image_ocr_outputs[2])
del model, processor
cleanup_gpu()

The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.

config.json: 0.00B [00:00, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading shards:   0%|          | 0/2 [00:00<?, ?it/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/3.99G [00:00<?, ?B/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/429M [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/272 [00:00<?, ?B/s]

preprocessor_config.json:   0%|          | 0.00/347 [00:00<?, ?B/s]

Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.48, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

chat_template.json: 0.00B [00:00, ?B/s]

COMET WARNING: To get all data logged automatically, import comet_ml before the following modules: sklearn, tensorflow, torch, keras.
COMET WARNING: As you are running in a Jupyter environment, you will need to call `experiment.end()` when finished to ensure all metrics and code are logged before exiting.
COMET INFO: Experiment is live on comet.com https://www.comet.com/scfeel/qwen3-1/12f441d0e2bb4d88b90c9ff51f8eb9c3

extraction:qwen:image_only:   0%|          | 0/400 [00:00<?, ?it/s]

COMET WARNING: log_asset_data(..., file_name=...) is deprecated; use log_asset_data(..., name=...)
COMET WARNING: log_asset_data(..., file_name=...) is deprecated; use log_asset_data(..., name=...)
COMET WARNING: log_asset_data(..., file_name=...) is deprecated; use log_asset_data(..., name=...)
COMET WARNING: log_asset_data(..., file_name=...) is deprecated; use log_asset_data(..., name=...)
COMET WARNING: Couldn't retrieve and log Google Colab notebook content, reason: 'NoneType' object is not subscriptable
COMET INFO: ---------------------------------------------------------------------------------------
COMET INFO: Comet.ml Experiment Summary
COMET INFO: ---------------------------------------------------------------------------------------
COMET INFO:   Data:
COMET INFO:     display_summary_level : 1
COMET INFO:     name                  : extraction-qwen2b-epoch10-imageonly-v2
COMET INFO:     url                   : https://www.comet.com/scfeel/qwen3-1/12f441d0e2bb4d88b90c9ff51f8eb9c3
COMET INFO:   Metrics:
COMET INFO:     seen_img_black_corrected_em     : 0.47575
COMET INFO:     seen_img_blur_20_corrected_em   : 0.48075
COMET INFO:     seen_img_blur_50_corrected_em   : 0.49075
COMET INFO:     seen_original_corrected_em      : 0.8057499999999999
COMET INFO:     unseen_img_black_corrected_em   : 0.013250000000000001
COMET INFO:     unseen_img_blur_20_corrected_em : 0.01825
COMET INFO:     unseen_img_blur_50_corrected_em : 0.013250000000000001
COMET INFO:     unseen_original_corrected_em    : 0.17825000000000002
COMET INFO:   Others:
COMET INFO:     Name         : extraction-qwen2b-epoch10-imageonly-v2
COMET INFO:     notebook_url : https://colab.research.google.com/notebook#23_data_extraction_v2-jvsc-17603f68-61d9-4ee8-ac45-070691eb2f613c1eee6f-0ab7-43f3-a66a-9de7128a3766.ipynb
COMET INFO:   Parameters:
COMET INFO:     mode      : image_only
COMET INFO:     model_tag : qwen2b_epoch10
COMET INFO:     n_seen    : 200
COMET INFO:     n_unseen  : 200
COMET INFO:     scenarios : ['original', 'img_black', 'img_blur_20', 'img_blur_50']
COMET INFO:   Uploads:
COMET INFO:     asset                    : 8 (594.63 KB)
COMET INFO:     dataframe                : 2 (11.15 KB)
COMET INFO:     environment details      : 1
COMET INFO:     filename                 : 1
COMET INFO:     git metadata             : 1
COMET INFO:     git-patch (uncompressed) : 1 (68.35 MB)
COMET INFO:     images                   : 5
COMET INFO:     installed packages       : 1
COMET INFO:     notebook                 : 1
COMET INFO:     os packages              : 1
COMET INFO:     source_code              : 1
COMET INFO:
COMET WARNING: To get all data logged automatically, import comet_ml before the following modules: sklearn, tensorflow, torch, keras.

,split,scenario,coarse_type,n_examples,exact_match,token_f1,random_em,random_f1,corrected_em,corrected_f1
0,seen,img_black,ALL,200,0.490000,0.557242,0.014250,0.034906,0.475750,0.522337
1,seen,img_black,AMOUNT,34,0.411765,0.441176,0.007353,0.028971,0.404412,0.412206
2,seen,img_black,CONTACT_ADR,34,0.441176,0.520499,0.036765,0.039706,0.404412,0.480793
3,seen,img_black,DATE,33,0.454545,0.542063,0.004545,0.035245,0.450000,0.506818
4,seen,img_black,ID,33,0.424242,0.467555,0.015152,0.016667,0.409091,0.450888
5,seen,img_black,ORG,33,0.484848,0.611400,0.019697,0.073098,0.465152,0.538302
6,seen,img_black,PERSON,33,0.727273,0.765392,0.001515,0.015783,0.725758,0.749609
7,seen,img_blur_20,ALL,200,0.495000,0.564454,0.014250,0.034906,0.480750,0.529548
8,seen,img_blur_20,AMOUNT,34,0.441176,0.470588,0.007353,0.028971,0.433824,0.441618
9,seen,img_blur_20,CONTACT_ADR,34,0.441176,0.510695,0.036765,0.039706,0.404412,0.470989
10,seen,img_blur_20,DATE,33,0.424242,0.552742,0.004545,0.035245,0.419697,0.517496
11,seen,img_blur_20,ID,33,0.454545,0.477656,0.015152,0.016667,0.439394,0.460989
12,seen,img_blur_20,ORG,33,0.515152,0.621697,0.019697,0.073098,0.495455,0.548600
13,seen,img_blur_20,PERSON,33,0.696970,0.757816,0.001515,0.015783,0.695455,0.742033
14,seen,img_blur_50,ALL,200,0.505000,0.568870,0.014250,0.034906,0.490750,0.533964
15,seen,img_blur_50,AMOUNT,34,0.470588,0.500000,0.007353,0.028971,0.463235,0.471029
16,seen,img_blur_50,CONTACT_ADR,34,0.470588,0.530303,0.036765,0.039706,0.433824,0.490597
17,seen,img_blur_50,DATE,33,0.424242,0.542641,0.004545,0.035245,0.419697,0.507395
18,seen,img_blur_50,ID,33,0.454545,0.477656,0.015152,0.016667,0.439394,0.460989
19,seen,img_blur_50,ORG,33,0.515152,0.618667,0.019697,0.073098,0.495455,0.545570
20,seen,img_blur_50,PERSON,33,0.696970,0.747210,0.001515,0.015783,0.695455,0.731427
21,seen,original,ALL,200,0.820000,0.852841,0.014250,0.034906,0.805750,0.817935
22,seen,original,AMOUNT,34,0.647059,0.676471,0.007353,0.028971,0.639706,0.647500
23,seen,original,CONTACT_ADR,34,0.794118,0.852941,0.036765,0.039706,0.757353,0.813235
24,seen,original,DATE,33,0.909091,0.945527,0.004545,0.035245,0.904545,0.910281
25,seen,original,ID,33,0.848485,0.862937,0.015152,0.016667,0.833333,0.846270
26,seen,original,ORG,33,0.878788,0.883838,0.019697,0.073098,0.859091,0.810741
27,seen,original,PERSON,33,0.848485,0.900673,0.001515,0.015783,0.846970,0.884891
28,unseen,img_black,ALL,200,0.015000,0.054599,0.001750,0.014448,0.013250,0.040151
29,unseen,img_black,AMOUNT,34,0.029412,0.063725,0.000000,0.019412,0.029412,0.044314
30,unseen,img_black,CONTACT_ADR,34,0.000000,0.022059,0.005882,0.008824,-0.005882,0.013235
31,unseen,img_black,DATE,33,0.000000,0.108947,0.000000,0.029516,0.000000,0.079431
32,unseen,img_black,ID,33,0.000000,0.012121,0.001515,0.002273,-0.001515,0.009848
33,unseen,img_black,ORG,33,0.030303,0.082492,0.003030,0.024303,0.027273,0.058189
34,unseen,img_black,PERSON,33,0.030303,0.038961,0.000000,0.002381,0.030303,0.036580
35,unseen,img_blur_20,ALL,200,0.020000,0.050648,0.001750,0.014448,0.018250,0.036200
36,unseen,img_blur_20,AMOUNT,34,0.029412,0.044118,0.000000,0.019412,0.029412,0.024706
37,unseen,img_blur_20,CONTACT_ADR,34,0.000000,0.014706,0.005882,0.008824,-0.005882,0.005882
38,unseen,img_blur_20,DATE,33,0.000000,0.108947,0.000000,0.029516,0.000000,0.079431
39,unseen,img_blur_20,ID,33,0.000000,0.000000,0.001515,0.002273,-0.001515,-0.002273
40,unseen,img_blur_20,ORG,33,0.090909,0.128748,0.003030,0.024303,0.087879,0.104445
41,unseen,img_blur_20,PERSON,33,0.000000,0.008658,0.000000,0.002381,0.000000,0.006277
42,unseen,img_blur_50,ALL,200,0.015000,0.049676,0.001750,0.014448,0.013250,0.035228
43,unseen,img_blur_50,AMOUNT,34,0.029412,0.053922,0.000000,0.019412,0.029412,0.034510
44,unseen,img_blur_50,CONTACT_ADR,34,0.000000,0.028595,0.005882,0.008824,-0.005882,0.019771
45,unseen,img_blur_50,DATE,33,0.000000,0.108947,0.000000,0.029516,0.000000,0.079431
46,unseen,img_blur_50,ID,33,0.000000,0.000000,0.001515,0.002273,-0.001515,-0.002273
47,unseen,img_blur_50,ORG,33,0.060606,0.098445,0.003030,0.024303,0.057576,0.074142
48,unseen,img_blur_50,PERSON,33,0.000000,0.008658,0.000000,0.002381,0.000000,0.006277
49,unseen,original,ALL,200,0.180000,0.215651,0.001750,0.014448,0.178250,0.201203
50,unseen,original,AMOUNT,34,0.147059,0.181373,0.000000,0.019412,0.147059,0.161961
51,unseen,original,CONTACT_ADR,34,0.058824,0.111111,0.005882,0.008824,0.052941,0.102288
52,unseen,original,DATE,33,0.333333,0.401010,0.000000,0.029516,0.333333,0.371495
53,unseen,original,ID,33,0.121212,0.156566,0.001515,0.002273,0.119697,0.154293
54,unseen,original,ORG,33,0.242424,0.242424,0.003030,0.024303,0.239394,0.218121
55,unseen,original,PERSON,33,0.181818,0.205628,0.000000,0.002381,0.181818,0.203247

The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

COMET WARNING: To get all data logged automatically, import comet_ml before the following modules: sklearn, tensorflow, torch, keras.
COMET WARNING: As you are running in a Jupyter environment, you will need to call `experiment.end()` when finished to ensure all metrics and code are logged before exiting.
COMET INFO: Experiment is live on comet.com https://www.comet.com/scfeel/qwen3-1/0a0468c452a243bf8b6f18ec95769f63

extraction:qwen:image_ocr:   0%|          | 0/400 [00:00<?, ?it/s]

COMET WARNING: log_asset_data(..., file_name=...) is deprecated; use log_asset_data(..., name=...)
COMET WARNING: log_asset_data(..., file_name=...) is deprecated; use log_asset_data(..., name=...)
COMET WARNING: log_asset_data(..., file_name=...) is deprecated; use log_asset_data(..., name=...)
COMET WARNING: log_asset_data(..., file_name=...) is deprecated; use log_asset_data(..., name=...)
COMET WARNING: Couldn't retrieve and log Google Colab notebook content, reason: 'NoneType' object is not subscriptable
COMET INFO: ---------------------------------------------------------------------------------------
COMET INFO: Comet.ml Experiment Summary
COMET INFO: ---------------------------------------------------------------------------------------
COMET INFO:   Data:
COMET INFO:     display_summary_level : 1
COMET INFO:     name                  : extraction-qwen2b-epoch10-imageocr-v2
COMET INFO:     url                   : https://www.comet.com/scfeel/qwen3-1/0a0468c452a243bf8b6f18ec95769f63
COMET INFO:   Metrics:
COMET INFO:     seen_img_black__ocr_mask__k_0_corrected_em   : 0.01575
COMET INFO:     seen_img_none__ocr_mask__k_0_corrected_em    : 0.31575
COMET INFO:     unseen_img_black__ocr_mask__k_0_corrected_em : 0.013250000000000001
COMET INFO:     unseen_img_none__ocr_mask__k_0_corrected_em  : 0.15325
COMET INFO:   Others:
COMET INFO:     Name         : extraction-qwen2b-epoch10-imageocr-v2
COMET INFO:     notebook_url : https://colab.research.google.com/notebook#23_data_extraction_v2-jvsc-17603f68-61d9-4ee8-ac45-070691eb2f613c1eee6f-0ab7-43f3-a66a-9de7128a3766.ipynb
COMET INFO:   Parameters:
COMET INFO:     mode      : image_ocr
COMET INFO:     model_tag : qwen2b_epoch10
COMET INFO:     n_seen    : 200
COMET INFO:     n_unseen  : 200
COMET INFO:     scenarios : ['img_black__ocr_mask__k_0', 'img_none__ocr_mask__k_0']
COMET INFO:   Uploads:
COMET INFO:     asset                    : 8 (2.19 MB)
COMET INFO:     dataframe                : 2 (30.02 KB)
COMET INFO:     environment details      : 1
COMET INFO:     filename                 : 1
COMET INFO:     git metadata             : 1
COMET INFO:     git-patch (uncompressed) : 1 (68.35 MB)
COMET INFO:     images                   : 5
COMET INFO:     installed packages       : 1
COMET INFO:     notebook                 : 1
COMET INFO:     os packages              : 1
COMET INFO:     source_code              : 1
COMET INFO:
COMET WARNING: To get all data logged automatically, import comet_ml before the following modules: sklearn, tensorflow, torch, keras.
COMET INFO: Please wait for metadata to finish uploading (timeout is 3600 seconds)
COMET INFO: Uploading 1 metrics, params and output messages

,split,scenario,coarse_type,n_examples,exact_match,token_f1,random_em,random_f1,corrected_em,corrected_f1
0,seen,img_black__ocr_mask__k_0,ALL,200,0.030000,0.110806,0.014250,0.034906,0.015750,0.075901
1,seen,img_black__ocr_mask__k_0,AMOUNT,34,0.058824,0.098039,0.007353,0.028971,0.051471,0.069069
2,seen,img_black__ocr_mask__k_0,CONTACT_ADR,34,0.000000,0.074981,0.036765,0.039706,-0.036765,0.035275
3,seen,img_black__ocr_mask__k_0,DATE,33,0.000000,0.123377,0.004545,0.035245,-0.004545,0.088131
4,seen,img_black__ocr_mask__k_0,ID,33,0.060606,0.092929,0.015152,0.016667,0.045455,0.076263
5,seen,img_black__ocr_mask__k_0,ORG,33,0.060606,0.227922,0.019697,0.073098,0.040909,0.154824
6,seen,img_black__ocr_mask__k_0,PERSON,33,0.000000,0.049062,0.001515,0.015783,-0.001515,0.033279
7,seen,img_none__ocr_mask__k_0,ALL,200,0.330000,0.387821,0.014250,0.034906,0.315750,0.352916
8,seen,img_none__ocr_mask__k_0,AMOUNT,34,0.264706,0.318627,0.007353,0.028971,0.257353,0.289657
9,seen,img_none__ocr_mask__k_0,CONTACT_ADR,34,0.352941,0.387255,0.036765,0.039706,0.316176,0.347549
10,seen,img_none__ocr_mask__k_0,DATE,33,0.424242,0.479798,0.004545,0.035245,0.419697,0.444553
11,seen,img_none__ocr_mask__k_0,ID,33,0.393939,0.426263,0.015152,0.016667,0.378788,0.409596
12,seen,img_none__ocr_mask__k_0,ORG,33,0.393939,0.514502,0.019697,0.073098,0.374242,0.441405
13,seen,img_none__ocr_mask__k_0,PERSON,33,0.151515,0.202597,0.001515,0.015783,0.150000,0.186815
14,unseen,img_black__ocr_mask__k_0,ALL,200,0.015000,0.099003,0.001750,0.014448,0.013250,0.084555
15,unseen,img_black__ocr_mask__k_0,AMOUNT,34,0.000000,0.063725,0.000000,0.019412,0.000000,0.044314
16,unseen,img_black__ocr_mask__k_0,CONTACT_ADR,34,0.000000,0.116103,0.005882,0.008824,-0.005882,0.107279
17,unseen,img_black__ocr_mask__k_0,DATE,33,0.030303,0.093074,0.000000,0.029516,0.030303,0.063558
18,unseen,img_black__ocr_mask__k_0,ID,33,0.000000,0.062963,0.001515,0.002273,-0.001515,0.060690
19,unseen,img_black__ocr_mask__k_0,ORG,33,0.060606,0.191534,0.003030,0.024303,0.057576,0.167232
20,unseen,img_black__ocr_mask__k_0,PERSON,33,0.000000,0.067172,0.000000,0.002381,0.000000,0.064791
21,unseen,img_none__ocr_mask__k_0,ALL,200,0.155000,0.249228,0.001750,0.014448,0.153250,0.234780
22,unseen,img_none__ocr_mask__k_0,AMOUNT,34,0.176471,0.240196,0.000000,0.019412,0.176471,0.220784
23,unseen,img_none__ocr_mask__k_0,CONTACT_ADR,34,0.029412,0.165033,0.005882,0.008824,0.023529,0.156209
24,unseen,img_none__ocr_mask__k_0,DATE,33,0.272727,0.359848,0.000000,0.029516,0.272727,0.330333
25,unseen,img_none__ocr_mask__k_0,ID,33,0.121212,0.184175,0.001515,0.002273,0.119697,0.181902
26,unseen,img_none__ocr_mask__k_0,ORG,33,0.212121,0.325204,0.003030,0.024303,0.209091,0.300902
27,unseen,img_none__ocr_mask__k_0,PERSON,33,0.121212,0.223737,0.000000,0.002381,0.121212,0.221356

In [8]:
# Qwen2-VL-7B extraction
model, processor = load_qwen("Qwen/Qwen2-VL-7B-Instruct", "checkpoints/qwen7b_v2/epoch_10")
qwen7b_image_only_outputs = run_model_extraction_experiment(
    model=model,
    processor=processor,
    model_tag="qwen7b_epoch10",
    model_kind="qwen",
    mode="image_only",
    scenarios=QWEN_IMAGE_ONLY_SCENARIOS,
    seen_records=qwen_seen,
    unseen_records=unseen_200,
    answer_pools=qwen_answer_pools,
    experiment_name="extraction-qwen7b-epoch10-imageonly-v2",
)
display(qwen7b_image_only_outputs[2])
del model, processor
cleanup_gpu()

The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.

config.json: 0.00B [00:00, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading shards:   0%|          | 0/5 [00:00<?, ?it/s]

model-00001-of-00005.safetensors:   0%|          | 0.00/3.90G [00:00<?, ?B/s]

model-00002-of-00005.safetensors:   0%|          | 0.00/3.86G [00:00<?, ?B/s]

model-00003-of-00005.safetensors:   0%|          | 0.00/3.86G [00:00<?, ?B/s]

model-00004-of-00005.safetensors:   0%|          | 0.00/3.86G [00:00<?, ?B/s]

model-00005-of-00005.safetensors:   0%|          | 0.00/1.09G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/5 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/244 [00:00<?, ?B/s]

preprocessor_config.json:   0%|          | 0.00/347 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

chat_template.json: 0.00B [00:00, ?B/s]

COMET WARNING: To get all data logged automatically, import comet_ml before the following modules: sklearn, tensorflow, torch, keras.
COMET WARNING: As you are running in a Jupyter environment, you will need to call `experiment.end()` when finished to ensure all metrics and code are logged before exiting.
COMET INFO: Experiment is live on comet.com https://www.comet.com/scfeel/qwen3-1/6d925ecfbbff49708069a86361b06fd3

extraction:qwen:image_only:   0%|          | 0/400 [00:00<?, ?it/s]

COMET WARNING: log_asset_data(..., file_name=...) is deprecated; use log_asset_data(..., name=...)
COMET WARNING: log_asset_data(..., file_name=...) is deprecated; use log_asset_data(..., name=...)
COMET WARNING: log_asset_data(..., file_name=...) is deprecated; use log_asset_data(..., name=...)
COMET WARNING: log_asset_data(..., file_name=...) is deprecated; use log_asset_data(..., name=...)
COMET WARNING: Couldn't retrieve and log Google Colab notebook content, reason: 'NoneType' object is not subscriptable
COMET INFO: ---------------------------------------------------------------------------------------
COMET INFO: Comet.ml Experiment Summary
COMET INFO: ---------------------------------------------------------------------------------------
COMET INFO:   Data:
COMET INFO:     display_summary_level : 1
COMET INFO:     name                  : extraction-qwen7b-epoch10-imageonly-v2
COMET INFO:     url                   : https://www.comet.com/scfeel/qwen3-1/6d925ecfbbff49708069a86361b06fd3
COMET INFO:   Metrics:
COMET INFO:     seen_img_black_corrected_em     : 0.57575
COMET INFO:     seen_img_blur_20_corrected_em   : 0.58575
COMET INFO:     seen_img_blur_50_corrected_em   : 0.57575
COMET INFO:     seen_original_corrected_em      : 0.9007499999999999
COMET INFO:     unseen_img_black_corrected_em   : 0.033249999999999995
COMET INFO:     unseen_img_blur_20_corrected_em : 0.028249999999999997
COMET INFO:     unseen_img_blur_50_corrected_em : 0.028249999999999997
COMET INFO:     unseen_original_corrected_em    : 0.22325000000000003
COMET INFO:   Others:
COMET INFO:     Name         : extraction-qwen7b-epoch10-imageonly-v2
COMET INFO:     notebook_url : https://colab.research.google.com/notebook#23_data_extraction_v2-jvsc-17603f68-61d9-4ee8-ac45-070691eb2f613c1eee6f-0ab7-43f3-a66a-9de7128a3766.ipynb
COMET INFO:   Parameters:
COMET INFO:     mode      : image_only
COMET INFO:     model_tag : qwen7b_epoch10
COMET INFO:     n_seen    : 200
COMET INFO:     n_unseen  : 200
COMET INFO:     scenarios : ['original', 'img_black', 'img_blur_20', 'img_blur_50']
COMET INFO:   Uploads:
COMET INFO:     asset                    : 8 (597.61 KB)
COMET INFO:     dataframe                : 2 (11.08 KB)
COMET INFO:     environment details      : 1
COMET INFO:     filename                 : 1
COMET INFO:     git metadata             : 1
COMET INFO:     git-patch (uncompressed) : 1 (68.35 MB)
COMET INFO:     images                   : 5
COMET INFO:     installed packages       : 1
COMET INFO:     notebook                 : 1
COMET INFO:     os packages              : 1
COMET INFO:     source_code              : 1
COMET INFO:
COMET WARNING: To get all data logged automatically, import comet_ml before the following modules: sklearn, tensorflow, torch, keras.

,split,scenario,coarse_type,n_examples,exact_match,token_f1,random_em,random_f1,corrected_em,corrected_f1
0,seen,img_black,ALL,200,0.590000,0.647342,0.014250,0.034906,0.575750,0.612436
1,seen,img_black,AMOUNT,34,0.470588,0.514706,0.007353,0.028971,0.463235,0.485735
2,seen,img_black,CONTACT_ADR,34,0.558824,0.648930,0.036765,0.039706,0.522059,0.609225
3,seen,img_black,DATE,33,0.545455,0.602092,0.004545,0.035245,0.540909,0.566847
4,seen,img_black,ID,33,0.575758,0.624675,0.015152,0.016667,0.560606,0.608009
5,seen,img_black,ORG,33,0.575758,0.660678,0.019697,0.073098,0.556061,0.587581
6,seen,img_black,PERSON,33,0.818182,0.836941,0.001515,0.015783,0.816667,0.821158
7,seen,img_blur_20,ALL,200,0.600000,0.657437,0.014250,0.034906,0.585750,0.622531
8,seen,img_blur_20,AMOUNT,34,0.470588,0.529412,0.007353,0.028971,0.463235,0.500441
9,seen,img_blur_20,CONTACT_ADR,34,0.558824,0.635205,0.036765,0.039706,0.522059,0.595499
10,seen,img_blur_20,DATE,33,0.545455,0.619769,0.004545,0.035245,0.540909,0.584524
11,seen,img_blur_20,ID,33,0.575758,0.629726,0.015152,0.016667,0.560606,0.613059
12,seen,img_blur_20,ORG,33,0.636364,0.688023,0.019697,0.073098,0.616667,0.614925
13,seen,img_blur_20,PERSON,33,0.818182,0.847042,0.001515,0.015783,0.816667,0.831259
14,seen,img_blur_50,ALL,200,0.590000,0.646425,0.014250,0.034906,0.575750,0.611520
15,seen,img_blur_50,AMOUNT,34,0.411765,0.455882,0.007353,0.028971,0.404412,0.426912
16,seen,img_blur_50,CONTACT_ADR,34,0.558824,0.645009,0.036765,0.039706,0.522059,0.605303
17,seen,img_blur_50,DATE,33,0.545455,0.619769,0.004545,0.035245,0.540909,0.584524
18,seen,img_blur_50,ID,33,0.575758,0.629726,0.015152,0.016667,0.560606,0.613059
19,seen,img_blur_50,ORG,33,0.636364,0.686941,0.019697,0.073098,0.616667,0.613843
20,seen,img_blur_50,PERSON,33,0.818182,0.847042,0.001515,0.015783,0.816667,0.831259
21,seen,original,ALL,200,0.915000,0.937905,0.014250,0.034906,0.900750,0.902999
22,seen,original,AMOUNT,34,0.676471,0.720588,0.007353,0.028971,0.669118,0.691618
23,seen,original,CONTACT_ADR,34,0.911765,0.969608,0.036765,0.039706,0.875000,0.929902
24,seen,original,DATE,33,1.000000,1.000000,0.004545,0.035245,0.995455,0.964755
25,seen,original,ID,33,0.909091,0.942857,0.015152,0.016667,0.893939,0.926190
26,seen,original,ORG,33,1.000000,1.000000,0.019697,0.073098,0.980303,0.926902
27,seen,original,PERSON,33,1.000000,1.000000,0.001515,0.015783,0.998485,0.984217
28,unseen,img_black,ALL,200,0.035000,0.084044,0.001750,0.014448,0.033250,0.069596
29,unseen,img_black,AMOUNT,34,0.000000,0.068627,0.000000,0.019412,0.000000,0.049216
30,unseen,img_black,CONTACT_ADR,34,0.000000,0.042717,0.005882,0.008824,-0.005882,0.033894
31,unseen,img_black,DATE,33,0.030303,0.127489,0.000000,0.029516,0.030303,0.097974
32,unseen,img_black,ID,33,0.000000,0.014141,0.001515,0.002273,-0.001515,0.011869
33,unseen,img_black,ORG,33,0.121212,0.164983,0.003030,0.024303,0.118182,0.140680
34,unseen,img_black,PERSON,33,0.060606,0.088023,0.000000,0.002381,0.060606,0.085642
35,unseen,img_blur_20,ALL,200,0.030000,0.080742,0.001750,0.014448,0.028250,0.066294
36,unseen,img_blur_20,AMOUNT,34,0.000000,0.050980,0.000000,0.019412,0.000000,0.031569
37,unseen,img_blur_20,CONTACT_ADR,34,0.000000,0.034314,0.005882,0.008824,-0.005882,0.025490
38,unseen,img_blur_20,DATE,33,0.000000,0.111688,0.000000,0.029516,0.000000,0.082173
39,unseen,img_blur_20,ID,33,0.000000,0.017677,0.001515,0.002273,-0.001515,0.015404
40,unseen,img_blur_20,ORG,33,0.121212,0.185522,0.003030,0.024303,0.118182,0.161219
41,unseen,img_blur_20,PERSON,33,0.060606,0.086580,0.000000,0.002381,0.060606,0.084199
42,unseen,img_blur_50,ALL,200,0.030000,0.086629,0.001750,0.014448,0.028250,0.072181
43,unseen,img_blur_50,AMOUNT,34,0.000000,0.085294,0.000000,0.019412,0.000000,0.065882
44,unseen,img_blur_50,CONTACT_ADR,34,0.000000,0.034314,0.005882,0.008824,-0.005882,0.025490
45,unseen,img_blur_50,DATE,33,0.000000,0.108225,0.000000,0.029516,0.000000,0.078710
46,unseen,img_blur_50,ID,33,0.000000,0.020202,0.001515,0.002273,-0.001515,0.017929
47,unseen,img_blur_50,ORG,33,0.121212,0.186785,0.003030,0.024303,0.118182,0.162482
48,unseen,img_blur_50,PERSON,33,0.060606,0.086580,0.000000,0.002381,0.060606,0.084199
49,unseen,original,ALL,200,0.225000,0.275107,0.001750,0.014448,0.223250,0.260659
50,unseen,original,AMOUNT,34,0.235294,0.261765,0.000000,0.019412,0.235294,0.242353
51,unseen,original,CONTACT_ADR,34,0.117647,0.142157,0.005882,0.008824,0.111765,0.133333
52,unseen,original,DATE,33,0.303030,0.385859,0.000000,0.029516,0.303030,0.356343
53,unseen,original,ID,33,0.151515,0.196970,0.001515,0.002273,0.150000,0.194697
54,unseen,original,ORG,33,0.333333,0.353030,0.003030,0.024303,0.330303,0.328727
55,unseen,original,PERSON,33,0.212121,0.315296,0.000000,0.002381,0.212121,0.312915

In [9]:
# Model summaries
summary_rows = []
for name, outputs in {
    "baseline_florence2": baseline_outputs,
    "florence2_epoch10": florence_outputs,
    "qwen2b_epoch10_image_only": qwen2b_image_only_outputs,
    "qwen2b_epoch10_image_ocr": qwen2b_image_ocr_outputs,
    "qwen7b_epoch10_image_only": qwen7b_image_only_outputs,
}.items():
    metrics_df = outputs[2]
    overall = metrics_df[metrics_df["coarse_type"] == "ALL"].copy()
    overall["model"] = name
    summary_rows.append(overall)

summary_df = pd.concat(summary_rows, ignore_index=True)
summary_path = EXTRACTION_DIR / "extraction_summary.csv"

summary_experiment = comet_ml.Experiment(api_key=os.environ["COMET_API_KEY"], workspace="scfeel", project_name="qwen3-1")
summary_experiment.set_name("extraction-summary-v2")
save_csv_with_comet(summary_df, summary_path, summary_experiment, table_name="extraction_summary.csv")

image_only_df = summary_df[(summary_df["model"].isin(["baseline_florence2", "florence2_epoch10", "qwen2b_epoch10_image_only", "qwen7b_epoch10_image_only"])) & (summary_df["split"] == "seen")].copy()
image_only_df["model_label"] = image_only_df["model"].map({
    "baseline_florence2": "Florence-2 base",
    "florence2_epoch10": "Florence-2 (эпоха 30)",
    "qwen2b_epoch10_image_only": "Qwen2-VL-2B (эпоха 20)",
    "qwen7b_epoch10_image_only": "Qwen2-VL-7B (эпоха 10)",
})
heatmap_df = image_only_df.pivot(index="model_label", columns="scenario", values="corrected_em")
fig, ax = plt.subplots(figsize=(10, 5))
sns.heatmap(heatmap_df, annot=True, fmt=".3f", cmap="YlGnBu", ax=ax)
ax.set_title("Extraction по image-only сценариям (seen)")
ax.set_xlabel("Сценарий")
ax.set_ylabel("Модель")
plt.tight_layout()
summary_experiment.log_figure("extraction_heatmap_image_only_seen", fig)
plt.close(fig)

image_ocr_df = summary_df[(summary_df["model"] == "qwen2b_epoch10_image_ocr") & (summary_df["split"] == "seen")].copy()
if not image_ocr_df.empty:
    heatmap_df = image_ocr_df.assign(model_label="Qwen2-VL-2B (epoch 10, image+OCR)").pivot(index="model_label", columns="scenario", values="corrected_em")
    fig, ax = plt.subplots(figsize=(8, 3))
    sns.heatmap(heatmap_df, annot=True, fmt=".3f", cmap="YlOrBr", ax=ax)
    ax.set_title("Extraction по image+OCR сценариям (seen)")
    ax.set_xlabel("Сценарий")
    ax.set_ylabel("")
    plt.tight_layout()
    summary_experiment.log_figure("extraction_heatmap_image_ocr_seen", fig)
    plt.close(fig)

display(summary_df)
summary_experiment.end()

COMET WARNING: To get all data logged automatically, import comet_ml before the following modules: sklearn, tensorflow, torch, keras.
COMET WARNING: As you are running in a Jupyter environment, you will need to call `experiment.end()` when finished to ensure all metrics and code are logged before exiting.
COMET INFO: Experiment is live on comet.com https://www.comet.com/scfeel/qwen3-1/32eeb008e4ff493ab133eaf981bec60f

COMET WARNING: log_asset_data(..., file_name=...) is deprecated; use log_asset_data(..., name=...)

,split,scenario,coarse_type,n_examples,exact_match,token_f1,random_em,random_f1,corrected_em,corrected_f1,model
0,seen,img_black,ALL,200,0.000,0.023929,0.01425,0.034906,-0.01425,-0.010977,baseline_florence2
1,seen,img_blur_20,ALL,200,0.000,0.024062,0.01425,0.034906,-0.01425,-0.010843,baseline_florence2
2,seen,img_blur_50,ALL,200,0.000,0.024062,0.01425,0.034906,-0.01425,-0.010843,baseline_florence2
3,seen,original,ALL,200,0.000,0.041350,0.01425,0.034906,-0.01425,0.006444,baseline_florence2
4,unseen,img_black,ALL,200,0.000,0.022494,0.00175,0.014448,-0.00175,0.008046,baseline_florence2
5,unseen,img_blur_20,ALL,200,0.000,0.023639,0.00175,0.014448,-0.00175,0.009191,baseline_florence2
6,unseen,img_blur_50,ALL,200,0.000,0.023589,0.00175,0.014448,-0.00175,0.009141,baseline_florence2
7,unseen,original,ALL,200,0.000,0.050198,0.00175,0.014448,-0.00175,0.035750,baseline_florence2
8,seen,img_black,ALL,200,0.095,0.228727,0.01425,0.034906,0.08075,0.193821,florence2_epoch10
9,seen,img_blur_20,ALL,200,0.095,0.227552,0.01425,0.034906,0.08075,0.192647,florence2_epoch10
10,seen,img_blur_50,ALL,200,0.095,0.225275,0.01425,0.034906,0.08075,0.190369,florence2_epoch10
11,seen,original,ALL,200,0.945,0.963167,0.01425,0.034906,0.93075,0.928261,florence2_epoch10
12,unseen,img_black,ALL,200,0.010,0.060067,0.00175,0.014448,0.00825,0.045620,florence2_epoch10
13,unseen,img_blur_20,ALL,200,0.010,0.061734,0.00175,0.014448,0.00825,0.047286,florence2_epoch10
14,unseen,img_blur_50,ALL,200,0.010,0.065067,0.00175,0.014448,0.00825,0.050620,florence2_epoch10
15,unseen,original,ALL,200,0.125,0.228508,0.00175,0.014448,0.12325,0.214060,florence2_epoch10
16,seen,img_black,ALL,200,0.490,0.557242,0.01425,0.034906,0.47575,0.522337,qwen2b_epoch10_image_only
17,seen,img_blur_20,ALL,200,0.495,0.564454,0.01425,0.034906,0.48075,0.529548,qwen2b_epoch10_image_only
18,seen,img_blur_50,ALL,200,0.505,0.568870,0.01425,0.034906,0.49075,0.533964,qwen2b_epoch10_image_only
19,seen,original,ALL,200,0.820,0.852841,0.01425,0.034906,0.80575,0.817935,qwen2b_epoch10_image_only
20,unseen,img_black,ALL,200,0.015,0.054599,0.00175,0.014448,0.01325,0.040151,qwen2b_epoch10_image_only
21,unseen,img_blur_20,ALL,200,0.020,0.050648,0.00175,0.014448,0.01825,0.036200,qwen2b_epoch10_image_only
22,unseen,img_blur_50,ALL,200,0.015,0.049676,0.00175,0.014448,0.01325,0.035228,qwen2b_epoch10_image_only
23,unseen,original,ALL,200,0.180,0.215651,0.00175,0.014448,0.17825,0.201203,qwen2b_epoch10_image_only
24,seen,img_black__ocr_mask__k_0,ALL,200,0.030,0.110806,0.01425,0.034906,0.01575,0.075901,qwen2b_epoch10_image_ocr
25,seen,img_none__ocr_mask__k_0,ALL,200,0.330,0.387821,0.01425,0.034906,0.31575,0.352916,qwen2b_epoch10_image_ocr
26,unseen,img_black__ocr_mask__k_0,ALL,200,0.015,0.099003,0.00175,0.014448,0.01325,0.084555,qwen2b_epoch10_image_ocr
27,unseen,img_none__ocr_mask__k_0,ALL,200,0.155,0.249228,0.00175,0.014448,0.15325,0.234780,qwen2b_epoch10_image_ocr
28,seen,img_black,ALL,200,0.590,0.647342,0.01425,0.034906,0.57575,0.612436,qwen7b_epoch10_image_only
29,seen,img_blur_20,ALL,200,0.600,0.657437,0.01425,0.034906,0.58575,0.622531,qwen7b_epoch10_image_only
30,seen,img_blur_50,ALL,200,0.590,0.646425,0.01425,0.034906,0.57575,0.611520,qwen7b_epoch10_image_only
31,seen,original,ALL,200,0.915,0.937905,0.01425,0.034906,0.90075,0.902999,qwen7b_epoch10_image_only
32,unseen,img_black,ALL,200,0.035,0.084044,0.00175,0.014448,0.03325,0.069596,qwen7b_epoch10_image_only
33,unseen,img_blur_20,ALL,200,0.030,0.080742,0.00175,0.014448,0.02825,0.066294,qwen7b_epoch10_image_only
34,unseen,img_blur_50,ALL,200,0.030,0.086629,0.00175,0.014448,0.02825,0.072181,qwen7b_epoch10_image_only
35,unseen,original,ALL,200,0.225,0.275107,0.00175,0.014448,0.22325,0.260659,qwen7b_epoch10_image_only

COMET INFO: The process of logging environment details (conda environment, git patch) is underway. Please be patient as this may take some time.
COMET WARNING: Couldn't retrieve and log Google Colab notebook content, reason: 'NoneType' object is not subscriptable
COMET INFO: ---------------------------------------------------------------------------------------
COMET INFO: Comet.ml Experiment Summary
COMET INFO: ---------------------------------------------------------------------------------------
COMET INFO:   Data:
COMET INFO:     display_summary_level : 1
COMET INFO:     name                  : extraction-summary-v2
COMET INFO:     url                   : https://www.comet.com/scfeel/qwen3-1/32eeb008e4ff493ab133eaf981bec60f
COMET INFO:   Others:
COMET INFO:     Name         : extraction-summary-v2
COMET INFO:     notebook_url : https://colab.research.google.com/notebook#23_data_extraction_v2-jvsc-17603f68-61d9-4ee8-ac45-070691eb2f613c1eee6f-0ab7-43f3-a66a-9de7128a3766.ipynb
COMET INFO:   Uploads:
COMET INFO:     asset                    : 2 (5.45 KB)
COMET INFO:     dataframe                : 1 (5.54 KB)
COMET INFO:     environment details      : 1
COMET INFO:     figures                  : 2
COMET INFO:     filename                 : 1
COMET INFO:     git metadata             : 1
COMET INFO:     git-patch (uncompressed) : 1 (68.35 MB)
COMET INFO:     installed packages       : 1
COMET INFO:     notebook                 : 1
COMET INFO:     os packages              : 1
COMET INFO:     source_code              : 1
COMET INFO:
COMET WARNING: To get all data logged automatically, import comet_ml before the following modules: sklearn, tensorflow, torch, keras.

In [10]:
# Saved outputs
saved_csvs = sorted(str(path) for path in EXTRACTION_DIR.glob("*.csv"))
display(pd.DataFrame({"csv_path": saved_csvs}))
print({"csv_count": len(saved_csvs), "output_dir": str(EXTRACTION_DIR)})

                                             csv_path
0   /content/drive/MyDrive/course_work2026/artifac...
1   /content/drive/MyDrive/course_work2026/artifac...
2   /content/drive/MyDrive/course_work2026/artifac...
3   /content/drive/MyDrive/course_work2026/artifac...
4   /content/drive/MyDrive/course_work2026/artifac...
5   /content/drive/MyDrive/course_work2026/artifac...
6   /content/drive/MyDrive/course_work2026/artifac...
7   /content/drive/MyDrive/course_work2026/artifac...
8   /content/drive/MyDrive/course_work2026/artifac...
9   /content/drive/MyDrive/course_work2026/artifac...
10  /content/drive/MyDrive/course_work2026/artifac...
11  /content/drive/MyDrive/course_work2026/artifac...
12  /content/drive/MyDrive/course_work2026/artifac...
13  /content/drive/MyDrive/course_work2026/artifac...
14  /content/drive/MyDrive/course_work2026/artifac...
15  /content/drive/MyDrive/course_work2026/artifac...
16  /content/drive/MyDrive/course_work2026/artifac...
17  /content/drive/MyDrive/course_work2026/artifac...
18  /content/drive/MyDrive/course_work2026/artifac...
19  /content/drive/MyDrive/course_work2026/artifac...
20  /content/drive/MyDrive/course_work2026/artifac...

{'csv_count': 21, 'output_dir': '/content/drive/MyDrive/course_work2026/artifacts_v2_controlled/privacy_attacks/extraction'}